// Each entry: name, country, dates, x (-10 left … 10 right), y (-10 authoritarian … 10 libertarian),
// blurb (short justification), aliases (lowercase strings people might type)
const POLITICIANS = [
  // --- authoritarian historical/modern rulers ---
  {name:"Omar al-Bashir", country:"Sudan", dates:"1989–2019", x:3, y:-6.5, blurb:"Islamist military ruler, ousted after mass protests.", aliases:["bashir","omar al-bashir","omar bashir"], flags:["warcrimes"]},
  {name:"Kim Jong-il", country:"North Korea", dates:"1994–2011", x:-9, y:-9.5, blurb:"Totalitarian command economy, absolute personality cult.", aliases:["kim jong il","kim jong-il"]},
  {name:"Kim Jong-un", country:"North Korea", dates:"2011–present", x:-9, y:-9.5, blurb:"Continues totalitarian one-party rule and command economy.", aliases:["kim jong un","kim jong-un","kim"]},
  {name:"Than Shwe", country:"Myanmar/Burma", dates:"1992–2011", x:4, y:-7.5, blurb:"Military junta leader, nationalist economic control.", aliases:["than shwe"]},
  {name:"Robert Mugabe", country:"Zimbabwe", dates:"1980–2017", x:-6, y:-5.8, blurb:"Land redistribution and socialist rhetoric, long one-party rule.", aliases:["mugabe","robert mugabe"]},
  {name:"Islam Karimov", country:"Uzbekistan", dates:"1989–2016", x:-3, y:-7.7, blurb:"Post-Soviet strongman, state-controlled economy.", aliases:["karimov","islam karimov"]},
  {name:"Hu Jintao", country:"China", dates:"2002–2012", x:-5, y:-5.5, blurb:"Socialist market economy under one-party rule.", aliases:["hu jintao"]},
  {name:"Xi Jinping", country:"China", dates:"2012–present", x:-5, y:-7, blurb:"Tightened one-party control, state-directed economy.", aliases:["xi jinping","xi"]},
  {name:"King Abdullah", country:"Saudi Arabia", dates:"2005–2015", x:7, y:-5, blurb:"Absolute monarchy, market economy for elites.", aliases:["king abdullah","abdullah saudi"]},
  {name:"Mohammed bin Salman", country:"Saudi Arabia", dates:"2017–present (Crown Prince/PM)", x:6, y:-5.5, blurb:"Economic liberalization drive alongside tight political control.", aliases:["mbs","mohammed bin salman","bin salman"]},
  {name:"Saparmurat Niyazov", country:"Turkmenistan", dates:"1985–2006", x:-7, y:-9, blurb:"Extreme personality cult, state-controlled economy.", aliases:["niyazov"]},
  {name:"Ali Khamenei", country:"Iran", dates:"1989–present", x:5, y:-6.5, blurb:"Theocratic conservative Supreme Leader.", aliases:["khamenei","ali khamenei"]},
  {name:"Teodoro Obiang Nguema", country:"Equatorial Guinea", dates:"1979–present", x:2, y:-7.5, blurb:"Longest-ruling head of state, oil-fueled kleptocracy.", aliases:["obiang","teodoro obiang"]},
  {name:"Muammar al-Qaddafi", country:"Libya", dates:"1969–2011", x:-7, y:-7, blurb:"\"Islamic socialism,\" anti-capitalist Jamahiriya system.", aliases:["gaddafi","qaddafi","muammar gaddafi"], flags:["warcrimes"]},
  {name:"King Mswati III", country:"Eswatini/Swaziland", dates:"1986–present", x:6, y:-5.5, blurb:"Absolute monarch, one of the world's last.", aliases:["mswati","king mswati"]},
  {name:"Pervez Musharraf", country:"Pakistan", dates:"1999–2008", x:3, y:-3.5, blurb:"Military ruler with market-friendly reforms.", aliases:["musharraf"]},
  {name:"Aleksandr Lukashenko", country:"Belarus", dates:"1994–present", x:-6.3, y:-6.2, blurb:"Soviet-nostalgic state-controlled economy.", aliases:["lukashenko"]},
  {name:"Fidel Castro", country:"Cuba", dates:"1959–2008", x:-9.5, y:-8, blurb:"Communist one-party state.", aliases:["castro","fidel castro"]},
  {name:"Isaias Afwerki", country:"Eritrea", dates:"1993–present", x:-6, y:-8.3, blurb:"One-party state, no elections ever held.", aliases:["afwerki","isaias"]},
  {name:"Bashar al-Assad", country:"Syria", dates:"2000–2024", x:-4, y:-7.3, blurb:"Ba'athist secular Arab socialism, ousted Dec 2024.", aliases:["assad","bashar al-assad","bashar assad"], flags:["warcrimes"]},
  {name:"Meles Zenawi", country:"Ethiopia", dates:"1991–2012", x:-5, y:-5, blurb:"Developmental state, \"revolutionary democracy.\"", aliases:["meles zenawi","meles"]},
  {name:"Paul Biya", country:"Cameroon", dates:"1982–present", x:-1, y:-5, blurb:"Personalist rule, nominally socialist party heritage.", aliases:["biya","paul biya"]},
  {name:"Vladimir Putin", country:"Russia", dates:"1999–present", x:1, y:-8, blurb:"State-capitalist economy under centralized authoritarian rule.", aliases:["putin","vladimir putin"], flags:["warcrimes"]},
  {name:"Nicolás Maduro", country:"Venezuela", dates:"2013–present", x:-8, y:-8, blurb:"Socialist command economy, contested elections.", aliases:["maduro","nicolas maduro"]},
  {name:"Daniel Ortega", country:"Nicaragua", dates:"2007–present", x:-7, y:-8, blurb:"Sandinista socialist rule, crackdowns on opposition.", aliases:["ortega","daniel ortega"]},
  {name:"Recep Tayyip Erdoğan", country:"Turkey", dates:"2003–present", x:2, y:-5.5, blurb:"Conservative-nationalist, growing executive power.", aliases:["erdogan","recep tayyip erdogan"]},

  // --- 20th century dictators/leaders ---
  {name:"Adolf Hitler", country:"Germany", dates:"1933–1945", x:1, y:-10, blurb:"Fascist totalitarian dictatorship.", aliases:["hitler","adolf hitler"]},
  {name:"Joseph Stalin", country:"Soviet Union", dates:"1924–1953", x:-9.5, y:-9.5, blurb:"Totalitarian command economy, mass purges.", aliases:["stalin"]},
  {name:"Mao Zedong", country:"China", dates:"1949–1976", x:-9.5, y:-9, blurb:"Communist revolution, Cultural Revolution repression.", aliases:["mao","mao zedong"]},
  {name:"Benito Mussolini", country:"Italy", dates:"1922–1943", x:2, y:-9, blurb:"Fascist corporatist state.", aliases:["mussolini"]},
  {name:"Francisco Franco", country:"Spain", dates:"1939–1975", x:4, y:-8.5, blurb:"Right-wing nationalist military dictatorship.", aliases:["franco","francisco franco"]},
  {name:"Augusto Pinochet", country:"Chile", dates:"1973–1990", x:6, y:-8, blurb:"Free-market reforms under brutal military rule.", aliases:["pinochet"]},
  {name:"Pol Pot", country:"Cambodia", dates:"1975–1979", x:-9, y:-10, blurb:"Agrarian communist genocide.", aliases:["pol pot"]},
  {name:"Idi Amin", country:"Uganda", dates:"1971–1979", x:-1, y:-9, blurb:"Erratic military dictatorship.", aliases:["idi amin"]},
  {name:"Saddam Hussein", country:"Iraq", dates:"1979–2003", x:-2, y:-9, blurb:"Ba'athist secular nationalist dictatorship.", aliases:["saddam","saddam hussein"], flags:["warcrimes"]},
  {name:"Slobodan Milošević", country:"Serbia/Yugoslavia", dates:"1989–2000", x:-3, y:-7.5, blurb:"Nationalist authoritarian, ethnic conflict.", aliases:["milosevic"], flags:["warcrimes"]},
  {name:"Josip Broz Tito", country:"Yugoslavia", dates:"1953–1980", x:-6, y:-4.5, blurb:"Non-aligned market socialism, relatively liberalized communism.", aliases:["tito"]},
  {name:"Nicolae Ceaușescu", country:"Romania", dates:"1965–1989", x:-8, y:-9, blurb:"Hardline Stalinist personality cult.", aliases:["ceausescu"]},
  {name:"Kim Il-sung", country:"North Korea", dates:"1948–1994", x:-9, y:-9.5, blurb:"Founder of totalitarian juche state.", aliases:["kim il sung","kim il-sung"]},
  {name:"Ho Chi Minh", country:"Vietnam", dates:"1945–1969", x:-8, y:-7, blurb:"Communist revolutionary and nation-founder.", aliases:["ho chi minh"]},
  {name:"Deng Xiaoping", country:"China", dates:"1978–1989", x:-3, y:-6.5, blurb:"Market reforms within one-party rule (\"socialism with Chinese characteristics\").", aliases:["deng xiaoping","deng"]},
  {name:"Mikhail Gorbachev", country:"Soviet Union", dates:"1985–1991", x:-6, y:-1, blurb:"Glasnost/perestroika reforms loosened authoritarian control.", aliases:["gorbachev"]},

  // --- widely admired reformers / democratic icons ---
  {name:"Nelson Mandela", country:"South Africa", dates:"1994–1999", x:-4, y:7, blurb:"Anti-apartheid leader, reconciliation-focused democracy.", aliases:["mandela","nelson mandela"]},
  {name:"Mahatma Gandhi", country:"India", dates:"Independence leader", x:-2, y:8, blurb:"Nonviolent independence movement, civil liberties focus.", aliases:["gandhi","mahatma gandhi"]},

  // --- US ---
  {name:"Donald Trump", country:"United States", dates:"2017–2021, 2025–present", x:4, y:-3, blurb:"Right-populist economics, disputed executive-power norms.", aliases:["trump","donald trump","donald j trump"]},
  {name:"Joe Biden", country:"United States", dates:"2021–2025", x:-2, y:4, blurb:"Center-left economics, standard democratic norms.", aliases:["biden","joe biden"]},
  {name:"Barack Obama", country:"United States", dates:"2009–2017", x:-2, y:5, blurb:"Center-left, expanded healthcare access.", aliases:["obama","barack obama"]},
  {name:"George W. Bush", country:"United States", dates:"2001–2009", x:5, y:1, blurb:"Tax cuts, expanded post-9/11 executive/security powers.", aliases:["bush","george w bush","gw bush"]},
  {name:"Bill Clinton", country:"United States", dates:"1993–2001", x:1, y:4, blurb:"Centrist \"Third Way\" economics.", aliases:["clinton","bill clinton"]},
  {name:"Ronald Reagan", country:"United States", dates:"1981–1989", x:7, y:2, blurb:"Free-market deregulation, tax cuts.", aliases:["reagan","ronald reagan"]},
  {name:"Franklin D. Roosevelt", country:"United States", dates:"1933–1945", x:-6, y:2, blurb:"New Deal state intervention in the economy.", aliases:["fdr","franklin roosevelt","franklin d roosevelt"]},
  {name:"Bernie Sanders", country:"United States", dates:"Senator, not head of state", x:-8, y:7, blurb:"Democratic socialist, strong civil-liberties record.", aliases:["bernie","bernie sanders","sanders"]},

  // --- UK ---
  {name:"Keir Starmer", country:"United Kingdom", dates:"2024–present", x:-2, y:4, blurb:"Center-left Labour, standard democratic governance.", aliases:["starmer","keir starmer"]},
  {name:"Rishi Sunak", country:"United Kingdom", dates:"2022–2024", x:5, y:3, blurb:"Fiscally conservative Conservative PM.", aliases:["sunak","rishi sunak"]},
  {name:"Liz Truss", country:"United Kingdom", dates:"2022 (49 days)", x:7, y:3, blurb:"Aggressive free-market tax-cutting agenda.", aliases:["liz truss","truss"]},
  {name:"Boris Johnson", country:"United Kingdom", dates:"2019–2022", x:4, y:1, blurb:"Populist-right, Brexit, some executive overreach controversies.", aliases:["boris johnson","boris"]},
  {name:"Theresa May", country:"United Kingdom", dates:"2016–2019", x:3, y:2, blurb:"Centrist Conservative, Brexit negotiations.", aliases:["theresa may"]},
  {name:"David Cameron", country:"United Kingdom", dates:"2010–2016", x:5, y:3, blurb:"Austerity economics, coalition government.", aliases:["david cameron","cameron"]},
  {name:"Gordon Brown", country:"United Kingdom", dates:"2007–2010", x:-2, y:4, blurb:"Labour, financial-crisis response.", aliases:["gordon brown"]},
  {name:"Tony Blair", country:"United Kingdom", dates:"1997–2007", x:0, y:2, blurb:"\"New Labour\" centrism.", aliases:["tony blair","blair"]},
  {name:"Margaret Thatcher", country:"United Kingdom", dates:"1979–1990", x:8, y:1, blurb:"Privatization, free-market deregulation.", aliases:["thatcher","margaret thatcher"]},
  {name:"Winston Churchill", country:"United Kingdom", dates:"1940–1945, 1951–1955", x:3, y:3, blurb:"Wartime leadership, traditional conservative economics.", aliases:["churchill","winston churchill"]},
  {name:"Andy Burnham", country:"United Kingdom", dates:"2017–present (Gtr Manchester Mayor)", x:-6, y:3, blurb:"Left-leaning Labour, no authoritarian record.", aliases:["andy burnham","burnham"]},
  {name:"Nigel Farage", country:"United Kingdom", dates:"2024–present, Reform UK leader", x:6, y:-2, blurb:"Right-populist, nationalist on immigration.", aliases:["farage","nigel farage"]},
  {name:"Rupert Lowe", country:"United Kingdom", dates:"2025–present, Restore Britain leader", x:8, y:-5, blurb:"Further right and more authoritarian-leaning than Farage.", aliases:["rupert lowe","lowe"]},
  {name:"Jeremy Corbyn", country:"United Kingdom", dates:"Labour leader 2015–2020", x:-8, y:4, blurb:"Democratic socialist, strong civil-liberties positions.", aliases:["corbyn","jeremy corbyn"]},

  // --- France ---
  {name:"Emmanuel Macron", country:"France", dates:"2017–present, President (not PM)", x:3, y:1, blurb:"Centrist market reforms, standard democratic leader.", aliases:["macron","emmanuel macron"]},
  {name:"Marine Le Pen", country:"France", dates:"RN Assembly leader since 2022", x:2, y:-5, blurb:"Nationalist right, protectionist economics.", aliases:["le pen","marine le pen"]},
  {name:"Charles de Gaulle", country:"France", dates:"1959–1969", x:2, y:0, blurb:"Nationalist, strong-executive Fifth Republic founder.", aliases:["de gaulle","charles de gaulle"]},

  // --- Germany ---
  {name:"Friedrich Merz", country:"Germany", dates:"2025–present", x:4, y:2, blurb:"Conservative CDU chancellor, market-oriented.", aliases:["merz","friedrich merz"]},
  {name:"Olaf Scholz", country:"Germany", dates:"2021–2025", x:-1, y:3, blurb:"Center-left SPD chancellor.", aliases:["scholz","olaf scholz"]},
  {name:"Angela Merkel", country:"Germany", dates:"2005–2021", x:1, y:3, blurb:"Centrist CDU, long-tenured stable democratic rule.", aliases:["merkel","angela merkel"]},
  {name:"Helmut Kohl", country:"Germany", dates:"1982–1998", x:3, y:2, blurb:"Center-right, German reunification.", aliases:["kohl","helmut kohl"]},
  {name:"Willy Brandt", country:"Germany", dates:"1969–1974", x:-4, y:4, blurb:"Social democrat, Ostpolitik détente policy.", aliases:["willy brandt","brandt"]},

  // --- rest of world (current-ish) ---
  {name:"Volodymyr Zelenskyy", country:"Ukraine", dates:"2019–present", x:-1, y:2, blurb:"Wartime democratic leader, some emergency-powers debate.", aliases:["zelensky","zelenskyy","volodymyr zelensky"]},
  {name:"Narendra Modi", country:"India", dates:"2014–present", x:3, y:-3, blurb:"Hindu-nationalist right, market reforms, press-freedom concerns.", aliases:["modi","narendra modi"]},
  {name:"Justin Trudeau", country:"Canada", dates:"2015–2025", x:-2, y:4, blurb:"Center-left Liberal, standard democratic governance.", aliases:["trudeau","justin trudeau"]},
  {name:"Giorgia Meloni", country:"Italy", dates:"2022–present", x:4, y:-1, blurb:"National-conservative right, within EU democratic norms.", aliases:["meloni","giorgia meloni"]},
  {name:"Pedro Sánchez", country:"Spain", dates:"2018–present", x:-3, y:3, blurb:"Center-left PSOE, standard democratic governance.", aliases:["pedro sanchez","sanchez"]},
  {name:"Lula da Silva", country:"Brazil", dates:"2003–2011, 2023–present", x:-5, y:3, blurb:"Left-leaning Workers' Party, democratic governance.", aliases:["lula","lula da silva"]},
  {name:"Jair Bolsonaro", country:"Brazil", dates:"2019–2023", x:5, y:-4, blurb:"Right-populist, some institutional-norm controversies.", aliases:["bolsonaro","jair bolsonaro"]},
  {name:"Javier Milei", country:"Argentina", dates:"2023–present", x:9, y:0, blurb:"Libertarian free-market radical, minimal-state agenda.", aliases:["milei","javier milei"]},
  {name:"Cyril Ramaphosa", country:"South Africa", dates:"2018–present", x:-3, y:3, blurb:"Center-left ANC, democratic governance.", aliases:["ramaphosa","cyril ramaphosa"]},
  {name:"Anthony Albanese", country:"Australia", dates:"2022–present", x:-3, y:4, blurb:"Center-left Labor, standard democratic governance.", aliases:["albanese","anthony albanese"]},
  {name:"Benjamin Netanyahu", country:"Israel", dates:"1996–1999, 2009–present", x:6, y:-3, blurb:"Right-leaning market reforms, judicial-overhaul controversy.", aliases:["netanyahu","bibi","benjamin netanyahu"], flags:["warcrimes"]},

  // --- Asia ---
  {name:"Shinzo Abe", country:"Japan", dates:"2006–2007, 2012–2020", x:5, y:1, blurb:"Conservative LDP, market reforms (\"Abenomics\").", aliases:["abe","shinzo abe"]},
  {name:"Fumio Kishida", country:"Japan", dates:"2021–2024", x:3, y:2, blurb:"Moderate LDP conservative.", aliases:["kishida","fumio kishida"]},
  {name:"Shigeru Ishiba", country:"Japan", dates:"2024–present", x:2, y:2, blurb:"Moderate LDP, defense-focused.", aliases:["ishiba","shigeru ishiba"]},
  {name:"Junichiro Koizumi", country:"Japan", dates:"2001–2006", x:6, y:1, blurb:"Privatization-focused LDP reformer.", aliases:["koizumi","junichiro koizumi"]},
  {name:"Rodrigo Duterte", country:"Philippines", dates:"2016–2022", x:-1, y:-7, blurb:"Populist, violent anti-drug crackdown.", aliases:["duterte","rodrigo duterte"]},
  {name:"Ferdinand Marcos Jr", country:"Philippines", dates:"2022–present", x:2, y:-3, blurb:"Dynastic conservative rule.", aliases:["marcos jr","bongbong marcos","ferdinand marcos jr"]},
  {name:"Joko Widodo", country:"Indonesia", dates:"2014–2024", x:-1, y:1, blurb:"Pragmatic developmentalist, democratic norms.", aliases:["jokowi","joko widodo"]},
  {name:"Prabowo Subianto", country:"Indonesia", dates:"2024–present", x:1, y:-2, blurb:"Nationalist, ex-military background.", aliases:["prabowo","prabowo subianto"]},
  {name:"Lee Kuan Yew", country:"Singapore", dates:"1959–1990", x:3, y:-4, blurb:"Market economy under tightly controlled politics.", aliases:["lee kuan yew"]},
  {name:"Lee Hsien Loong", country:"Singapore", dates:"2004–2024", x:3, y:-2, blurb:"Continued PAP dominance, market economy.", aliases:["lee hsien loong"]},
  {name:"Imran Khan", country:"Pakistan", dates:"2018–2022", x:-1, y:-2, blurb:"Populist, later jailed amid political crackdown.", aliases:["imran khan"]},
  {name:"Sheikh Hasina", country:"Bangladesh", dates:"2009–2024", x:-3, y:-6, blurb:"Increasingly authoritarian one-party dominance.", aliases:["sheikh hasina","hasina"]},
  {name:"Muhammad Yunus", country:"Bangladesh", dates:"2024–present, interim leader", x:-2, y:3, blurb:"Microfinance pioneer leading interim reform government.", aliases:["yunus","muhammad yunus"]},
  {name:"Aung San Suu Kyi", country:"Myanmar", dates:"2016–2021", x:-2, y:4, blurb:"Democracy icon, later overthrown by coup.", aliases:["aung san suu kyi","suu kyi"]},
  {name:"Hun Sen", country:"Cambodia", dates:"1985–2023", x:-3, y:-7, blurb:"Long-ruling one-party dominance.", aliases:["hun sen"]},
  {name:"Thaksin Shinawatra", country:"Thailand", dates:"2001–2006", x:1, y:-3, blurb:"Populist business tycoon, ousted by coup.", aliases:["thaksin","thaksin shinawatra"]},
  {name:"Prayut Chan-o-cha", country:"Thailand", dates:"2014–2023", x:2, y:-6, blurb:"Military junta leader turned civilian PM.", aliases:["prayut","prayut chan-o-cha"]},
  {name:"Mahinda Rajapaksa", country:"Sri Lanka", dates:"2005–2015", x:-1, y:-5, blurb:"Nationalist, centralized executive power.", aliases:["mahinda rajapaksa","rajapaksa"]},
  {name:"Indira Gandhi", country:"India", dates:"1966–1977, 1980–1984", x:-4, y:-4, blurb:"State-led economy, imposed emergency rule 1975-77.", aliases:["indira gandhi"]},
  {name:"Jawaharlal Nehru", country:"India", dates:"1947–1964", x:-5, y:3, blurb:"Democratic socialist, founding PM.", aliases:["nehru","jawaharlal nehru"]},

  // --- Middle East ---
  {name:"Mohammed bin Zayed", country:"UAE", dates:"2022–present", x:5, y:-6, blurb:"Absolute rule, market-friendly economy.", aliases:["mbz","mohammed bin zayed"]},
  {name:"Hosni Mubarak", country:"Egypt", dates:"1981–2011", x:1, y:-7, blurb:"Long authoritarian rule, ousted in Arab Spring.", aliases:["mubarak","hosni mubarak"]},
  {name:"Abdel Fattah el-Sisi", country:"Egypt", dates:"2014–present", x:1, y:-7, blurb:"Military-backed authoritarian rule.", aliases:["sisi","el-sisi","abdel fattah el-sisi"]},
  {name:"Anwar Sadat", country:"Egypt", dates:"1970–1981", x:1, y:-5, blurb:"Economic liberalization, centralized power.", aliases:["sadat","anwar sadat"]},
  {name:"Yasser Arafat", country:"Palestine", dates:"1994–2004", x:-3, y:-4, blurb:"PLO/PA leader, centralized personal authority.", aliases:["arafat","yasser arafat"]},
  {name:"Mahmoud Abbas", country:"Palestine", dates:"2005–present", x:-2, y:-4, blurb:"PA leader, term repeatedly extended without new elections.", aliases:["abbas","mahmoud abbas"]},
  {name:"Yitzhak Rabin", country:"Israel", dates:"1974–1977, 1992–1995", x:-1, y:3, blurb:"Peace-process focused, standard democratic norms.", aliases:["rabin","yitzhak rabin"]},
  {name:"Golda Meir", country:"Israel", dates:"1969–1974", x:-3, y:2, blurb:"Labor-aligned, standard democratic norms.", aliases:["golda meir"]},
  {name:"King Hussein", country:"Jordan", dates:"1952–1999", x:3, y:-3, blurb:"Monarchy with limited pluralism.", aliases:["king hussein"]},
  {name:"King Abdullah II", country:"Jordan", dates:"1999–present", x:3, y:-3, blurb:"Monarchy with limited pluralism.", aliases:["king abdullah ii","abdullah ii"]},
  {name:"Hassan Rouhani", country:"Iran", dates:"2013–2021", x:2, y:-5, blurb:"Relatively moderate cleric within theocratic system.", aliases:["rouhani","hassan rouhani"]},
  {name:"Mahmoud Ahmadinejad", country:"Iran", dates:"2005–2013", x:-2, y:-7, blurb:"Populist-conservative, hardline theocratic system.", aliases:["ahmadinejad","mahmoud ahmadinejad"]},

  // --- Africa ---
  {name:"Jomo Kenyatta", country:"Kenya", dates:"1964–1978", x:1, y:-3, blurb:"Founding president, centralized rule.", aliases:["jomo kenyatta"]},
  {name:"Uhuru Kenyatta", country:"Kenya", dates:"2013–2022", x:2, y:-2, blurb:"Market-oriented, democratic transitions of power.", aliases:["uhuru kenyatta","uhuru"]},
  {name:"William Ruto", country:"Kenya", dates:"2022–present", x:1, y:-1, blurb:"Market-oriented, democratic governance.", aliases:["ruto","william ruto"]},
  {name:"Julius Nyerere", country:"Tanzania", dates:"1964–1985", x:-6, y:-2, blurb:"African socialism (Ujamaa), one-party state.", aliases:["nyerere","julius nyerere"]},
  {name:"Kenneth Kaunda", country:"Zambia", dates:"1964–1991", x:-5, y:-3, blurb:"African socialism, one-party rule.", aliases:["kaunda","kenneth kaunda"]},
  {name:"Jerry Rawlings", country:"Ghana", dates:"1981–2001", x:-4, y:-5, blurb:"Military-populist, later democratized.", aliases:["rawlings","jerry rawlings"]},
  {name:"Nana Akufo-Addo", country:"Ghana", dates:"2017–2025", x:2, y:1, blurb:"Center-right, democratic governance.", aliases:["akufo-addo","nana akufo-addo"]},
  {name:"Muhammadu Buhari", country:"Nigeria", dates:"2015–2023", x:-1, y:-3, blurb:"Anti-corruption focus, some authoritarian tendencies.", aliases:["buhari","muhammadu buhari"]},
  {name:"Bola Tinubu", country:"Nigeria", dates:"2023–present", x:2, y:-2, blurb:"Market reforms, democratic governance.", aliases:["tinubu","bola tinubu"]},
  {name:"Olusegun Obasanjo", country:"Nigeria", dates:"1999–2007", x:0, y:-1, blurb:"Ex-military turned democratic president.", aliases:["obasanjo","olusegun obasanjo"]},
  {name:"Thabo Mbeki", country:"South Africa", dates:"1999–2008", x:-2, y:2, blurb:"Market-friendly ANC, democratic norms.", aliases:["mbeki","thabo mbeki"]},
  {name:"F.W. de Klerk", country:"South Africa", dates:"1989–1994", x:3, y:-2, blurb:"Ended apartheid, transitioned to democracy.", aliases:["de klerk","fw de klerk"]},
  {name:"Jacob Zuma", country:"South Africa", dates:"2009–2018", x:-2, y:-3, blurb:"Populist ANC, corruption scandals.", aliases:["zuma","jacob zuma"], flags:["corruption"]},
  {name:"Yoweri Museveni", country:"Uganda", dates:"1986–present", x:-1, y:-6, blurb:"Long-ruling, restricts opposition.", aliases:["museveni","yoweri museveni"]},
  {name:"Paul Kagame", country:"Rwanda", dates:"2000–present", x:-1, y:-6, blurb:"Developmental authoritarianism, tight political control.", aliases:["kagame","paul kagame"]},
  {name:"Denis Sassou Nguesso", country:"Republic of the Congo", dates:"1979–1992, 1997–present", x:-2, y:-7, blurb:"Long-ruling, oil-fueled patronage.", aliases:["sassou nguesso","denis sassou nguesso"]},
  {name:"Joseph Kabila", country:"DR Congo", dates:"2001–2019", x:-2, y:-6, blurb:"Overstayed term limits before stepping down.", aliases:["kabila","joseph kabila"]},
  {name:"Félix Tshisekedi", country:"DR Congo", dates:"2019–present", x:-1, y:-4, blurb:"Contested elections, gradual consolidation.", aliases:["tshisekedi","felix tshisekedi"]},
  {name:"Emmerson Mnangagwa", country:"Zimbabwe", dates:"2017–present", x:-4, y:-6, blurb:"Continued ZANU-PF authoritarian rule after Mugabe.", aliases:["mnangagwa","emmerson mnangagwa"]},
  {name:"Abiy Ahmed", country:"Ethiopia", dates:"2018–present", x:-2, y:-5, blurb:"Reformist start, later civil conflict/centralization.", aliases:["abiy ahmed","abiy"]},
  {name:"Ismail Omar Guelleh", country:"Djibouti", dates:"1999–present", x:-1, y:-6, blurb:"Long-ruling, limited political pluralism.", aliases:["guelleh","ismail omar guelleh"]},
  {name:"Idriss Déby", country:"Chad", dates:"1990–2021", x:-1, y:-7, blurb:"Long military-backed authoritarian rule.", aliases:["deby","idriss deby"]},

  // --- Latin America ---
  {name:"Hugo Chávez", country:"Venezuela", dates:"1999–2013", x:-8, y:-6, blurb:"Socialist \"Bolivarian Revolution,\" centralized power.", aliases:["chavez","hugo chavez"]},
  {name:"Evo Morales", country:"Bolivia", dates:"2006–2019", x:-7, y:-3, blurb:"Indigenous-socialist, nationalized industries.", aliases:["evo morales","evo"]},
  {name:"Luis Arce", country:"Bolivia", dates:"2020–present", x:-6, y:1, blurb:"Socialist economics, democratic governance.", aliases:["luis arce"]},
  {name:"Rafael Correa", country:"Ecuador", dates:"2007–2017", x:-6, y:-2, blurb:"Left-populist, press-freedom concerns.", aliases:["correa","rafael correa"], flags:["corruption"]},
  {name:"Gabriel Boric", country:"Chile", dates:"2022–present", x:-6, y:5, blurb:"Millennial left, strong democratic/civil-liberties focus.", aliases:["boric","gabriel boric"]},
  {name:"Sebastián Piñera", country:"Chile", dates:"2010–2014, 2018–2022", x:5, y:3, blurb:"Center-right businessman, democratic governance.", aliases:["pinera","sebastian pinera"]},
  {name:"Michelle Bachelet", country:"Chile", dates:"2006–2010, 2014–2018", x:-4, y:4, blurb:"Center-left, strong civil-liberties record.", aliases:["bachelet","michelle bachelet"]},
  {name:"Cristina Fernández de Kirchner", country:"Argentina", dates:"2007–2015", x:-5, y:-1, blurb:"Left-populist Peronism.", aliases:["cristina kirchner","cristina fernandez"], flags:["corruption"]},
  {name:"Néstor Kirchner", country:"Argentina", dates:"2003–2007", x:-5, y:0, blurb:"Left-leaning Peronism.", aliases:["nestor kirchner"]},
  {name:"Mauricio Macri", country:"Argentina", dates:"2015–2019", x:5, y:2, blurb:"Center-right market reforms.", aliases:["macri","mauricio macri"]},
  {name:"Andrés Manuel López Obrador", country:"Mexico", dates:"2018–2024", x:-4, y:-1, blurb:"Left-populist, some institutional-norm friction.", aliases:["amlo","lopez obrador","andres manuel lopez obrador"]},
  {name:"Claudia Sheinbaum", country:"Mexico", dates:"2024–present", x:-4, y:1, blurb:"Left-leaning, continuity with AMLO's agenda.", aliases:["sheinbaum","claudia sheinbaum"]},
  {name:"Felipe Calderón", country:"Mexico", dates:"2006–2012", x:3, y:1, blurb:"Center-right, drug-war security expansion.", aliases:["calderon","felipe calderon"]},
  {name:"Vicente Fox", country:"Mexico", dates:"2000–2006", x:3, y:2, blurb:"Ended 71 years of one-party rule.", aliases:["vicente fox"]},
  {name:"Juan Manuel Santos", country:"Colombia", dates:"2010–2018", x:1, y:2, blurb:"Peace-process focused centrist.", aliases:["santos","juan manuel santos"]},
  {name:"Gustavo Petro", country:"Colombia", dates:"2022–present", x:-6, y:2, blurb:"First leftist president, democratic governance.", aliases:["petro","gustavo petro"]},
  {name:"Álvaro Uribe", country:"Colombia", dates:"2002–2010", x:5, y:-3, blurb:"Hardline security policies, some institutional friction.", aliases:["uribe","alvaro uribe"]},
  {name:"Dilma Rousseff", country:"Brazil", dates:"2011–2016", x:-4, y:3, blurb:"Left-leaning Workers' Party, impeached.", aliases:["dilma","dilma rousseff"]},
  {name:"Fernando Henrique Cardoso", country:"Brazil", dates:"1995–2003", x:1, y:3, blurb:"Centrist market reforms, price stabilization.", aliases:["fhc","fernando henrique cardoso"]},
  {name:"Daniel Noboa", country:"Ecuador", dates:"2023–present", x:3, y:-1, blurb:"Center-right, security crackdowns amid gang violence.", aliases:["noboa","daniel noboa"]},

  // --- Continental Europe & Oceania ---
  {name:"Silvio Berlusconi", country:"Italy", dates:"1994–1995, 2001–2006, 2008–2011", x:4, y:0, blurb:"Media-mogul populist, conflict-of-interest controversies.", aliases:["berlusconi","silvio berlusconi"], flags:["corruption"]},
  {name:"Matteo Renzi", country:"Italy", dates:"2014–2016", x:0, y:2, blurb:"Centrist reformer.", aliases:["renzi","matteo renzi"]},
  {name:"Viktor Orbán", country:"Hungary", dates:"1998–2002, 2010–present", x:3, y:-6, blurb:"\"Illiberal democracy,\" nationalist-conservative.", aliases:["orban","viktor orban"]},
  {name:"Andrzej Duda", country:"Poland", dates:"2015–present", x:3, y:-3, blurb:"National-conservative, judiciary controversies.", aliases:["duda","andrzej duda"]},
  {name:"Donald Tusk", country:"Poland", dates:"2007–2014, 2023–present", x:1, y:3, blurb:"Centrist, pro-EU.", aliases:["tusk","donald tusk"]},
  {name:"Jarosław Kaczyński", country:"Poland", dates:"PiS party leader", x:3, y:-5, blurb:"National-conservative, judicial-independence disputes.", aliases:["kaczynski","jaroslaw kaczynski"]},
  {name:"José Luis Rodríguez Zapatero", country:"Spain", dates:"2004–2011", x:-4, y:3, blurb:"Center-left social reforms.", aliases:["zapatero","jose luis rodriguez zapatero"]},
  {name:"Mariano Rajoy", country:"Spain", dates:"2011–2018", x:3, y:2, blurb:"Center-right austerity economics.", aliases:["rajoy","mariano rajoy"]},
  {name:"Alexis Tsipras", country:"Greece", dates:"2015–2019", x:-6, y:2, blurb:"Left-wing Syriza, anti-austerity.", aliases:["tsipras","alexis tsipras"]},
  {name:"Kyriakos Mitsotakis", country:"Greece", dates:"2019–present", x:4, y:1, blurb:"Center-right market reforms.", aliases:["mitsotakis","kyriakos mitsotakis"]},
  {name:"Geert Wilders", country:"Netherlands", dates:"PVV party leader", x:3, y:-4, blurb:"Right-populist nationalist.", aliases:["wilders","geert wilders"]},
  {name:"Mark Rutte", country:"Netherlands", dates:"2010–2024", x:3, y:2, blurb:"Center-right liberal, standard democratic norms.", aliases:["rutte","mark rutte"]},
  {name:"Olof Palme", country:"Sweden", dates:"1969–1976, 1982–1986", x:-6, y:4, blurb:"Social democrat, strong welfare state.", aliases:["olof palme"]},
  {name:"Magdalena Andersson", country:"Sweden", dates:"2021–2022", x:-4, y:3, blurb:"Social democrat.", aliases:["magdalena andersson"]},
  {name:"Jens Stoltenberg", country:"Norway", dates:"2000–2001, 2005–2013", x:-3, y:4, blurb:"Social democrat.", aliases:["stoltenberg","jens stoltenberg"]},
  {name:"Mette Frederiksen", country:"Denmark", dates:"2019–present", x:-3, y:3, blurb:"Social democrat with restrictive immigration stance.", aliases:["frederiksen","mette frederiksen"]},
  {name:"Sanna Marin", country:"Finland", dates:"2019–2023", x:-4, y:4, blurb:"Social democrat, youngest PM at the time.", aliases:["sanna marin"]},
  {name:"Leo Varadkar", country:"Ireland", dates:"2017–2020, 2022–2024", x:2, y:3, blurb:"Center-right liberal-conservative.", aliases:["varadkar","leo varadkar"]},
  {name:"Petro Poroshenko", country:"Ukraine", dates:"2014–2019", x:2, y:1, blurb:"Business-oligarch turned reform-minded president.", aliases:["poroshenko","petro poroshenko"]},
  {name:"John Howard", country:"Australia", dates:"1996–2007", x:5, y:1, blurb:"Center-right, market liberalization.", aliases:["john howard"]},
  {name:"Julia Gillard", country:"Australia", dates:"2010–2013", x:-3, y:3, blurb:"Center-left Labor.", aliases:["julia gillard"]},
  {name:"Jacinda Ardern", country:"New Zealand", dates:"2017–2023", x:-4, y:5, blurb:"Center-left, strong civil-liberties record.", aliases:["ardern","jacinda ardern","jacinda"]},
  {name:"Christopher Luxon", country:"New Zealand", dates:"2023–present", x:4, y:2, blurb:"Center-right, business background.", aliases:["luxon","christopher luxon"]},
  {name:"Robert Menzies", country:"Australia", dates:"1949–1966", x:4, y:1, blurb:"Longest-serving PM, center-right.", aliases:["robert menzies","menzies"]},
  {name:"Helen Clark", country:"New Zealand", dates:"1999–2008", x:-4, y:4, blurb:"Center-left Labour.", aliases:["helen clark"]},
// --- UK MPs ---
  {name:"Ed Miliband", country:"United Kingdom", dates:"Energy Secretary, 2024–present", x:-6, y:4, blurb:"Left-leaning Labour, climate policy focus.", aliases:["ed miliband","miliband"]},
  {name:"Rachel Reeves", country:"United Kingdom", dates:"Chancellor of the Exchequer, 2024–present", x:-2, y:3, blurb:"Fiscally cautious Labour centrist.", aliases:["rachel reeves","reeves"]},
  {name:"David Lammy", country:"United Kingdom", dates:"Foreign Secretary, 2024–present", x:-3, y:3, blurb:"Center-left Labour, internationalist.", aliases:["david lammy","lammy"]},
  {name:"Yvette Cooper", country:"United Kingdom", dates:"Home Secretary, 2024–present", x:-2, y:2, blurb:"Center-left Labour.", aliases:["yvette cooper","cooper"]},
  {name:"Wes Streeting", country:"United Kingdom", dates:"Health Secretary, 2024–present", x:0, y:3, blurb:"More centrist wing of Labour.", aliases:["wes streeting","streeting"]},
  {name:"Angela Rayner", country:"United Kingdom", dates:"Deputy PM, 2024–present", x:-5, y:3, blurb:"Left-wing Labour, trade-union background.", aliases:["angela rayner","rayner"]},
  {name:"Kemi Badenoch", country:"United Kingdom", dates:"Conservative Party leader, 2024–present", x:6, y:0, blurb:"Right-wing Conservative, culture-war focus.", aliases:["kemi badenoch","badenoch"]},
  {name:"Priti Patel", country:"United Kingdom", dates:"Former Home Secretary", x:6, y:-2, blurb:"Right-wing Conservative, hardline immigration stance.", aliases:["priti patel","patel"]},
  {name:"Suella Braverman", country:"United Kingdom", dates:"Former Home Secretary", x:7, y:-3, blurb:"Hard-right Conservative, restrictive immigration stance.", aliases:["suella braverman","braverman"]},
  {name:"Jacob Rees-Mogg", country:"United Kingdom", dates:"Former Cabinet minister", x:8, y:1, blurb:"Traditionalist free-market Conservative.", aliases:["jacob rees-mogg","rees-mogg","rees mogg"]},
  {name:"Michael Gove", country:"United Kingdom", dates:"Former Cabinet minister", x:5, y:1, blurb:"Center-right Conservative reformer.", aliases:["michael gove","gove"]},
  {name:"Dominic Raab", country:"United Kingdom", dates:"Former Deputy PM", x:6, y:0, blurb:"Right-leaning Conservative.", aliases:["dominic raab","raab"]},
  {name:"Ed Davey", country:"United Kingdom", dates:"Liberal Democrat leader, 2020–present", x:-3, y:5, blurb:"Centrist liberal, strong civil-liberties record.", aliases:["ed davey","davey"]},
  {name:"Vince Cable", country:"United Kingdom", dates:"Former Lib Dem leader", x:-2, y:4, blurb:"Centrist liberal economist.", aliases:["vince cable","cable"]},
  {name:"Caroline Lucas", country:"United Kingdom", dates:"Former Green MP", x:-7, y:6, blurb:"Green Party, strong civil-liberties and environmental focus.", aliases:["caroline lucas"]},
  {name:"Zack Polanski", country:"United Kingdom", dates:"Green Party leader, 2025–present", x:-7, y:5, blurb:"Left-wing eco-populist.", aliases:["zack polanski","polanski"]},
  {name:"Nicola Sturgeon", country:"United Kingdom", dates:"Scottish First Minister, 2014–2023", x:-4, y:3, blurb:"Center-left SNP, Scottish independence focus.", aliases:["nicola sturgeon","sturgeon"]},
  {name:"John Swinney", country:"United Kingdom", dates:"Scottish First Minister, 2024–present", x:-4, y:3, blurb:"Center-left SNP.", aliases:["john swinney","swinney"]},
  {name:"Humza Yousaf", country:"United Kingdom", dates:"Scottish First Minister, 2023–2024", x:-4, y:3, blurb:"Center-left SNP.", aliases:["humza yousaf","yousaf"]},
  {name:"Diane Abbott", country:"United Kingdom", dates:"Labour MP since 1987", x:-8, y:5, blurb:"Veteran hard-left Labour backbencher.", aliases:["diane abbott","abbott"]},
  {name:"Zarah Sultana", country:"United Kingdom", dates:"Independent MP (ex-Labour)", x:-8, y:4, blurb:"Hard-left, left Labour over whip suspension.", aliases:["zarah sultana","sultana"]},
  {name:"George Galloway", country:"United Kingdom", dates:"Workers Party leader", x:-5, y:-2, blurb:"Left-populist, some illiberal rhetoric controversies.", aliases:["george galloway","galloway"]},
  {name:"Lee Anderson", country:"United Kingdom", dates:"Reform UK MP", x:7, y:-4, blurb:"Right-populist, defected from Conservatives to Reform.", aliases:["lee anderson"]},
  {name:"Richard Tice", country:"United Kingdom", dates:"Reform UK deputy leader", x:7, y:-2, blurb:"Right-populist, business background.", aliases:["richard tice","tice"]},
  {name:"Harriet Harman", country:"United Kingdom", dates:"Former Labour deputy leader", x:-4, y:4, blurb:"Veteran center-left Labour.", aliases:["harriet harman","harman"]},
  {name:"Kenneth Clarke", country:"United Kingdom", dates:"Former Chancellor, retired", x:3, y:3, blurb:"One-nation centrist Conservative.", aliases:["ken clarke","kenneth clarke"]},
  {name:"William Hague", country:"United Kingdom", dates:"Former Conservative leader", x:5, y:2, blurb:"Center-right Conservative.", aliases:["william hague","hague"]},
  {name:"Iain Duncan Smith", country:"United Kingdom", dates:"Former Conservative leader", x:5, y:-1, blurb:"Right-wing Conservative, welfare-reform focus.", aliases:["iain duncan smith","ids"]},

  // --- US Senators ---
  {name:"Chuck Schumer", country:"United States", dates:"Senator (NY), 1999–present", x:-3, y:3, blurb:"Senate Democratic leader, center-left.", aliases:["chuck schumer","schumer"]},
  {name:"Mitch McConnell", country:"United States", dates:"Senator (KY), 1985–present", x:4, y:1, blurb:"Longtime Senate Republican leader.", aliases:["mitch mcconnell","mcconnell"]},
  {name:"John Thune", country:"United States", dates:"Senator (SD), Majority Leader", x:4, y:1, blurb:"Establishment Republican.", aliases:["john thune","thune"]},
  {name:"Elizabeth Warren", country:"United States", dates:"Senator (MA), 2013–present", x:-7, y:5, blurb:"Progressive Democrat, financial-regulation focus.", aliases:["elizabeth warren","warren"]},
  {name:"Ted Cruz", country:"United States", dates:"Senator (TX), 2013–present", x:7, y:-1, blurb:"Hard-right conservative Republican.", aliases:["ted cruz","cruz"]},
  {name:"Josh Hawley", country:"United States", dates:"Senator (MO), 2019–present", x:5, y:-3, blurb:"Right-wing populist Republican.", aliases:["josh hawley","hawley"]},
  {name:"Rand Paul", country:"United States", dates:"Senator (KY), 2011–present", x:6, y:6, blurb:"Libertarian-leaning Republican.", aliases:["rand paul"]},
  {name:"Marco Rubio", country:"United States", dates:"Former Senator (FL); Secretary of State, 2025–present", x:5, y:0, blurb:"Establishment conservative Republican.", aliases:["marco rubio","rubio"]},
  {name:"Lindsey Graham", country:"United States", dates:"Senator (SC), 2003–present", x:4, y:-1, blurb:"Hawkish establishment Republican.", aliases:["lindsey graham","graham"]},
  {name:"Susan Collins", country:"United States", dates:"Senator (ME), 1997–present", x:2, y:4, blurb:"Moderate Republican, frequent swing vote.", aliases:["susan collins","collins"]},
  {name:"Lisa Murkowski", country:"United States", dates:"Senator (AK), 2002–present", x:1, y:4, blurb:"Moderate Republican, frequent swing vote.", aliases:["lisa murkowski","murkowski"]},
  {name:"Joe Manchin", country:"United States", dates:"Former Senator (WV), Independent", x:1, y:2, blurb:"Conservative Democrat turned independent, swing vote.", aliases:["joe manchin","manchin"]},
  {name:"Kyrsten Sinema", country:"United States", dates:"Former Senator (AZ), Independent", x:1, y:2, blurb:"Centrist, left Democratic Party to become independent.", aliases:["kyrsten sinema","sinema"]},
  {name:"Amy Klobuchar", country:"United States", dates:"Senator (MN), 2007–present", x:-3, y:4, blurb:"Center-left Democrat.", aliases:["amy klobuchar","klobuchar"]},
  {name:"Cory Booker", country:"United States", dates:"Senator (NJ), 2013–present", x:-4, y:5, blurb:"Center-left Democrat.", aliases:["cory booker","booker"]},
  {name:"Kamala Harris", country:"United States", dates:"Former Senator (CA); VP 2021–2025", x:-3, y:3, blurb:"Center-left Democrat.", aliases:["kamala harris","harris"]},
  {name:"J.D. Vance", country:"United States", dates:"Former Senator (OH); VP 2025–present", x:5, y:-3, blurb:"Right-populist Republican.", aliases:["jd vance","j.d. vance","vance"]},
  {name:"Tom Cotton", country:"United States", dates:"Senator (AR), 2015–present", x:6, y:-3, blurb:"Hard-right conservative Republican.", aliases:["tom cotton","cotton"]},
  {name:"John Fetterman", country:"United States", dates:"Senator (PA), 2023–present", x:-3, y:3, blurb:"Populist-leaning Democrat.", aliases:["john fetterman","fetterman"]},
  {name:"Raphael Warnock", country:"United States", dates:"Senator (GA), 2021–present", x:-4, y:4, blurb:"Center-left Democrat.", aliases:["raphael warnock","warnock"]},
  {name:"Tim Scott", country:"United States", dates:"Senator (SC), 2013–present", x:4, y:2, blurb:"Establishment conservative Republican.", aliases:["tim scott"]},
  {name:"Mike Lee", country:"United States", dates:"Senator (UT), 2011–present", x:6, y:5, blurb:"Libertarian-leaning Republican.", aliases:["mike lee"]},
  {name:"Chuck Grassley", country:"United States", dates:"Senator (IA), 1981–present", x:4, y:1, blurb:"Veteran establishment Republican.", aliases:["chuck grassley","grassley"]},
// --- Mayors (UK) ---
  {name:"Sadiq Khan", country:"United Kingdom", dates:"Mayor of London, 2016–present", x:-4, y:3, blurb:"Center-left Labour, London Mayor.", aliases:["sadiq khan","khan"]},
  {name:"Andy Street", country:"United Kingdom", dates:"West Midlands Mayor, 2017–2024", x:4, y:2, blurb:"Center-right Conservative, business background.", aliases:["andy street","street"]},
  {name:"Tracy Brabin", country:"United Kingdom", dates:"West Yorkshire Mayor, 2021–present", x:-4, y:3, blurb:"Center-left Labour.", aliases:["tracy brabin","brabin"]},
  {name:"Ben Houchen", country:"United Kingdom", dates:"Tees Valley Mayor, 2017–present", x:3, y:2, blurb:"Center-right Conservative, regional-investment focus.", aliases:["ben houchen","houchen"]},

  // --- Mayors (US) ---
  {name:"Eric Adams", country:"United States", dates:"Mayor of New York City, 2022–present", x:-1, y:0, blurb:"Moderate Democrat, controversial corruption allegations.", aliases:["eric adams"]},
  {name:"Karen Bass", country:"United States", dates:"Mayor of Los Angeles, 2022–present", x:-4, y:3, blurb:"Center-left Democrat.", aliases:["karen bass","bass"]},
  {name:"Brandon Johnson", country:"United States", dates:"Mayor of Chicago, 2023–present", x:-6, y:3, blurb:"Progressive Democrat, teachers'-union background.", aliases:["brandon johnson"]},
  {name:"Michelle Wu", country:"United States", dates:"Mayor of Boston, 2021–present", x:-5, y:4, blurb:"Progressive Democrat.", aliases:["michelle wu","wu"]},
  {name:"Muriel Bowser", country:"United States", dates:"Mayor of Washington DC, 2015–present", x:-3, y:3, blurb:"Center-left Democrat.", aliases:["muriel bowser","bowser"]},
  {name:"Daniel Lurie", country:"United States", dates:"Mayor of San Francisco, 2025–present", x:-2, y:2, blurb:"Moderate Democrat, nonprofit background.", aliases:["daniel lurie","lurie"]},
  {name:"London Breed", country:"United States", dates:"Former Mayor of San Francisco, 2018–2025", x:-2, y:2, blurb:"Moderate Democrat.", aliases:["london breed","breed"]},
  {name:"Bill de Blasio", country:"United States", dates:"Former Mayor of New York City, 2014–2022", x:-5, y:3, blurb:"Progressive Democrat.", aliases:["bill de blasio","de blasio"]},
  {name:"Rudy Giuliani", country:"United States", dates:"Former Mayor of New York City, 1994–2001", x:4, y:-1, blurb:"Law-and-order Republican.", aliases:["rudy giuliani","giuliani"]},
  {name:"Michael Bloomberg", country:"United States", dates:"Former Mayor of New York City, 2002–2013", x:1, y:3, blurb:"Independent/moderate, business background.", aliases:["michael bloomberg","bloomberg"]},
  {name:"Lori Lightfoot", country:"United States", dates:"Former Mayor of Chicago, 2019–2023", x:-4, y:2, blurb:"Center-left Democrat.", aliases:["lori lightfoot","lightfoot"]},
// --- More global leaders ---
  {name:"Edi Rama", country:"Albania", dates:"Prime Minister, 2013–present", x:-2, y:2, blurb:"Center-left Socialist Party, EU-accession focused.", aliases:["edi rama","rama"]},
  {name:"Aleksandar Vučić", country:"Serbia", dates:"President, 2017–present", x:2, y:-3, blurb:"Nationalist-populist, increasing media/press-freedom concerns.", aliases:["vucic","aleksandar vucic","aleksandar vučić"]},
  {name:"Zoran Milanović", country:"Croatia", dates:"President, 2020–present", x:-2, y:3, blurb:"Center-left, frequent friction with government.", aliases:["milanovic","zoran milanovic"]},
  {name:"Robert Fico", country:"Slovakia", dates:"Prime Minister, 2023–present", x:-2, y:-3, blurb:"Left-populist, pro-Russia leaning foreign policy.", aliases:["robert fico","fico"]},
  {name:"Petr Fiala", country:"Czech Republic", dates:"Prime Minister, 2021–2025", x:4, y:2, blurb:"Center-right, pro-EU/NATO.", aliases:["petr fiala","fiala"]},
  {name:"Alexander Stubb", country:"Finland", dates:"President, 2024–present", x:3, y:3, blurb:"Center-right liberal.", aliases:["alexander stubb","stubb"]},
  {name:"Frank-Walter Steinmeier", country:"Germany", dates:"President, 2017–present", x:-2, y:4, blurb:"Center-left SPD, largely ceremonial head of state.", aliases:["steinmeier","frank-walter steinmeier"]},
  {name:"Anwar Ibrahim", country:"Malaysia", dates:"Prime Minister, 2022–present", x:-1, y:2, blurb:"Reformist, long-time opposition figure now in power.", aliases:["anwar ibrahim","anwar"]},
  {name:"Yoon Suk-yeol", country:"South Korea", dates:"President, 2022–2025 (impeached)", x:5, y:-3, blurb:"Conservative, impeached after martial-law declaration attempt.", aliases:["yoon suk-yeol","yoon"]},
  {name:"Lee Jae-myung", country:"South Korea", dates:"President, 2025–present", x:-3, y:2, blurb:"Center-left, populist economic policies.", aliases:["lee jae-myung","lee jae myung"]},
  {name:"Kais Saied", country:"Tunisia", dates:"President, 2019–present", x:-1, y:-6, blurb:"Consolidated executive power after 2021 self-coup.", aliases:["kais saied","saied"]},
  {name:"Abdelmadjid Tebboune", country:"Algeria", dates:"President, 2019–present", x:-2, y:-5, blurb:"Military-backed, limited political pluralism.", aliases:["tebboune","abdelmadjid tebboune"]},
  {name:"Mohammed VI", country:"Morocco", dates:"King, 1999–present", x:3, y:-4, blurb:"Constitutional monarch with substantial personal power.", aliases:["mohammed vi","king mohammed vi"]},
  {name:"Nicolas Sarkozy", country:"France", dates:"President, 2007–2012", x:5, y:0, blurb:"Center-right; later convicted of corruption offenses.", aliases:["nicolas sarkozy","sarkozy"], flags:["corruption"]},
  {name:"Park Geun-hye", country:"South Korea", dates:"President, 2013–2017 (impeached)", x:4, y:-2, blurb:"Conservative; impeached and convicted of corruption.", aliases:["park geun-hye","park geun hye"], flags:["corruption"]},
  {name:"Alberto Fujimori", country:"Peru", dates:"President, 1990–2000", x:5, y:-6, blurb:"Authoritarian; later convicted of corruption and human rights crimes.", aliases:["alberto fujimori","fujimori"], flags:["warcrimes","corruption"]}
];
