// Each entry: name, country, dates, x (-10 left … 10 right), y (-10 authoritarian … 10 libertarian),
// blurb (short justification), aliases (lowercase strings people might type)
const POLITICIANS = [
  // --- authoritarian historical/modern rulers ---
  {name:"Omar al-Bashir", country:"Sudan", dates:"1989–2019", x:3, y:-6.5, blurb:"Islamist military ruler, ousted after mass protests.", aliases:["bashir","omar al-bashir","omar bashir"], flags:["warcrimes"]},
  {name:"Kim Jong-il", country:"North Korea", dates:"1994–2011", x:-9, y:-9.5, blurb:"Totalitarian command economy, absolute personality cult.", aliases:["kim jong il","kim jong-il"]},
  {name:"Kim Jong-un", country:"North Korea", dates:"2011–present", x:-9, y:-9.5, blurb:"Continues totalitarian one-party rule and command economy.", aliases:["kim jong un","kim jong-un","kim"]},
  {name:"Than Shwe", country:"Myanmar/Burma", dates:"1992–2011", x:4, y:-7.5, blurb:"Military junta leader, nationalist economic control.", aliases:["than shwe"]},
  {name:"Robert Mugabe", country:"Zimbabwe", dates:"1980–2017", x:-6, y:-5.8, blurb:"Land redistribution and socialist rhetoric, long one-party rule.", aliases:["mugabe","robert mugabe"]},
  {name:"Islam Karimov", country:"Uzbekistan", dates:"1989–2016", x:-3, y:-7.7, blurb:"Post-Soviet strongman, state-controlled economy.", aliases:["karimov","islam karimov"]},
  {name:"Hu Jintao", country:"China", dates:"2002–2012", x:-5, y:-5.5, blurb:"Socialist market economy under one-party rule.", aliases:["hu jintao"]},
  {name:"Xi Jinping", country:"China", dates:"2012–present", x:-5, y:-7, blurb:"Tightened one-party control, state-directed economy.", aliases:["xi jinping","xi"]},
  {name:"King Abdullah", country:"Saudi Arabia", dates:"2005–2015", x:7, y:-5, blurb:"Absolute monarchy, market economy for elites.", aliases:["king abdullah","abdullah saudi"]},
  {name:"Mohammed bin Salman", country:"Saudi Arabia", dates:"2017–present (Crown Prince/PM)", x:6, y:-5.5, blurb:"Economic liberalization drive alongside tight political control.", aliases:["mbs","mohammed bin salman","bin salman"]},
  {name:"Saparmurat Niyazov", country:"Turkmenistan", dates:"1985–2006", x:-7, y:-9, blurb:"Extreme personality cult, state-controlled economy.", aliases:["niyazov"]},
  {name:"Ali Khamenei", country:"Iran", dates:"1989–present", x:5, y:-6.5, blurb:"Theocratic conservative Supreme Leader.", aliases:["khamenei","ali khamenei"]},
  {name:"Teodoro Obiang Nguema", country:"Equatorial Guinea", dates:"1979–present", x:2, y:-7.5, blurb:"Longest-ruling head of state, oil-fueled kleptocracy.", aliases:["obiang","teodoro obiang"]},
  {name:"Muammar al-Qaddafi", country:"Libya", dates:"1969–2011", x:-7, y:-7, blurb:"\"Islamic socialism,\" anti-capitalist Jamahiriya system.", aliases:["gaddafi","qaddafi","muammar gaddafi"], flags:["warcrimes"]},
  {name:"King Mswati III", country:"Eswatini/Swaziland", dates:"1986–present", x:6, y:-5.5, blurb:"Absolute monarch, one of the world's last.", aliases:["mswati","king mswati"]},
  {name:"Pervez Musharraf", country:"Pakistan", dates:"1999–2008", x:3, y:-3.5, blurb:"Military ruler with market-friendly reforms.", aliases:["musharraf"]},
  {name:"Aleksandr Lukashenko", country:"Belarus", dates:"1994–present", x:-6.3, y:-6.2, blurb:"Soviet-nostalgic state-controlled economy.", aliases:["lukashenko"]},
  {name:"Fidel Castro", country:"Cuba", dates:"1959–2008", x:-9.5, y:-8, blurb:"Communist one-party state.", aliases:["castro","fidel castro"]},
  {name:"Isaias Afwerki", country:"Eritrea", dates:"1993–present", x:-6, y:-8.3, blurb:"One-party state, no elections ever held.", aliases:["afwerki","isaias"]},
  {name:"Bashar al-Assad", country:"Syria", dates:"2000–2024", x:-4, y:-7.3, blurb:"Ba'athist secular Arab socialism, ousted Dec 2024.", aliases:["assad","bashar al-assad","bashar assad"], flags:["warcrimes"]},
  {name:"Meles Zenawi", country:"Ethiopia", dates:"1991–2012", x:-5, y:-5, blurb:"Developmental state, \"revolutionary democracy.\"", aliases:["meles zenawi","meles"]},
  {name:"Paul Biya", country:"Cameroon", dates:"1982–present", x:-1, y:-5, blurb:"Personalist rule, nominally socialist party heritage.", aliases:["biya","paul biya"]},
  {name:"Vladimir Putin", country:"Russia", dates:"1999–present", x:1, y:-8, blurb:"State-capitalist economy under centralized authoritarian rule.", aliases:["putin","vladimir putin"], flags:["warcrimes"]},
  {name:"Nicolás Maduro", country:"Venezuela", dates:"2013–present", x:-8, y:-8, blurb:"Socialist command economy, contested elections.", aliases:["maduro","nicolas maduro"]},
  {name:"Daniel Ortega", country:"Nicaragua", dates:"2007–present", x:-7, y:-8, blurb:"Sandinista socialist rule, crackdowns on opposition.", aliases:["ortega","daniel ortega"]},
  {name:"Recep Tayyip Erdoğan", country:"Turkey", dates:"2003–present", x:2, y:-5.5, blurb:"Conservative-nationalist, growing executive power.", aliases:["erdogan","recep tayyip erdogan"]},

  // --- 20th century dictators/leaders ---
  {name:"Adolf Hitler", country:"Germany", dates:"1933–1945", x:1, y:-10, blurb:"Fascist totalitarian dictatorship.", aliases:["hitler","adolf hitler"], flags:["warcrimes"]},
  {name:"Joseph Stalin", country:"Soviet Union", dates:"1924–1953", x:-9.5, y:-9.5, blurb:"Totalitarian command economy, mass purges.", aliases:["stalin"], flags:["warcrimes"]},
  {name:"Mao Zedong", country:"China", dates:"1949–1976", x:-9.5, y:-9, blurb:"Communist revolution, Cultural Revolution repression.", aliases:["mao","mao zedong"]},
  {name:"Benito Mussolini", country:"Italy", dates:"1922–1943", x:2, y:-9, blurb:"Fascist corporatist state.", aliases:["mussolini"], flags:["warcrimes"]},
  {name:"Francisco Franco", country:"Spain", dates:"1939–1975", x:4, y:-8.5, blurb:"Right-wing nationalist military dictatorship.", aliases:["franco","francisco franco"]},
  {name:"Augusto Pinochet", country:"Chile", dates:"1973–1990", x:6, y:-8, blurb:"Free-market reforms under brutal military rule.", aliases:["pinochet"]},
  {name:"Pol Pot", country:"Cambodia", dates:"1975–1979", x:-9, y:-10, blurb:"Agrarian communist genocide.", aliases:["pol pot"]},
  {name:"Idi Amin", country:"Uganda", dates:"1971–1979", x:-1, y:-9, blurb:"Erratic military dictatorship.", aliases:["idi amin"]},
  {name:"Saddam Hussein", country:"Iraq", dates:"1979–2003", x:-2, y:-9, blurb:"Ba'athist secular nationalist dictatorship.", aliases:["saddam","saddam hussein"], flags:["warcrimes"]},
  {name:"Slobodan Milošević", country:"Serbia/Yugoslavia", dates:"1989–2000", x:-3, y:-7.5, blurb:"Nationalist authoritarian, ethnic conflict.", aliases:["milosevic"], flags:["warcrimes"]},
  {name:"Josip Broz Tito", country:"Yugoslavia", dates:"1953–1980", x:-6, y:-4.5, blurb:"Non-aligned market socialism, relatively liberalized communism.", aliases:["tito"]},
  {name:"Nicolae Ceaușescu", country:"Romania", dates:"1965–1989", x:-8, y:-9, blurb:"Hardline Stalinist personality cult.", aliases:["ceausescu"]},
  {name:"Kim Il-sung", country:"North Korea", dates:"1948–1994", x:-9, y:-9.5, blurb:"Founder of totalitarian juche state.", aliases:["kim il sung","kim il-sung"]},
  {name:"Ho Chi Minh", country:"Vietnam", dates:"1945–1969", x:-8, y:-7, blurb:"Communist revolutionary and nation-founder.", aliases:["ho chi minh"]},
  {name:"Deng Xiaoping", country:"China", dates:"1978–1989", x:-3, y:-6.5, blurb:"Market reforms within one-party rule (\"socialism with Chinese characteristics\").", aliases:["deng xiaoping","deng"]},
  {name:"Mikhail Gorbachev", country:"Soviet Union", dates:"1985–1991", x:-6, y:-1, blurb:"Glasnost/perestroika reforms loosened authoritarian control.", aliases:["gorbachev"]},

  // --- widely admired reformers / democratic icons ---
  {name:"Nelson Mandela", country:"South Africa", dates:"1994–1999", x:-4, y:7, blurb:"Anti-apartheid leader, reconciliation-focused democracy.", aliases:["mandela","nelson mandela"]},
  {name:"Mahatma Gandhi", country:"India", dates:"Independence leader", x:-2, y:8, blurb:"Nonviolent independence movement, civil liberties focus.", aliases:["gandhi","mahatma gandhi"]},

  // --- US ---
  {name:"Donald Trump", country:"United States", dates:"2017–2021, 2025–present", x:4, y:-3, blurb:"Right-populist economics, disputed executive-power norms.", aliases:["trump","donald trump","donald j trump"]},
  {name:"Joe Biden", country:"United States", dates:"2021–2025", x:-2, y:4, blurb:"Center-left economics, standard democratic norms.", aliases:["biden","joe biden"]},
  {name:"Barack Obama", country:"United States", dates:"2009–2017", x:-2, y:5, blurb:"Center-left, expanded healthcare access.", aliases:["obama","barack obama"]},
  {name:"George W. Bush", country:"United States", dates:"2001–2009", x:5, y:1, blurb:"Tax cuts, expanded post-9/11 executive/security powers.", aliases:["bush","george w bush","gw bush"]},
  {name:"Bill Clinton", country:"United States", dates:"1993–2001", x:1, y:4, blurb:"Centrist \"Third Way\" economics.", aliases:["clinton","bill clinton"]},
  {name:"Ronald Reagan", country:"United States", dates:"1981–1989", x:7, y:2, blurb:"Free-market deregulation, tax cuts.", aliases:["reagan","ronald reagan"]},
  {name:"Franklin D. Roosevelt", country:"United States", dates:"1933–1945", x:-6, y:2, blurb:"New Deal state intervention in the economy.", aliases:["fdr","franklin roosevelt","franklin d roosevelt"]},
  {name:"Bernie Sanders", country:"United States", dates:"Senator, not head of state", x:-8, y:7, blurb:"Democratic socialist, strong civil-liberties record.", aliases:["bernie","bernie sanders","sanders"]},

  // --- UK ---
  {name:"Keir Starmer", country:"United Kingdom", dates:"2024–present", x:-2, y:4, blurb:"Center-left Labour, standard democratic governance.", aliases:["starmer","keir starmer"]},
  {name:"Rishi Sunak", country:"United Kingdom", dates:"2022–2024", x:5, y:3, blurb:"Fiscally conservative Conservative PM.", aliases:["sunak","rishi sunak"]},
  {name:"Liz Truss", country:"United Kingdom", dates:"2022 (49 days)", x:7, y:3, blurb:"Aggressive free-market tax-cutting agenda.", aliases:["liz truss","truss"]},
  {name:"Boris Johnson", country:"United Kingdom", dates:"2019–2022", x:4, y:1, blurb:"Populist-right, Brexit, some executive overreach controversies.", aliases:["boris johnson","boris"]},
  {name:"Theresa May", country:"United Kingdom", dates:"2016–2019", x:3, y:2, blurb:"Centrist Conservative, Brexit negotiations.", aliases:["theresa may"]},
  {name:"David Cameron", country:"United Kingdom", dates:"2010–2016", x:5, y:3, blurb:"Austerity economics, coalition government.", aliases:["david cameron","cameron"]},
  {name:"Gordon Brown", country:"United Kingdom", dates:"2007–2010", x:-2, y:4, blurb:"Labour, financial-crisis response.", aliases:["gordon brown"]},
  {name:"Tony Blair", country:"United Kingdom", dates:"1997–2007", x:0, y:2, blurb:"\"New Labour\" centrism.", aliases:["tony blair","blair"]},
  {name:"Margaret Thatcher", country:"United Kingdom", dates:"1979–1990", x:8, y:1, blurb:"Privatization, free-market deregulation.", aliases:["thatcher","margaret thatcher"]},
  {name:"Winston Churchill", country:"United Kingdom", dates:"1940–1945, 1951–1955", x:3, y:3, blurb:"Wartime leadership, traditional conservative economics.", aliases:["churchill","winston churchill"]},
  {name:"Andy Burnham", country:"United Kingdom", dates:"2017–present (Gtr Manchester Mayor)", x:-6, y:3, blurb:"Left-leaning Labour, no authoritarian record.", aliases:["andy burnham","burnham"]},
  {name:"Nigel Farage", country:"United Kingdom", dates:"2024–present, Reform UK leader", x:6, y:-2, blurb:"Right-populist, nationalist on immigration.", aliases:["farage","nigel farage"]},
  {name:"Rupert Lowe", country:"United Kingdom", dates:"2025–present, Restore Britain leader", x:8, y:-5, blurb:"Further right and more authoritarian-leaning than Farage.", aliases:["rupert lowe","lowe"]},
  {name:"Jeremy Corbyn", country:"United Kingdom", dates:"Labour leader 2015–2020", x:-8, y:4, blurb:"Democratic socialist, strong civil-liberties positions.", aliases:["corbyn","jeremy corbyn"]},

  // --- France ---
  {name:"Emmanuel Macron", country:"France", dates:"2017–present, President (not PM)", x:3, y:1, blurb:"Centrist market reforms, standard democratic leader.", aliases:["macron","emmanuel macron"]},
  {name:"Marine Le Pen", country:"France", dates:"RN Assembly leader since 2022", x:2, y:-5, blurb:"Nationalist right, protectionist economics.", aliases:["le pen","marine le pen"]},
  {name:"Charles de Gaulle", country:"France", dates:"1959–1969", x:2, y:0, blurb:"Nationalist, strong-executive Fifth Republic founder.", aliases:["de gaulle","charles de gaulle"]},

  // --- Germany ---
  {name:"Friedrich Merz", country:"Germany", dates:"2025–present", x:4, y:2, blurb:"Conservative CDU chancellor, market-oriented.", aliases:["merz","friedrich merz"]},
  {name:"Olaf Scholz", country:"Germany", dates:"2021–2025", x:-1, y:3, blurb:"Center-left SPD chancellor.", aliases:["scholz","olaf scholz"]},
  {name:"Angela Merkel", country:"Germany", dates:"2005–2021", x:1, y:3, blurb:"Centrist CDU, long-tenured stable democratic rule.", aliases:["merkel","angela merkel"]},
  {name:"Helmut Kohl", country:"Germany", dates:"1982–1998", x:3, y:2, blurb:"Center-right, German reunification.", aliases:["kohl","helmut kohl"]},
  {name:"Willy Brandt", country:"Germany", dates:"1969–1974", x:-4, y:4, blurb:"Social democrat, Ostpolitik détente policy.", aliases:["willy brandt","brandt"]},

  // --- rest of world (current-ish) ---
  {name:"Volodymyr Zelenskyy", country:"Ukraine", dates:"2019–present", x:-1, y:2, blurb:"Wartime democratic leader, some emergency-powers debate.", aliases:["zelensky","zelenskyy","volodymyr zelensky"]},
  {name:"Narendra Modi", country:"India", dates:"2014–present", x:3, y:-3, blurb:"Hindu-nationalist right, market reforms, press-freedom concerns.", aliases:["modi","narendra modi"]},
  {name:"Justin Trudeau", country:"Canada", dates:"2015–2025", x:-2, y:4, blurb:"Center-left Liberal, standard democratic governance.", aliases:["trudeau","justin trudeau"]},
  {name:"Giorgia Meloni", country:"Italy", dates:"2022–present", x:4, y:-1, blurb:"National-conservative right, within EU democratic norms.", aliases:["meloni","giorgia meloni"]},
  {name:"Pedro Sánchez", country:"Spain", dates:"2018–present", x:-3, y:3, blurb:"Center-left PSOE, standard democratic governance.", aliases:["pedro sanchez","sanchez"]},
  {name:"Lula da Silva", country:"Brazil", dates:"2003–2011, 2023–present", x:-5, y:3, blurb:"Left-leaning Workers' Party, democratic governance.", aliases:["lula","lula da silva"]},
  {name:"Jair Bolsonaro", country:"Brazil", dates:"2019–2023", x:5, y:-4, blurb:"Right-populist, some institutional-norm controversies.", aliases:["bolsonaro","jair bolsonaro"]},
  {name:"Javier Milei", country:"Argentina", dates:"2023–present", x:9, y:0, blurb:"Libertarian free-market radical, minimal-state agenda.", aliases:["milei","javier milei"]},
  {name:"Cyril Ramaphosa", country:"South Africa", dates:"2018–present", x:-3, y:3, blurb:"Center-left ANC, democratic governance.", aliases:["ramaphosa","cyril ramaphosa"]},
  {name:"Anthony Albanese", country:"Australia", dates:"2022–present", x:-3, y:4, blurb:"Center-left Labor, standard democratic governance.", aliases:["albanese","anthony albanese"]},
  {name:"Benjamin Netanyahu", country:"Israel", dates:"1996–1999, 2009–present", x:6, y:-3, blurb:"Right-leaning market reforms, judicial-overhaul controversy.", aliases:["netanyahu","bibi","benjamin netanyahu"], flags:["warcrimes"]},

  // --- Asia ---
  {name:"Shinzo Abe", country:"Japan", dates:"2006–2007, 2012–2020", x:5, y:1, blurb:"Conservative LDP, market reforms (\"Abenomics\").", aliases:["abe","shinzo abe"]},
  {name:"Fumio Kishida", country:"Japan", dates:"2021–2024", x:3, y:2, blurb:"Moderate LDP conservative.", aliases:["kishida","fumio kishida"]},
  {name:"Shigeru Ishiba", country:"Japan", dates:"2024–present", x:2, y:2, blurb:"Moderate LDP, defense-focused.", aliases:["ishiba","shigeru ishiba"]},
  {name:"Junichiro Koizumi", country:"Japan", dates:"2001–2006", x:6, y:1, blurb:"Privatization-focused LDP reformer.", aliases:["koizumi","junichiro koizumi"]},
  {name:"Rodrigo Duterte", country:"Philippines", dates:"2016–2022", x:-1, y:-7, blurb:"Populist, violent anti-drug crackdown.", aliases:["duterte","rodrigo duterte"]},
  {name:"Ferdinand Marcos Jr", country:"Philippines", dates:"2022–present", x:2, y:-3, blurb:"Dynastic conservative rule.", aliases:["marcos jr","bongbong marcos","ferdinand marcos jr"]},
  {name:"Joko Widodo", country:"Indonesia", dates:"2014–2024", x:-1, y:1, blurb:"Pragmatic developmentalist, democratic norms.", aliases:["jokowi","joko widodo"]},
  {name:"Prabowo Subianto", country:"Indonesia", dates:"2024–present", x:1, y:-2, blurb:"Nationalist, ex-military background.", aliases:["prabowo","prabowo subianto"]},
  {name:"Lee Kuan Yew", country:"Singapore", dates:"1959–1990", x:3, y:-4, blurb:"Market economy under tightly controlled politics.", aliases:["lee kuan yew"]},
  {name:"Lee Hsien Loong", country:"Singapore", dates:"2004–2024", x:3, y:-2, blurb:"Continued PAP dominance, market economy.", aliases:["lee hsien loong"]},
  {name:"Imran Khan", country:"Pakistan", dates:"2018–2022", x:-1, y:-2, blurb:"Populist, later jailed amid political crackdown.", aliases:["imran khan"]},
  {name:"Sheikh Hasina", country:"Bangladesh", dates:"2009–2024", x:-3, y:-6, blurb:"Increasingly authoritarian one-party dominance.", aliases:["sheikh hasina","hasina"]},
  {name:"Muhammad Yunus", country:"Bangladesh", dates:"2024–present, interim leader", x:-2, y:3, blurb:"Microfinance pioneer leading interim reform government.", aliases:["yunus","muhammad yunus"]},
  {name:"Aung San Suu Kyi", country:"Myanmar", dates:"2016–2021", x:-2, y:4, blurb:"Democracy icon, later overthrown by coup.", aliases:["aung san suu kyi","suu kyi"]},
  {name:"Hun Sen", country:"Cambodia", dates:"1985–2023", x:-3, y:-7, blurb:"Long-ruling one-party dominance.", aliases:["hun sen"]},
  {name:"Thaksin Shinawatra", country:"Thailand", dates:"2001–2006", x:1, y:-3, blurb:"Populist business tycoon, ousted by coup.", aliases:["thaksin","thaksin shinawatra"]},
  {name:"Prayut Chan-o-cha", country:"Thailand", dates:"2014–2023", x:2, y:-6, blurb:"Military junta leader turned civilian PM.", aliases:["prayut","prayut chan-o-cha"]},
  {name:"Mahinda Rajapaksa", country:"Sri Lanka", dates:"2005–2015", x:-1, y:-5, blurb:"Nationalist, centralized executive power.", aliases:["mahinda rajapaksa","rajapaksa"]},
  {name:"Indira Gandhi", country:"India", dates:"1966–1977, 1980–1984", x:-4, y:-4, blurb:"State-led economy, imposed emergency rule 1975-77.", aliases:["indira gandhi"]},
  {name:"Jawaharlal Nehru", country:"India", dates:"1947–1964", x:-5, y:3, blurb:"Democratic socialist, founding PM.", aliases:["nehru","jawaharlal nehru"]},

  // --- Middle East ---
  {name:"Mohammed bin Zayed", country:"UAE", dates:"2022–present", x:5, y:-6, blurb:"Absolute rule, market-friendly economy.", aliases:["mbz","mohammed bin zayed"]},
  {name:"Hosni Mubarak", country:"Egypt", dates:"1981–2011", x:1, y:-7, blurb:"Long authoritarian rule, ousted in Arab Spring.", aliases:["mubarak","hosni mubarak"]},
  {name:"Abdel Fattah el-Sisi", country:"Egypt", dates:"2014–present", x:1, y:-7, blurb:"Military-backed authoritarian rule.", aliases:["sisi","el-sisi","abdel fattah el-sisi"]},
  {name:"Anwar Sadat", country:"Egypt", dates:"1970–1981", x:1, y:-5, blurb:"Economic liberalization, centralized power.", aliases:["sadat","anwar sadat"]},
  {name:"Yasser Arafat", country:"Palestine", dates:"1994–2004", x:-3, y:-4, blurb:"PLO/PA leader, centralized personal authority.", aliases:["arafat","yasser arafat"]},
  {name:"Mahmoud Abbas", country:"Palestine", dates:"2005–present", x:-2, y:-4, blurb:"PA leader, term repeatedly extended without new elections.", aliases:["abbas","mahmoud abbas"]},
  {name:"Yitzhak Rabin", country:"Israel", dates:"1974–1977, 1992–1995", x:-1, y:3, blurb:"Peace-process focused, standard democratic norms.", aliases:["rabin","yitzhak rabin"]},
  {name:"Golda Meir", country:"Israel", dates:"1969–1974", x:-3, y:2, blurb:"Labor-aligned, standard democratic norms.", aliases:["golda meir"]},
  {name:"King Hussein", country:"Jordan", dates:"1952–1999", x:3, y:-3, blurb:"Monarchy with limited pluralism.", aliases:["king hussein"]},
  {name:"King Abdullah II", country:"Jordan", dates:"1999–present", x:3, y:-3, blurb:"Monarchy with limited pluralism.", aliases:["king abdullah ii","abdullah ii"]},
  {name:"Hassan Rouhani", country:"Iran", dates:"2013–2021", x:2, y:-5, blurb:"Relatively moderate cleric within theocratic system.", aliases:["rouhani","hassan rouhani"]},
  {name:"Mahmoud Ahmadinejad", country:"Iran", dates:"2005–2013", x:-2, y:-7, blurb:"Populist-conservative, hardline theocratic system.", aliases:["ahmadinejad","mahmoud ahmadinejad"]},

  // --- Africa ---
  {name:"Jomo Kenyatta", country:"Kenya", dates:"1964–1978", x:1, y:-3, blurb:"Founding president, centralized rule.", aliases:["jomo kenyatta"]},
  {name:"Uhuru Kenyatta", country:"Kenya", dates:"2013–2022", x:2, y:-2, blurb:"Market-oriented, democratic transitions of power.", aliases:["uhuru kenyatta","uhuru"]},
  {name:"William Ruto", country:"Kenya", dates:"2022–present", x:1, y:-1, blurb:"Market-oriented, democratic governance.", aliases:["ruto","william ruto"]},
  {name:"Julius Nyerere", country:"Tanzania", dates:"1964–1985", x:-6, y:-2, blurb:"African socialism (Ujamaa), one-party state.", aliases:["nyerere","julius nyerere"]},
  {name:"Kenneth Kaunda", country:"Zambia", dates:"1964–1991", x:-5, y:-3, blurb:"African socialism, one-party rule.", aliases:["kaunda","kenneth kaunda"]},
  {name:"Jerry Rawlings", country:"Ghana", dates:"1981–2001", x:-4, y:-5, blurb:"Military-populist, later democratized.", aliases:["rawlings","jerry rawlings"]},
  {name:"Nana Akufo-Addo", country:"Ghana", dates:"2017–2025", x:2, y:1, blurb:"Center-right, democratic governance.", aliases:["akufo-addo","nana akufo-addo"]},
  {name:"Muhammadu Buhari", country:"Nigeria", dates:"2015–2023", x:-1, y:-3, blurb:"Anti-corruption focus, some authoritarian tendencies.", aliases:["buhari","muhammadu buhari"]},
  {name:"Bola Tinubu", country:"Nigeria", dates:"2023–present", x:2, y:-2, blurb:"Market reforms, democratic governance.", aliases:["tinubu","bola tinubu"]},
  {name:"Olusegun Obasanjo", country:"Nigeria", dates:"1999–2007", x:0, y:-1, blurb:"Ex-military turned democratic president.", aliases:["obasanjo","olusegun obasanjo"]},
  {name:"Thabo Mbeki", country:"South Africa", dates:"1999–2008", x:-2, y:2, blurb:"Market-friendly ANC, democratic norms.", aliases:["mbeki","thabo mbeki"]},
  {name:"F.W. de Klerk", country:"South Africa", dates:"1989–1994", x:3, y:-2, blurb:"Ended apartheid, transitioned to democracy.", aliases:["de klerk","fw de klerk"]},
  {name:"Jacob Zuma", country:"South Africa", dates:"2009–2018", x:-2, y:-3, blurb:"Populist ANC, corruption scandals.", aliases:["zuma","jacob zuma"], flags:["corruption"]},
  {name:"Yoweri Museveni", country:"Uganda", dates:"1986–present", x:-1, y:-6, blurb:"Long-ruling, restricts opposition.", aliases:["museveni","yoweri museveni"]},
  {name:"Paul Kagame", country:"Rwanda", dates:"2000–present", x:-1, y:-6, blurb:"Developmental authoritarianism, tight political control.", aliases:["kagame","paul kagame"]},
  {name:"Denis Sassou Nguesso", country:"Republic of the Congo", dates:"1979–1992, 1997–present", x:-2, y:-7, blurb:"Long-ruling, oil-fueled patronage.", aliases:["sassou nguesso","denis sassou nguesso"]},
  {name:"Joseph Kabila", country:"DR Congo", dates:"2001–2019", x:-2, y:-6, blurb:"Overstayed term limits before stepping down.", aliases:["kabila","joseph kabila"]},
  {name:"Félix Tshisekedi", country:"DR Congo", dates:"2019–present", x:-1, y:-4, blurb:"Contested elections, gradual consolidation.", aliases:["tshisekedi","felix tshisekedi"]},
  {name:"Emmerson Mnangagwa", country:"Zimbabwe", dates:"2017–present", x:-4, y:-6, blurb:"Continued ZANU-PF authoritarian rule after Mugabe.", aliases:["mnangagwa","emmerson mnangagwa"]},
  {name:"Abiy Ahmed", country:"Ethiopia", dates:"2018–present", x:-2, y:-5, blurb:"Reformist start, later civil conflict/centralization.", aliases:["abiy ahmed","abiy"]},
  {name:"Ismail Omar Guelleh", country:"Djibouti", dates:"1999–present", x:-1, y:-6, blurb:"Long-ruling, limited political pluralism.", aliases:["guelleh","ismail omar guelleh"]},
  {name:"Idriss Déby", country:"Chad", dates:"1990–2021", x:-1, y:-7, blurb:"Long military-backed authoritarian rule.", aliases:["deby","idriss deby"]},

  // --- Latin America ---
  {name:"Hugo Chávez", country:"Venezuela", dates:"1999–2013", x:-8, y:-6, blurb:"Socialist \"Bolivarian Revolution,\" centralized power.", aliases:["chavez","hugo chavez"]},
  {name:"Evo Morales", country:"Bolivia", dates:"2006–2019", x:-7, y:-3, blurb:"Indigenous-socialist, nationalized industries.", aliases:["evo morales","evo"]},
  {name:"Luis Arce", country:"Bolivia", dates:"2020–present", x:-6, y:1, blurb:"Socialist economics, democratic governance.", aliases:["luis arce"]},
  {name:"Rafael Correa", country:"Ecuador", dates:"2007–2017", x:-6, y:-2, blurb:"Left-populist, press-freedom concerns.", aliases:["correa","rafael correa"], flags:["corruption"]},
  {name:"Gabriel Boric", country:"Chile", dates:"2022–present", x:-6, y:5, blurb:"Millennial left, strong democratic/civil-liberties focus.", aliases:["boric","gabriel boric"]},
  {name:"Sebastián Piñera", country:"Chile", dates:"2010–2014, 2018–2022", x:5, y:3, blurb:"Center-right businessman, democratic governance.", aliases:["pinera","sebastian pinera"]},
  {name:"Michelle Bachelet", country:"Chile", dates:"2006–2010, 2014–2018", x:-4, y:4, blurb:"Center-left, strong civil-liberties record.", aliases:["bachelet","michelle bachelet"]},
  {name:"Cristina Fernández de Kirchner", country:"Argentina", dates:"2007–2015", x:-5, y:-1, blurb:"Left-populist Peronism.", aliases:["cristina kirchner","cristina fernandez"], flags:["corruption"]},
  {name:"Néstor Kirchner", country:"Argentina", dates:"2003–2007", x:-5, y:0, blurb:"Left-leaning Peronism.", aliases:["nestor kirchner"]},
  {name:"Mauricio Macri", country:"Argentina", dates:"2015–2019", x:5, y:2, blurb:"Center-right market reforms.", aliases:["macri","mauricio macri"]},
  {name:"Andrés Manuel López Obrador", country:"Mexico", dates:"2018–2024", x:-4, y:-1, blurb:"Left-populist, some institutional-norm friction.", aliases:["amlo","lopez obrador","andres manuel lopez obrador"]},
  {name:"Claudia Sheinbaum", country:"Mexico", dates:"2024–present", x:-4, y:1, blurb:"Left-leaning, continuity with AMLO's agenda.", aliases:["sheinbaum","claudia sheinbaum"]},
  {name:"Felipe Calderón", country:"Mexico", dates:"2006–2012", x:3, y:1, blurb:"Center-right, drug-war security expansion.", aliases:["calderon","felipe calderon"]},
  {name:"Vicente Fox", country:"Mexico", dates:"2000–2006", x:3, y:2, blurb:"Ended 71 years of one-party rule.", aliases:["vicente fox"]},
  {name:"Juan Manuel Santos", country:"Colombia", dates:"2010–2018", x:1, y:2, blurb:"Peace-process focused centrist.", aliases:["santos","juan manuel santos"]},
  {name:"Gustavo Petro", country:"Colombia", dates:"2022–present", x:-6, y:2, blurb:"First leftist president, democratic governance.", aliases:["petro","gustavo petro"]},
  {name:"Álvaro Uribe", country:"Colombia", dates:"2002–2010", x:5, y:-3, blurb:"Hardline security policies, some institutional friction.", aliases:["uribe","alvaro uribe"]},
  {name:"Dilma Rousseff", country:"Brazil", dates:"2011–2016", x:-4, y:3, blurb:"Left-leaning Workers' Party, impeached.", aliases:["dilma","dilma rousseff"]},
  {name:"Fernando Henrique Cardoso", country:"Brazil", dates:"1995–2003", x:1, y:3, blurb:"Centrist market reforms, price stabilization.", aliases:["fhc","fernando henrique cardoso"]},
  {name:"Daniel Noboa", country:"Ecuador", dates:"2023–present", x:3, y:-1, blurb:"Center-right, security crackdowns amid gang violence.", aliases:["noboa","daniel noboa"]},

  // --- Continental Europe & Oceania ---
  {name:"Silvio Berlusconi", country:"Italy", dates:"1994–1995, 2001–2006, 2008–2011", x:4, y:0, blurb:"Media-mogul populist, conflict-of-interest controversies.", aliases:["berlusconi","silvio berlusconi"], flags:["corruption"]},
  {name:"Matteo Renzi", country:"Italy", dates:"2014–2016", x:0, y:2, blurb:"Centrist reformer.", aliases:["renzi","matteo renzi"]},
  {name:"Viktor Orbán", country:"Hungary", dates:"1998–2002, 2010–present", x:3, y:-6, blurb:"\"Illiberal democracy,\" nationalist-conservative.", aliases:["orban","viktor orban"]},
  {name:"Andrzej Duda", country:"Poland", dates:"2015–present", x:3, y:-3, blurb:"National-conservative, judiciary controversies.", aliases:["duda","andrzej duda"]},
  {name:"Donald Tusk", country:"Poland", dates:"2007–2014, 2023–present", x:1, y:3, blurb:"Centrist, pro-EU.", aliases:["tusk","donald tusk"]},
  {name:"Jarosław Kaczyński", country:"Poland", dates:"PiS party leader", x:3, y:-5, blurb:"National-conservative, judicial-independence disputes.", aliases:["kaczynski","jaroslaw kaczynski"]},
  {name:"José Luis Rodríguez Zapatero", country:"Spain", dates:"2004–2011", x:-4, y:3, blurb:"Center-left social reforms.", aliases:["zapatero","jose luis rodriguez zapatero"]},
  {name:"Mariano Rajoy", country:"Spain", dates:"2011–2018", x:3, y:2, blurb:"Center-right austerity economics.", aliases:["rajoy","mariano rajoy"]},
  {name:"Alexis Tsipras", country:"Greece", dates:"2015–2019", x:-6, y:2, blurb:"Left-wing Syriza, anti-austerity.", aliases:["tsipras","alexis tsipras"]},
  {name:"Kyriakos Mitsotakis", country:"Greece", dates:"2019–present", x:4, y:1, blurb:"Center-right market reforms.", aliases:["mitsotakis","kyriakos mitsotakis"]},
  {name:"Geert Wilders", country:"Netherlands", dates:"PVV party leader", x:3, y:-4, blurb:"Right-populist nationalist.", aliases:["wilders","geert wilders"]},
  {name:"Mark Rutte", country:"Netherlands", dates:"2010–2024", x:3, y:2, blurb:"Center-right liberal, standard democratic norms.", aliases:["rutte","mark rutte"]},
  {name:"Olof Palme", country:"Sweden", dates:"1969–1976, 1982–1986", x:-6, y:4, blurb:"Social democrat, strong welfare state.", aliases:["olof palme"]},
  {name:"Magdalena Andersson", country:"Sweden", dates:"2021–2022", x:-4, y:3, blurb:"Social democrat.", aliases:["magdalena andersson"]},
  {name:"Jens Stoltenberg", country:"Norway", dates:"2000–2001, 2005–2013", x:-3, y:4, blurb:"Social democrat.", aliases:["stoltenberg","jens stoltenberg"]},
  {name:"Mette Frederiksen", country:"Denmark", dates:"2019–present", x:-3, y:3, blurb:"Social democrat with restrictive immigration stance.", aliases:["frederiksen","mette frederiksen"]},
  {name:"Sanna Marin", country:"Finland", dates:"2019–2023", x:-4, y:4, blurb:"Social democrat, youngest PM at the time.", aliases:["sanna marin"]},
  {name:"Leo Varadkar", country:"Ireland", dates:"2017–2020, 2022–2024", x:2, y:3, blurb:"Center-right liberal-conservative.", aliases:["varadkar","leo varadkar"]},
  {name:"Petro Poroshenko", country:"Ukraine", dates:"2014–2019", x:2, y:1, blurb:"Business-oligarch turned reform-minded president.", aliases:["poroshenko","petro poroshenko"]},
  {name:"John Howard", country:"Australia", dates:"1996–2007", x:5, y:1, blurb:"Center-right, market liberalization.", aliases:["john howard"]},
  {name:"Julia Gillard", country:"Australia", dates:"2010–2013", x:-3, y:3, blurb:"Center-left Labor.", aliases:["julia gillard"]},
  {name:"Jacinda Ardern", country:"New Zealand", dates:"2017–2023", x:-4, y:5, blurb:"Center-left, strong civil-liberties record.", aliases:["ardern","jacinda ardern","jacinda"]},
  {name:"Christopher Luxon", country:"New Zealand", dates:"2023–present", x:4, y:2, blurb:"Center-right, business background.", aliases:["luxon","christopher luxon"]},
  {name:"Robert Menzies", country:"Australia", dates:"1949–1966", x:4, y:1, blurb:"Longest-serving PM, center-right.", aliases:["robert menzies","menzies"]},
  {name:"Helen Clark", country:"New Zealand", dates:"1999–2008", x:-4, y:4, blurb:"Center-left Labour.", aliases:["helen clark"]},
// --- UK MPs ---
  {name:"Ed Miliband", country:"United Kingdom", dates:"Energy Secretary, 2024–present", x:-6, y:4, blurb:"Left-leaning Labour, climate policy focus.", aliases:["ed miliband","miliband"]},
  {name:"Rachel Reeves", country:"United Kingdom", dates:"Chancellor of the Exchequer, 2024–present", x:-2, y:3, blurb:"Fiscally cautious Labour centrist.", aliases:["rachel reeves","reeves"]},
  {name:"David Lammy", country:"United Kingdom", dates:"Foreign Secretary, 2024–present", x:-3, y:3, blurb:"Center-left Labour, internationalist.", aliases:["david lammy","lammy"]},
  {name:"Yvette Cooper", country:"United Kingdom", dates:"Home Secretary, 2024–present", x:-2, y:2, blurb:"Center-left Labour.", aliases:["yvette cooper","cooper"]},
  {name:"Wes Streeting", country:"United Kingdom", dates:"Health Secretary, 2024–present", x:0, y:3, blurb:"More centrist wing of Labour.", aliases:["wes streeting","streeting"]},
  {name:"Angela Rayner", country:"United Kingdom", dates:"Deputy PM, 2024–present", x:-5, y:3, blurb:"Left-wing Labour, trade-union background.", aliases:["angela rayner","rayner"]},
  {name:"Kemi Badenoch", country:"United Kingdom", dates:"Conservative Party leader, 2024–present", x:6, y:0, blurb:"Right-wing Conservative, culture-war focus.", aliases:["kemi badenoch","badenoch"]},
  {name:"Priti Patel", country:"United Kingdom", dates:"Former Home Secretary", x:6, y:-2, blurb:"Right-wing Conservative, hardline immigration stance.", aliases:["priti patel","patel"]},
  {name:"Suella Braverman", country:"United Kingdom", dates:"Former Home Secretary", x:7, y:-3, blurb:"Hard-right Conservative, restrictive immigration stance.", aliases:["suella braverman","braverman"]},
  {name:"Jacob Rees-Mogg", country:"United Kingdom", dates:"Former Cabinet minister", x:8, y:1, blurb:"Traditionalist free-market Conservative.", aliases:["jacob rees-mogg","rees-mogg","rees mogg"]},
  {name:"Michael Gove", country:"United Kingdom", dates:"Former Cabinet minister", x:5, y:1, blurb:"Center-right Conservative reformer.", aliases:["michael gove","gove"]},
  {name:"Dominic Raab", country:"United Kingdom", dates:"Former Deputy PM", x:6, y:0, blurb:"Right-leaning Conservative.", aliases:["dominic raab","raab"]},
  {name:"Ed Davey", country:"United Kingdom", dates:"Liberal Democrat leader, 2020–present", x:-3, y:5, blurb:"Centrist liberal, strong civil-liberties record.", aliases:["ed davey","davey"]},
  {name:"Vince Cable", country:"United Kingdom", dates:"Former Lib Dem leader", x:-2, y:4, blurb:"Centrist liberal economist.", aliases:["vince cable","cable"]},
  {name:"Caroline Lucas", country:"United Kingdom", dates:"Former Green MP", x:-7, y:6, blurb:"Green Party, strong civil-liberties and environmental focus.", aliases:["caroline lucas"]},
  {name:"Zack Polanski", country:"United Kingdom", dates:"Green Party leader, 2025–present", x:-7, y:5, blurb:"Left-wing eco-populist.", aliases:["zack polanski","polanski"]},
  {name:"Nicola Sturgeon", country:"United Kingdom", dates:"Scottish First Minister, 2014–2023", x:-4, y:3, blurb:"Center-left SNP, Scottish independence focus.", aliases:["nicola sturgeon","sturgeon"]},
  {name:"John Swinney", country:"United Kingdom", dates:"Scottish First Minister, 2024–present", x:-4, y:3, blurb:"Center-left SNP.", aliases:["john swinney","swinney"]},
  {name:"Humza Yousaf", country:"United Kingdom", dates:"Scottish First Minister, 2023–2024", x:-4, y:3, blurb:"Center-left SNP.", aliases:["humza yousaf","yousaf"]},
  {name:"Diane Abbott", country:"United Kingdom", dates:"Labour MP since 1987", x:-8, y:5, blurb:"Veteran hard-left Labour backbencher.", aliases:["diane abbott","abbott"]},
  {name:"Zarah Sultana", country:"United Kingdom", dates:"Independent MP (ex-Labour)", x:-8, y:4, blurb:"Hard-left, left Labour over whip suspension.", aliases:["zarah sultana","sultana"]},
  {name:"George Galloway", country:"United Kingdom", dates:"Workers Party leader", x:-5, y:-2, blurb:"Left-populist, some illiberal rhetoric controversies.", aliases:["george galloway","galloway"]},
  {name:"Lee Anderson", country:"United Kingdom", dates:"Reform UK MP", x:7, y:-4, blurb:"Right-populist, defected from Conservatives to Reform.", aliases:["lee anderson"]},
  {name:"Richard Tice", country:"United Kingdom", dates:"Reform UK deputy leader", x:7, y:-2, blurb:"Right-populist, business background.", aliases:["richard tice","tice"]},
  {name:"Harriet Harman", country:"United Kingdom", dates:"Former Labour deputy leader", x:-4, y:4, blurb:"Veteran center-left Labour.", aliases:["harriet harman","harman"]},
  {name:"Kenneth Clarke", country:"United Kingdom", dates:"Former Chancellor, retired", x:3, y:3, blurb:"One-nation centrist Conservative.", aliases:["ken clarke","kenneth clarke"]},
  {name:"William Hague", country:"United Kingdom", dates:"Former Conservative leader", x:5, y:2, blurb:"Center-right Conservative.", aliases:["william hague","hague"]},
  {name:"Iain Duncan Smith", country:"United Kingdom", dates:"Former Conservative leader", x:5, y:-1, blurb:"Right-wing Conservative, welfare-reform focus.", aliases:["iain duncan smith","ids"]},

  // --- US Senators ---
  {name:"Chuck Schumer", country:"United States", dates:"Senator (NY), 1999–present", x:-3, y:3, blurb:"Senate Democratic leader, center-left.", aliases:["chuck schumer","schumer"]},
  {name:"Mitch McConnell", country:"United States", dates:"Senator (KY), 1985–present", x:4, y:1, blurb:"Longtime Senate Republican leader.", aliases:["mitch mcconnell","mcconnell"]},
  {name:"John Thune", country:"United States", dates:"Senator (SD), Majority Leader", x:4, y:1, blurb:"Establishment Republican.", aliases:["john thune","thune"]},
  {name:"Elizabeth Warren", country:"United States", dates:"Senator (MA), 2013–present", x:-7, y:5, blurb:"Progressive Democrat, financial-regulation focus.", aliases:["elizabeth warren","warren"]},
  {name:"Ted Cruz", country:"United States", dates:"Senator (TX), 2013–present", x:7, y:-1, blurb:"Hard-right conservative Republican.", aliases:["ted cruz","cruz"]},
  {name:"Josh Hawley", country:"United States", dates:"Senator (MO), 2019–present", x:5, y:-3, blurb:"Right-wing populist Republican.", aliases:["josh hawley","hawley"]},
  {name:"Rand Paul", country:"United States", dates:"Senator (KY), 2011–present", x:6, y:6, blurb:"Libertarian-leaning Republican.", aliases:["rand paul"]},
  {name:"Marco Rubio", country:"United States", dates:"Former Senator (FL); Secretary of State, 2025–present", x:5, y:0, blurb:"Establishment conservative Republican.", aliases:["marco rubio","rubio"]},
  {name:"Lindsey Graham", country:"United States", dates:"Senator (SC), 2003–present", x:4, y:-1, blurb:"Hawkish establishment Republican.", aliases:["lindsey graham","graham"]},
  {name:"Susan Collins", country:"United States", dates:"Senator (ME), 1997–present", x:2, y:4, blurb:"Moderate Republican, frequent swing vote.", aliases:["susan collins","collins"]},
  {name:"Lisa Murkowski", country:"United States", dates:"Senator (AK), 2002–present", x:1, y:4, blurb:"Moderate Republican, frequent swing vote.", aliases:["lisa murkowski","murkowski"]},
  {name:"Joe Manchin", country:"United States", dates:"Former Senator (WV), Independent", x:1, y:2, blurb:"Conservative Democrat turned independent, swing vote.", aliases:["joe manchin","manchin"]},
  {name:"Kyrsten Sinema", country:"United States", dates:"Former Senator (AZ), Independent", x:1, y:2, blurb:"Centrist, left Democratic Party to become independent.", aliases:["kyrsten sinema","sinema"]},
  {name:"Amy Klobuchar", country:"United States", dates:"Senator (MN), 2007–present", x:-3, y:4, blurb:"Center-left Democrat.", aliases:["amy klobuchar","klobuchar"]},
  {name:"Cory Booker", country:"United States", dates:"Senator (NJ), 2013–present", x:-4, y:5, blurb:"Center-left Democrat.", aliases:["cory booker","booker"]},
  {name:"Kamala Harris", country:"United States", dates:"Former Senator (CA); VP 2021–2025", x:-3, y:3, blurb:"Center-left Democrat.", aliases:["kamala harris","harris"]},
  {name:"J.D. Vance", country:"United States", dates:"Former Senator (OH); VP 2025–present", x:5, y:-3, blurb:"Right-populist Republican.", aliases:["jd vance","j.d. vance","vance"]},
  {name:"Tom Cotton", country:"United States", dates:"Senator (AR), 2015–present", x:6, y:-3, blurb:"Hard-right conservative Republican.", aliases:["tom cotton","cotton"]},
  {name:"John Fetterman", country:"United States", dates:"Senator (PA), 2023–present", x:-3, y:3, blurb:"Populist-leaning Democrat.", aliases:["john fetterman","fetterman"]},
  {name:"Raphael Warnock", country:"United States", dates:"Senator (GA), 2021–present", x:-4, y:4, blurb:"Center-left Democrat.", aliases:["raphael warnock","warnock"]},
  {name:"Tim Scott", country:"United States", dates:"Senator (SC), 2013–present", x:4, y:2, blurb:"Establishment conservative Republican.", aliases:["tim scott"]},
  {name:"Mike Lee", country:"United States", dates:"Senator (UT), 2011–present", x:6, y:5, blurb:"Libertarian-leaning Republican.", aliases:["mike lee"]},
  {name:"Chuck Grassley", country:"United States", dates:"Senator (IA), 1981–present", x:4, y:1, blurb:"Veteran establishment Republican.", aliases:["chuck grassley","grassley"]},
// --- Mayors (UK) ---
  {name:"Sadiq Khan", country:"United Kingdom", dates:"Mayor of London, 2016–present", x:-4, y:3, blurb:"Center-left Labour, London Mayor.", aliases:["sadiq khan","khan"]},
  {name:"Andy Street", country:"United Kingdom", dates:"West Midlands Mayor, 2017–2024", x:4, y:2, blurb:"Center-right Conservative, business background.", aliases:["andy street","street"]},
  {name:"Tracy Brabin", country:"United Kingdom", dates:"West Yorkshire Mayor, 2021–present", x:-4, y:3, blurb:"Center-left Labour.", aliases:["tracy brabin","brabin"]},
  {name:"Ben Houchen", country:"United Kingdom", dates:"Tees Valley Mayor, 2017–present", x:3, y:2, blurb:"Center-right Conservative, regional-investment focus.", aliases:["ben houchen","houchen"]},

  // --- Mayors (US) ---
  {name:"Eric Adams", country:"United States", dates:"Mayor of New York City, 2022–present", x:-1, y:0, blurb:"Moderate Democrat, controversial corruption allegations.", aliases:["eric adams"]},
  {name:"Karen Bass", country:"United States", dates:"Mayor of Los Angeles, 2022–present", x:-4, y:3, blurb:"Center-left Democrat.", aliases:["karen bass","bass"]},
  {name:"Brandon Johnson", country:"United States", dates:"Mayor of Chicago, 2023–present", x:-6, y:3, blurb:"Progressive Democrat, teachers'-union background.", aliases:["brandon johnson"]},
  {name:"Michelle Wu", country:"United States", dates:"Mayor of Boston, 2021–present", x:-5, y:4, blurb:"Progressive Democrat.", aliases:["michelle wu","wu"]},
  {name:"Muriel Bowser", country:"United States", dates:"Mayor of Washington DC, 2015–present", x:-3, y:3, blurb:"Center-left Democrat.", aliases:["muriel bowser","bowser"]},
  {name:"Daniel Lurie", country:"United States", dates:"Mayor of San Francisco, 2025–present", x:-2, y:2, blurb:"Moderate Democrat, nonprofit background.", aliases:["daniel lurie","lurie"]},
  {name:"London Breed", country:"United States", dates:"Former Mayor of San Francisco, 2018–2025", x:-2, y:2, blurb:"Moderate Democrat.", aliases:["london breed","breed"]},
  {name:"Bill de Blasio", country:"United States", dates:"Former Mayor of New York City, 2014–2022", x:-5, y:3, blurb:"Progressive Democrat.", aliases:["bill de blasio","de blasio"]},
  {name:"Rudy Giuliani", country:"United States", dates:"Former Mayor of New York City, 1994–2001", x:4, y:-1, blurb:"Law-and-order Republican.", aliases:["rudy giuliani","giuliani"]},
  {name:"Michael Bloomberg", country:"United States", dates:"Former Mayor of New York City, 2002–2013", x:1, y:3, blurb:"Independent/moderate, business background.", aliases:["michael bloomberg","bloomberg"]},
  {name:"Lori Lightfoot", country:"United States", dates:"Former Mayor of Chicago, 2019–2023", x:-4, y:2, blurb:"Center-left Democrat.", aliases:["lori lightfoot","lightfoot"]},
// --- More global leaders ---
  {name:"Edi Rama", country:"Albania", dates:"Prime Minister, 2013–present", x:-2, y:2, blurb:"Center-left Socialist Party, EU-accession focused.", aliases:["edi rama","rama"]},
  {name:"Aleksandar Vučić", country:"Serbia", dates:"President, 2017–present", x:2, y:-3, blurb:"Nationalist-populist, increasing media/press-freedom concerns.", aliases:["vucic","aleksandar vucic","aleksandar vučić"]},
  {name:"Zoran Milanović", country:"Croatia", dates:"President, 2020–present", x:-2, y:3, blurb:"Center-left, frequent friction with government.", aliases:["milanovic","zoran milanovic"]},
  {name:"Robert Fico", country:"Slovakia", dates:"Prime Minister, 2023–present", x:-2, y:-3, blurb:"Left-populist, pro-Russia leaning foreign policy.", aliases:["robert fico","fico"]},
  {name:"Petr Fiala", country:"Czech Republic", dates:"Prime Minister, 2021–2025", x:4, y:2, blurb:"Center-right, pro-EU/NATO.", aliases:["petr fiala","fiala"]},
  {name:"Alexander Stubb", country:"Finland", dates:"President, 2024–present", x:3, y:3, blurb:"Center-right liberal.", aliases:["alexander stubb","stubb"]},
  {name:"Frank-Walter Steinmeier", country:"Germany", dates:"President, 2017–present", x:-2, y:4, blurb:"Center-left SPD, largely ceremonial head of state.", aliases:["steinmeier","frank-walter steinmeier"]},
  {name:"Anwar Ibrahim", country:"Malaysia", dates:"Prime Minister, 2022–present", x:-1, y:2, blurb:"Reformist, long-time opposition figure now in power.", aliases:["anwar ibrahim","anwar"]},
  {name:"Yoon Suk-yeol", country:"South Korea", dates:"President, 2022–2025 (impeached)", x:5, y:-3, blurb:"Conservative, impeached after martial-law declaration attempt.", aliases:["yoon suk-yeol","yoon"]},
  {name:"Lee Jae-myung", country:"South Korea", dates:"President, 2025–present", x:-3, y:2, blurb:"Center-left, populist economic policies.", aliases:["lee jae-myung","lee jae myung"]},
  {name:"Kais Saied", country:"Tunisia", dates:"President, 2019–present", x:-1, y:-6, blurb:"Consolidated executive power after 2021 self-coup.", aliases:["kais saied","saied"]},
  {name:"Abdelmadjid Tebboune", country:"Algeria", dates:"President, 2019–present", x:-2, y:-5, blurb:"Military-backed, limited political pluralism.", aliases:["tebboune","abdelmadjid tebboune"]},
  {name:"Mohammed VI", country:"Morocco", dates:"King, 1999–present", x:3, y:-4, blurb:"Constitutional monarch with substantial personal power.", aliases:["mohammed vi","king mohammed vi"]},
  {name:"Nicolas Sarkozy", country:"France", dates:"President, 2007–2012", x:5, y:0, blurb:"Center-right; later convicted of corruption offenses.", aliases:["nicolas sarkozy","sarkozy"], flags:["corruption"]},
  {name:"Park Geun-hye", country:"South Korea", dates:"President, 2013–2017 (impeached)", x:4, y:-2, blurb:"Conservative; impeached and convicted of corruption.", aliases:["park geun-hye","park geun hye"], flags:["corruption"]},
  {name:"Alberto Fujimori", country:"Peru", dates:"President, 1990–2000", x:5, y:-6, blurb:"Authoritarian; later convicted of corruption and human rights crimes.", aliases:["alberto fujimori","fujimori"], flags:["warcrimes","corruption"]},

  // --- UK historical PMs ---
  {name:"Clement Attlee", country:"United Kingdom", dates:"1945–1951", x:-6, y:3, blurb:"Labour, founded NHS and welfare state.", aliases:["clement attlee","attlee"]},
  {name:"Harold Wilson", country:"United Kingdom", dates:"1964–1970, 1974–1976", x:-4, y:3, blurb:"Labour, modernizing centrist.", aliases:["harold wilson","wilson uk"]},
  {name:"Edward Heath", country:"United Kingdom", dates:"1970–1974", x:2, y:2, blurb:"One-nation Conservative, took UK into EEC.", aliases:["edward heath","heath"]},
  {name:"James Callaghan", country:"United Kingdom", dates:"1976–1979", x:-3, y:3, blurb:"Labour, faced Winter of Discontent.", aliases:["james callaghan","callaghan"]},
  {name:"Michael Foot", country:"United Kingdom", dates:"Labour leader 1980–1983", x:-8, y:5, blurb:"Democratic socialist, strong civil-liberties record.", aliases:["michael foot"]},
  {name:"Neil Kinnock", country:"United Kingdom", dates:"Labour leader 1983–1992", x:-5, y:4, blurb:"Center-left, modernized Labour.", aliases:["neil kinnock","kinnock"]},
  {name:"John Smith", country:"United Kingdom", dates:"Labour leader 1992–1994", x:-4, y:4, blurb:"Center-left Labour.", aliases:["john smith uk"]},
  {name:"Stanley Baldwin", country:"United Kingdom", dates:"1923–1924, 1924–1929, 1935–1937", x:3, y:1, blurb:"Conservative, interwar consensus politics.", aliases:["stanley baldwin","baldwin"]},
  {name:"David Lloyd George", country:"United Kingdom", dates:"1916–1922", x:-2, y:2, blurb:"Liberal, WWI leadership, welfare reforms.", aliases:["david lloyd george","lloyd george"]},
  {name:"Anthony Eden", country:"United Kingdom", dates:"1955–1957", x:3, y:1, blurb:"Conservative, resigned over Suez Crisis.", aliases:["anthony eden","eden"]},
  {name:"Alec Douglas-Home", country:"United Kingdom", dates:"1963–1964", x:3, y:2, blurb:"Conservative, brief tenure.", aliases:["alec douglas-home","douglas-home"]},

  // --- Ireland ---
  {name:"Micheál Martin", country:"Ireland", dates:"Taoiseach, 2020–2022, 2024–present", x:0, y:3, blurb:"Centrist Fianna Fáil.", aliases:["micheal martin","martin ireland"]},
  {name:"Simon Harris", country:"Ireland", dates:"Taoiseach, 2024", x:1, y:3, blurb:"Centrist Fine Gael.", aliases:["simon harris"]},
  {name:"Bertie Ahern", country:"Ireland", dates:"Taoiseach, 1997–2008", x:0, y:2, blurb:"Centrist Fianna Fáil, Good Friday Agreement.", aliases:["bertie ahern","ahern"]},
  {name:"Enda Kenny", country:"Ireland", dates:"Taoiseach, 2011–2017", x:1, y:2, blurb:"Center-right Fine Gael, austerity-era leadership.", aliases:["enda kenny","kenny ireland"]},
  {name:"Mary Lou McDonald", country:"Ireland", dates:"Sinn Féin leader, 2018–present", x:-5, y:3, blurb:"Left-wing, Irish reunification focus.", aliases:["mary lou mcdonald","mcdonald"]},

  // --- Austria, Belgium, Portugal, Iceland, Luxembourg ---
  {name:"Karl Nehammer", country:"Austria", dates:"Chancellor, 2021–2024", x:3, y:0, blurb:"Center-right ÖVP.", aliases:["karl nehammer","nehammer"]},
  {name:"Sebastian Kurz", country:"Austria", dates:"Chancellor, 2017–2019, 2020–2021", x:4, y:-1, blurb:"Right-leaning ÖVP, later resigned amid scandal.", aliases:["sebastian kurz","kurz"]},
  {name:"Bart De Wever", country:"Belgium", dates:"Prime Minister, 2025–present", x:5, y:-1, blurb:"Flemish nationalist, right-leaning.", aliases:["bart de wever","de wever"]},
  {name:"Alexander De Croo", country:"Belgium", dates:"Prime Minister, 2020–2025", x:2, y:2, blurb:"Center-right liberal.", aliases:["alexander de croo","de croo"]},
  {name:"António Costa", country:"Portugal", dates:"Prime Minister, 2015–2024", x:-3, y:3, blurb:"Center-left Socialist.", aliases:["antonio costa","costa portugal"]},
  {name:"Luís Montenegro", country:"Portugal", dates:"Prime Minister, 2024–present", x:2, y:2, blurb:"Center-right.", aliases:["luis montenegro","montenegro"]},
  {name:"Katrín Jakobsdóttir", country:"Iceland", dates:"Prime Minister, 2017–2024", x:-6, y:5, blurb:"Left-Green, coalition leader.", aliases:["katrin jakobsdottir","jakobsdottir"]},

  // --- Africa ---
  {name:"Bassirou Diomaye Faye", country:"Senegal", dates:"President, 2024–present", x:-5, y:2, blurb:"Left-leaning reformist, youngest elected African president.", aliases:["bassirou diomaye faye","diomaye faye"]},
  {name:"Macky Sall", country:"Senegal", dates:"President, 2012–2024", x:-1, y:0, blurb:"Center-left, controversial third-term attempt.", aliases:["macky sall","sall"]},
  {name:"Alassane Ouattara", country:"Ivory Coast", dates:"President, 2011–present", x:2, y:-3, blurb:"Market-friendly, extended tenure controversy.", aliases:["alassane ouattara","ouattara"]},
  {name:"Assimi Goïta", country:"Mali", dates:"President, 2021–present (coup leader)", x:-1, y:-8, blurb:"Military junta leader after coups.", aliases:["assimi goita","goita"]},
  {name:"Ibrahim Traoré", country:"Burkina Faso", dates:"President, 2022–present (coup leader)", x:-3, y:-8, blurb:"Military junta leader, anti-Western rhetoric.", aliases:["ibrahim traore","traore"]},
  {name:"Abdel Fattah al-Burhan", country:"Sudan", dates:"Leader, 2019–present", x:1, y:-8, blurb:"Military leader amid ongoing civil war.", aliases:["al-burhan","burhan"]},
  {name:"João Lourenço", country:"Angola", dates:"President, 2017–present", x:-2, y:-3, blurb:"MPLA, limited political pluralism.", aliases:["joao lourenco","lourenco"]},
  {name:"José Eduardo dos Santos", country:"Angola", dates:"President, 1979–2017", x:-3, y:-6, blurb:"Long one-party MPLA rule.", aliases:["jose eduardo dos santos","dos santos"]},
  {name:"Filipe Nyusi", country:"Mozambique", dates:"President, 2015–2025", x:-3, y:-4, blurb:"FRELIMO, one-party dominance.", aliases:["filipe nyusi","nyusi"]},
  {name:"Mokgweetsi Masisi", country:"Botswana", dates:"President, 2018–2024", x:1, y:2, blurb:"Center-right, stable democracy.", aliases:["mokgweetsi masisi","masisi"]},
  {name:"Hage Geingob", country:"Namibia", dates:"President, 2015–2024", x:-3, y:2, blurb:"SWAPO, center-left.", aliases:["hage geingob","geingob"]},
  {name:"Julius Malema", country:"South Africa", dates:"EFF leader, 2013–present", x:-8, y:-1, blurb:"Radical left, land-reform focus.", aliases:["julius malema","malema"]},
  {name:"Helen Zille", country:"South Africa", dates:"Former DA leader", x:4, y:3, blurb:"Center-right Democratic Alliance.", aliases:["helen zille","zille"]},

  // --- Asia further ---
  {name:"Jiang Zemin", country:"China", dates:"1993–2003", x:-4, y:-7, blurb:"Market reforms continued, one-party control.", aliases:["jiang zemin","jiang"]},
  {name:"Zhou Enlai", country:"China", dates:"Premier, 1949–1976", x:-6, y:-6, blurb:"Founding Communist premier.", aliases:["zhou enlai","zhou"]},
  {name:"Li Qiang", country:"China", dates:"Premier, 2023–present", x:-4, y:-7, blurb:"State-directed economy, one-party rule.", aliases:["li qiang"]},
  {name:"Nguyễn Phú Trọng", country:"Vietnam", dates:"Party leader, 2011–2024", x:-6, y:-6, blurb:"One-party communist rule.", aliases:["nguyen phu trong","trong"]},
  {name:"Tô Lâm", country:"Vietnam", dates:"Party leader, 2024–present", x:-6, y:-6, blurb:"One-party communist rule.", aliases:["to lam"]},
  {name:"Tsai Ing-wen", country:"Taiwan", dates:"President, 2016–2024", x:-2, y:4, blurb:"Center-left DPP, pro-democratic norms.", aliases:["tsai ing-wen","tsai"]},
  {name:"Lai Ching-te", country:"Taiwan", dates:"President, 2024–present", x:-2, y:4, blurb:"Center-left DPP.", aliases:["lai ching-te","lai"]},
  {name:"Ma Ying-jeou", country:"Taiwan", dates:"President, 2008–2016", x:2, y:3, blurb:"Center-right KMT, closer China ties.", aliases:["ma ying-jeou","ma"]},
  {name:"Nursultan Nazarbayev", country:"Kazakhstan", dates:"President, 1991–2019", x:1, y:-7, blurb:"Long-ruling post-Soviet strongman.", aliases:["nursultan nazarbayev","nazarbayev"]},
  {name:"Kassym-Jomart Tokayev", country:"Kazakhstan", dates:"President, 2019–present", x:1, y:-6, blurb:"Continued authoritarian governance.", aliases:["kassym-jomart tokayev","tokayev"]},
  {name:"Hamid Karzai", country:"Afghanistan", dates:"President, 2001–2014", x:1, y:-2, blurb:"US-backed transitional leader.", aliases:["hamid karzai","karzai"]},
  {name:"Ashraf Ghani", country:"Afghanistan", dates:"President, 2014–2021", x:1, y:-1, blurb:"Technocratic, government collapsed 2021.", aliases:["ashraf ghani","ghani"]},

  // --- Middle East further ---
  {name:"Nouri al-Maliki", country:"Iraq", dates:"Prime Minister, 2006–2014", x:-2, y:-5, blurb:"Sectarian-leaning, centralized power.", aliases:["nouri al-maliki","maliki"]},
  {name:"Mustafa al-Kadhimi", country:"Iraq", dates:"Prime Minister, 2020–2022", x:0, y:-2, blurb:"Technocratic transitional leader.", aliases:["mustafa al-kadhimi","kadhimi"]},
  {name:"Tamim bin Hamad Al Thani", country:"Qatar", dates:"Emir, 2013–present", x:4, y:-5, blurb:"Absolute monarch, market-driven diversification.", aliases:["tamim","emir of qatar"]},
  {name:"Nayib Bukele", country:"El Salvador", dates:"President, 2019–present", x:2, y:-7, blurb:"Populist, mass-incarceration security crackdown.", aliases:["nayib bukele","bukele"]},
  {name:"Miguel Díaz-Canel", country:"Cuba", dates:"President, 2018–present", x:-8, y:-7, blurb:"Continued one-party communist rule.", aliases:["miguel diaz-canel","diaz-canel"]},

  // --- More US ---
  {name:"Nancy Pelosi", country:"United States", dates:"House Speaker, 2007–2011, 2019–2023", x:-4, y:4, blurb:"Center-left Democrat, longtime House leader.", aliases:["nancy pelosi","pelosi"]},
  {name:"Mike Johnson", country:"United States", dates:"House Speaker, 2023–present", x:6, y:-2, blurb:"Conservative Republican.", aliases:["mike johnson"]},
  {name:"Kevin McCarthy", country:"United States", dates:"House Speaker, 2023", x:5, y:0, blurb:"Establishment Republican.", aliases:["kevin mccarthy","mccarthy"]},
  {name:"Newt Gingrich", country:"United States", dates:"House Speaker, 1995–1999", x:6, y:0, blurb:"Conservative Republican revolution architect.", aliases:["newt gingrich","gingrich"]},
  {name:"Al Gore", country:"United States", dates:"VP 1993–2001", x:-4, y:4, blurb:"Center-left Democrat, climate advocacy.", aliases:["al gore","gore"]},
  {name:"Dick Cheney", country:"United States", dates:"VP 2001–2009", x:6, y:0, blurb:"Hawkish conservative Republican.", aliases:["dick cheney","cheney"]},
  {name:"Mike Pence", country:"United States", dates:"VP 2017–2021", x:6, y:2, blurb:"Social conservative Republican.", aliases:["mike pence","pence"]},
  {name:"Gavin Newsom", country:"United States", dates:"Governor of California, 2019–present", x:-5, y:4, blurb:"Progressive Democrat governor.", aliases:["gavin newsom","newsom"]},
  {name:"Ron DeSantis", country:"United States", dates:"Governor of Florida, 2019–present", x:7, y:-2, blurb:"Right-wing Republican governor.", aliases:["ron desantis","desantis"]},
  {name:"Greg Abbott", country:"United States", dates:"Governor of Texas, 2015–present", x:6, y:-1, blurb:"Conservative Republican governor.", aliases:["greg abbott","abbott texas"]},
  {name:"Kathy Hochul", country:"United States", dates:"Governor of New York, 2021–present", x:-3, y:3, blurb:"Center-left Democrat governor.", aliases:["kathy hochul","hochul"]},
  {name:"J.B. Pritzker", country:"United States", dates:"Governor of Illinois, 2019–present", x:-4, y:4, blurb:"Progressive Democrat governor.", aliases:["jb pritzker","pritzker"]},
  {name:"Alexandria Ocasio-Cortez", country:"United States", dates:"Representative (NY), 2019–present", x:-8, y:6, blurb:"Progressive Democrat, strong civil-liberties positions.", aliases:["aoc","alexandria ocasio-cortez","ocasio-cortez"]},
  {name:"Marjorie Taylor Greene", country:"United States", dates:"Representative (GA), 2021–present", x:8, y:-4, blurb:"Hard-right populist Republican.", aliases:["marjorie taylor greene","mtg"]},
  {name:"Kevin de León", country:"United States", dates:"California state legislator", x:-5, y:3, blurb:"Progressive Democrat.", aliases:["kevin de leon"]},
  {name:"Hillary Clinton", country:"United States", dates:"Secretary of State, 2009–2013", x:-2, y:4, blurb:"Center-left Democrat.", aliases:["hillary clinton"]},
  {name:"John McCain", country:"United States", dates:"Senator (AZ), 1987–2018", x:4, y:2, blurb:"Establishment Republican, maverick reputation.", aliases:["john mccain","mccain"]},
  {name:"Mitt Romney", country:"United States", dates:"Senator (UT), 2019–2025", x:3, y:2, blurb:"Establishment moderate Republican.", aliases:["mitt romney","romney"]},
  {name:"Paul Ryan", country:"United States", dates:"House Speaker, 2015–2019", x:6, y:2, blurb:"Fiscally conservative Republican.", aliases:["paul ryan","ryan"]},
  {name:"Nikki Haley", country:"United States", dates:"UN Ambassador, 2017–2018", x:5, y:2, blurb:"Establishment conservative Republican.", aliases:["nikki haley","haley"]},
  {name:"Vivek Ramaswamy", country:"United States", dates:"2024 presidential candidate", x:6, y:0, blurb:"Right-wing entrepreneur-politician.", aliases:["vivek ramaswamy","ramaswamy"]},
  {name:"Andrew Yang", country:"United States", dates:"2020 presidential candidate", x:-2, y:5, blurb:"Centrist, universal-basic-income focus.", aliases:["andrew yang","yang"]},
  {name:"Pete Buttigieg", country:"United States", dates:"Transportation Secretary, 2021–2025", x:-3, y:4, blurb:"Center-left Democrat.", aliases:["pete buttigieg","buttigieg"]},

  // --- More Caribbean / Central America / Pacific ---
  {name:"Mia Mottley", country:"Barbados", dates:"Prime Minister, 2018–present", x:-4, y:3, blurb:"Center-left, climate-finance advocate.", aliases:["mia mottley","mottley"]},
  {name:"Andrew Holness", country:"Jamaica", dates:"Prime Minister, 2016–present", x:2, y:2, blurb:"Center-right JLP.", aliases:["andrew holness","holness"]},
  {name:"Keith Rowley", country:"Trinidad and Tobago", dates:"Prime Minister, 2015–2025", x:1, y:2, blurb:"Center-right PNM.", aliases:["keith rowley","rowley"]},
  {name:"Xiomara Castro", country:"Honduras", dates:"President, 2022–present", x:-6, y:2, blurb:"Left-wing, first female president.", aliases:["xiomara castro","castro honduras"]},
  {name:"Rodrigo Chaves", country:"Costa Rica", dates:"President, 2022–present", x:3, y:0, blurb:"Populist-technocrat.", aliases:["rodrigo chaves","chaves"]},
  {name:"José Raúl Mulino", country:"Panama", dates:"President, 2024–present", x:2, y:2, blurb:"Center-right.", aliases:["jose raul mulino","mulino"]},
  {name:"Bernardo Arévalo", country:"Guatemala", dates:"President, 2024–present", x:-3, y:4, blurb:"Anti-corruption reformist.", aliases:["bernardo arevalo","arevalo"]},
  {name:"Frank Bainimarama", country:"Fiji", dates:"Prime Minister, 2007–2022", x:0, y:-5, blurb:"Former coup leader turned elected PM.", aliases:["frank bainimarama","bainimarama"]},
  {name:"James Marape", country:"Papua New Guinea", dates:"Prime Minister, 2019–present", x:0, y:1, blurb:"Centrist, resource-economy focus.", aliases:["james marape","marape"]},

  // --- More global historical figures ---
  {name:"Otto von Bismarck", country:"Germany", dates:"Chancellor, 1871–1890", x:3, y:-3, blurb:"Conservative unifier, welfare-state pioneer.", aliases:["otto von bismarck","bismarck"]},
  {name:"Napoleon Bonaparte", country:"France", dates:"1799–1815", x:1, y:-6, blurb:"Military dictator, centralized authoritarian rule.", aliases:["napoleon bonaparte","napoleon"]},
  {name:"Vladimir Lenin", country:"Soviet Union", dates:"1917–1924", x:-9, y:-8, blurb:"Bolshevik revolutionary, one-party state founder.", aliases:["vladimir lenin","lenin"]},
  {name:"Leon Trotsky", country:"Soviet Union", dates:"Revolutionary leader", x:-9, y:-4, blurb:"Marxist revolutionary, later exiled and assassinated.", aliases:["leon trotsky","trotsky"]},
  {name:"Kwame Nkrumah", country:"Ghana", dates:"1957–1966", x:-6, y:-3, blurb:"Pan-Africanist founding leader, later one-party rule.", aliases:["kwame nkrumah","nkrumah"]},
  {name:"Patrice Lumumba", country:"DR Congo", dates:"1960", blurb:"Independence leader, deposed and killed.", x:-5, y:2, aliases:["patrice lumumba","lumumba"]},
  {name:"Haile Selassie", country:"Ethiopia", dates:"1930–1974", x:2, y:-6, blurb:"Monarch, deposed by military coup.", aliases:["haile selassie"]},
  {name:"Sukarno", country:"Indonesia", dates:"1945–1967", x:-4, y:-4, blurb:"Independence founder, later authoritarian \"Guided Democracy.\"", aliases:["sukarno"]},
  {name:"Suharto", country:"Indonesia", dates:"1967–1998", x:2, y:-8, blurb:"Long military-backed authoritarian rule.", aliases:["suharto"]},
  {name:"Ferdinand Marcos Sr", country:"Philippines", dates:"1965–1986", x:2, y:-8, blurb:"Martial-law dictatorship, later ousted.", aliases:["ferdinand marcos sr","marcos sr"]},
  {name:"Corazon Aquino", country:"Philippines", dates:"1986–1992", x:-1, y:5, blurb:"Restored democracy after People Power Revolution.", aliases:["corazon aquino","cory aquino"]},
  {name:"Park Chung-hee", country:"South Korea", dates:"1961–1979", x:3, y:-7, blurb:"Authoritarian developmental state.", aliases:["park chung-hee","park chung hee"]},
  {name:"Chiang Kai-shek", country:"Taiwan/China", dates:"1928–1975", x:4, y:-8, blurb:"Nationalist authoritarian leader.", aliases:["chiang kai-shek","chiang kai shek"]},
  {name:"Getúlio Vargas", country:"Brazil", dates:"1930–1945, 1951–1954", x:-3, y:-4, blurb:"Populist-authoritarian corporatist rule.", aliases:["getulio vargas","vargas"]},
  {name:"Juan Perón", country:"Argentina", dates:"1946–1955, 1973–1974", x:-2, y:-4, blurb:"Populist corporatist, foundational Peronism.", aliases:["juan peron","peron"]},
  {name:"Eva Perón", country:"Argentina", dates:"First Lady, 1946–1952", x:-3, y:-1, blurb:"Populist icon, social-welfare advocate.", aliases:["eva peron","evita"]},
  {name:"Salvador Allende", country:"Chile", dates:"1970–1973", x:-8, y:3, blurb:"Democratic socialist, overthrown by coup.", aliases:["salvador allende","allende"]},
  {name:"Lech Wałęsa", country:"Poland", dates:"1990–1995", x:1, y:4, blurb:"Solidarity movement leader, transitioned to democracy.", aliases:["lech walesa","walesa"]},
  {name:"Václav Havel", country:"Czech Republic", dates:"1993–2003", x:-2, y:6, blurb:"Dissident playwright, strong civil-liberties record.", aliases:["vaclav havel","havel"]},

  // --- More UAE/Gulf/Africa small states ---
  {name:"Sheikh Khalifa bin Zayed", country:"UAE", dates:"President, 2004–2022", x:5, y:-6, blurb:"Absolute rule, market economy.", aliases:["khalifa bin zayed"]},
  {name:"Sheikh Sabah Al-Ahmad Al-Jaber Al-Sabah", country:"Kuwait", dates:"Emir, 2006–2020", x:4, y:-3, blurb:"Constitutional monarchy with elected parliament.", aliases:["sheikh sabah","sabah kuwait"]},
  {name:"Hamad bin Isa Al Khalifa", country:"Bahrain", dates:"King, 2002–present", x:5, y:-6, blurb:"Absolute monarchy, limited pluralism.", aliases:["hamad bin isa","king of bahrain"]},
  {name:"Qaboos bin Said", country:"Oman", dates:"Sultan, 1970–2020", x:3, y:-4, blurb:"Modernizing absolute monarch.", aliases:["qaboos bin said","qaboos"]},

  // --- More Nordic/Baltic ---
  {name:"Kristrún Frostadóttir", country:"Iceland", dates:"Prime Minister, 2024–present", x:-4, y:4, blurb:"Center-left Social Democrat.", aliases:["kristrun frostadottir","frostadottir"]},
  {name:"Kaja Kallas", country:"Estonia", dates:"Prime Minister, 2021–2024", x:3, y:3, blurb:"Center-right liberal, hawkish on Russia.", aliases:["kaja kallas","kallas"]},
  {name:"Ingrida Šimonytė", country:"Lithuania", dates:"Prime Minister, 2020–2024", x:3, y:3, blurb:"Center-right liberal-conservative.", aliases:["ingrida simonyte","simonyte"]},
  {name:"Krišjānis Kariņš", country:"Latvia", dates:"Prime Minister, 2019–2023", x:2, y:3, blurb:"Center-right liberal.", aliases:["krisjanis karins","karins"]},

  // --- More South Asia ---
  {name:"Zulfikar Ali Bhutto", country:"Pakistan", dates:"1971–1977", x:-4, y:-3, blurb:"Populist democratic-socialist, later executed.", aliases:["zulfikar ali bhutto","zulfikar bhutto"]},
  {name:"Benazir Bhutto", country:"Pakistan", dates:"1988–1990, 1993–1996", x:-3, y:1, blurb:"Center-left, first female PM of a Muslim-majority nation.", aliases:["benazir bhutto","benazir"]},
  {name:"Shehbaz Sharif", country:"Pakistan", dates:"Prime Minister, 2022–present", x:2, y:0, blurb:"Center-right, business-friendly.", aliases:["shehbaz sharif","shehbaz"]},
  {name:"Nawaz Sharif", country:"Pakistan", dates:"1990–1993, 1997–1999, 2013–2017", x:3, y:-1, blurb:"Center-right, market-friendly.", aliases:["nawaz sharif","nawaz"]},
  {name:"Ranil Wickremesinghe", country:"Sri Lanka", dates:"President, 2022–2024", x:2, y:1, blurb:"Center-right, crisis-era leadership.", aliases:["ranil wickremesinghe","wickremesinghe"]},
  {name:"Anura Kumara Dissanayake", country:"Sri Lanka", dates:"President, 2024–present", x:-6, y:2, blurb:"Left-wing, anti-corruption platform.", aliases:["anura kumara dissanayake","dissanayake"]},

  // --- More cabinet-level/opposition Europe ---
  {name:"Sahra Wagenknecht", country:"Germany", dates:"BSW party leader", x:-5, y:-3, blurb:"Left-populist, socially conservative positions.", aliases:["sahra wagenknecht","wagenknecht"]},
  {name:"Alice Weidel", country:"Germany", dates:"AfD co-leader", x:7, y:-4, blurb:"Right-wing nationalist AfD.", aliases:["alice weidel","weidel"]},
  {name:"Robert Habeck", country:"Germany", dates:"Vice Chancellor, 2021–2025", x:-4, y:4, blurb:"Green Party, climate-policy focus.", aliases:["robert habeck","habeck"]},
  {name:"Christian Lindner", country:"Germany", dates:"Finance Minister, 2021–2024", x:4, y:3, blurb:"Free-market liberal FDP.", aliases:["christian lindner","lindner"]},

  // --- More African leaders ---
  {name:"Nelson Chamisa", country:"Zimbabwe", dates:"Opposition leader (CCC)", x:-2, y:4, blurb:"Opposition figure challenging ZANU-PF.", aliases:["nelson chamisa","chamisa"]},
  {name:"Raila Odinga", country:"Kenya", dates:"Longtime opposition leader", x:-3, y:2, blurb:"Center-left, repeated presidential candidate.", aliases:["raila odinga","odinga"]},
  {name:"Atiku Abubakar", country:"Nigeria", dates:"Former VP, opposition figure", x:2, y:1, blurb:"Center-right, business background.", aliases:["atiku abubakar","atiku"]},
  {name:"Peter Obi", country:"Nigeria", dates:"2023 presidential candidate", x:-2, y:3, blurb:"Reformist, anti-establishment appeal.", aliases:["peter obi","obi"]},

  // --- More Middle East ---
  {name:"Ebrahim Raisi", country:"Iran", dates:"President, 2021–2024", x:-2, y:-8, blurb:"Hardline conservative cleric.", aliases:["ebrahim raisi","raisi"]},
  {name:"Masoud Pezeshkian", country:"Iran", dates:"President, 2024–present", x:1, y:-6, blurb:"Relatively moderate reformist within theocratic system.", aliases:["masoud pezeshkian","pezeshkian"]},
  {name:"Ahmed al-Sharaa", country:"Syria", dates:"Transitional leader, 2024–present", x:1, y:-5, blurb:"Former rebel commander, now transitional president.", aliases:["ahmed al-sharaa","al-sharaa","al-jolani"]},

  // --- More US historical ---
  {name:"Lyndon B. Johnson", country:"United States", dates:"1963–1969", x:-4, y:2, blurb:"Great Society reforms, Civil Rights Act.", aliases:["lyndon johnson","lbj"]},
  {name:"Dwight D. Eisenhower", country:"United States", dates:"1953–1961", x:3, y:2, blurb:"Moderate Republican, interstate highway system.", aliases:["dwight eisenhower","eisenhower"]},
  {name:"Harry Truman", country:"United States", dates:"1945–1953", x:-3, y:2, blurb:"Democrat, Cold War containment policy.", aliases:["harry truman","truman"]},
  {name:"Woodrow Wilson", country:"United States", dates:"1913–1921", x:-2, y:0, blurb:"Progressive-era Democrat, WWI leadership.", aliases:["woodrow wilson","wilson us"]},
  {name:"Theodore Roosevelt", country:"United States", dates:"1901–1909", x:1, y:2, blurb:"Progressive Republican, trust-busting reforms.", aliases:["theodore roosevelt","teddy roosevelt"]},
  {name:"Andrew Jackson", country:"United States", dates:"1829–1837", x:-1, y:-5, blurb:"Populist Democrat, expanded executive power controversially.", aliases:["andrew jackson","jackson us"]},
  {name:"Thomas Jefferson", country:"United States", dates:"1801–1809", x:-2, y:3, blurb:"Founding father, limited-government Democratic-Republican.", aliases:["thomas jefferson","jefferson"]},
  {name:"George Washington", country:"United States", dates:"1789–1797", x:1, y:2, blurb:"Founding president, set precedent for peaceful transfer of power.", aliases:["george washington","washington us"]},

  // --- More UK party figures ---
  {name:"Nick Clegg", country:"United Kingdom", dates:"Deputy PM, 2010–2015", x:-1, y:4, blurb:"Centrist Liberal Democrat.", aliases:["nick clegg","clegg"]},
  {name:"Tim Farron", country:"United Kingdom", dates:"Lib Dem leader, 2015–2017", x:-2, y:4, blurb:"Centrist liberal.", aliases:["tim farron","farron"]},
  {name:"Alex Salmond", country:"United Kingdom", dates:"Scottish First Minister, 2007–2014", x:-3, y:1, blurb:"Center-left SNP, Scottish independence campaigner.", aliases:["alex salmond","salmond"]},
  {name:"Ruth Davidson", country:"United Kingdom", dates:"Scottish Conservative leader", x:4, y:2, blurb:"Center-right, pro-Union Conservative.", aliases:["ruth davidson","davidson"]},
  {name:"Arlene Foster", country:"United Kingdom", dates:"NI First Minister, 2016–2021", x:5, y:-2, blurb:"DUP, socially conservative unionist.", aliases:["arlene foster","foster"]},
  {name:"Michelle O'Neill", country:"United Kingdom", dates:"NI First Minister, 2024–present", x:-4, y:2, blurb:"Sinn Féin, Irish reunification focus.", aliases:["michelle o'neill","oneill"]}
];
