// Each entry: name, country, x (-10 far-left … 10 far-right, political lean of reporting/editorial),
// y (-10 sensationalist/opinion-heavy … 10 rigorous fact-based reporting), blurb, aliases
const MEDIA_OUTLETS = [
  // --- US ---
  {name:"Reuters", country:"United States/UK", x:0, y:7, blurb:"Wire service, minimal editorializing, high factual standards.", aliases:["reuters"]},
  {name:"Associated Press", country:"United States", x:-1, y:6.5, blurb:"Wire service, style guide emphasizes neutrality.", aliases:["ap","associated press","ap news"]},
  {name:"The Wall Street Journal", country:"United States", x:2, y:5.5, blurb:"News desk fairly centrist; opinion page leans right.", aliases:["wsj","wall street journal"]},
  {name:"Bloomberg", country:"United States", x:1, y:5, blurb:"Business-focused, data-driven reporting.", aliases:["bloomberg"]},
  {name:"The New York Times", country:"United States", x:-4, y:4.5, blurb:"Left-leaning editorial stance, strong investigative desk.", aliases:["nyt","new york times","the times"]},
  {name:"The Washington Post", country:"United States", x:-4, y:4.5, blurb:"Left-leaning editorial stance, investigative reporting.", aliases:["wapo","washington post"]},
  {name:"NPR", country:"United States", x:-4, y:4, blurb:"Public radio, left-leaning framing, careful sourcing.", aliases:["npr","national public radio"]},
  {name:"PBS NewsHour", country:"United States", x:-2, y:5, blurb:"Public broadcaster, measured tone.", aliases:["pbs","pbs newshour"]},
  {name:"The Atlantic", country:"United States", x:-4, y:3.5, blurb:"Left-leaning long-form journalism and opinion.", aliases:["atlantic","the atlantic"]},
  {name:"Politico", country:"United States", x:-2, y:3.5, blurb:"Insider political coverage, slight left lean.", aliases:["politico"]},
  {name:"The Hill", country:"United States", x:0, y:3.5, blurb:"Congress-focused, relatively centrist.", aliases:["the hill"]},
  {name:"USA Today", country:"United States", x:-1, y:3, blurb:"General-interest, centrist framing.", aliases:["usa today"]},
  {name:"ABC News", country:"United States", x:-2, y:3, blurb:"Broadcast network, mild left lean.", aliases:["abc news","abc"]},
  {name:"CBS News", country:"United States", x:-2, y:3, blurb:"Broadcast network, mild left lean.", aliases:["cbs news","cbs"]},
  {name:"NBC News", country:"United States", x:-3, y:3, blurb:"Broadcast network, mild-moderate left lean.", aliases:["nbc news","nbc"]},
  {name:"National Review", country:"United States", x:6, y:3, blurb:"Conservative opinion/commentary magazine.", aliases:["national review"]},
  {name:"CNN", country:"United States", x:-4, y:2, blurb:"Cable news, left-leaning framing, more opinion content than wire services.", aliases:["cnn"]},
  {name:"Vox", country:"United States", x:-6, y:1.5, blurb:"Explanatory journalism, openly left-leaning.", aliases:["vox"]},
  {name:"HuffPost", country:"United States", x:-6, y:0, blurb:"Left-leaning digital news and opinion.", aliases:["huffpost","huffington post"]},
  {name:"MSNBC", country:"United States", x:-7, y:-3, blurb:"Cable news, strongly left-leaning opinion-heavy programming.", aliases:["msnbc"]},
  {name:"Fox News", country:"United States", x:7, y:-3, blurb:"Cable news, strongly right-leaning opinion-heavy programming.", aliases:["fox news","fox"]},
  {name:"Fox Business", country:"United States", x:6, y:-1, blurb:"Business-focused, right-leaning framing.", aliases:["fox business"]},
  {name:"The Daily Wire", country:"United States", x:8, y:-4, blurb:"Conservative commentary and opinion outlet.", aliases:["daily wire","the daily wire"]},
  {name:"The Federalist", country:"United States", x:8, y:-5, blurb:"Conservative opinion outlet.", aliases:["federalist","the federalist"]},
  {name:"Breitbart News", country:"United States", x:9, y:-7, blurb:"Right-wing populist, opinion-heavy, contested factual record.", aliases:["breitbart"]},
  {name:"Newsmax", country:"United States", x:8, y:-6, blurb:"Right-leaning cable news, opinion-heavy.", aliases:["newsmax"]},
  {name:"One America News", country:"United States", x:9, y:-8, blurb:"Far-right cable news, low fact-checking standards.", aliases:["oan","oann","one america news"]},
  {name:"The Epoch Times", country:"United States", x:7, y:-6, blurb:"Right-leaning, associated with Falun Gong movement.", aliases:["epoch times","the epoch times"]},

  // --- UK ---
  {name:"BBC News", country:"United Kingdom", x:-1, y:4.5, blurb:"Public broadcaster, mandated impartiality standard.", aliases:["bbc","bbc news"]},
  {name:"The Economist", country:"United Kingdom", x:2, y:6, blurb:"Centrist-liberal, rigorous data-driven analysis.", aliases:["economist","the economist"]},
  {name:"Financial Times", country:"United Kingdom", x:2, y:6, blurb:"Business-focused, high factual standards.", aliases:["ft","financial times"]},
  {name:"Sky News", country:"United Kingdom", x:1, y:3.5, blurb:"Broadcast news, relatively centrist.", aliases:["sky news"]},
  {name:"The Times", country:"United Kingdom", x:3, y:4, blurb:"Center-right broadsheet.", aliases:["the times uk","times uk"]},
  {name:"The Guardian", country:"United Kingdom", x:-6, y:2.5, blurb:"Left-leaning broadsheet, strong investigative desk.", aliases:["guardian","the guardian"]},
  {name:"The Independent", country:"United Kingdom", x:-4, y:1.5, blurb:"Left-leaning digital outlet.", aliases:["independent","the independent"]},
  {name:"The Telegraph", country:"United Kingdom", x:6, y:2, blurb:"Center-right broadsheet.", aliases:["telegraph","the telegraph"]},
  {name:"Daily Mail", country:"United Kingdom", x:6, y:-4, blurb:"Right-leaning tabloid, sensationalist headlines.", aliases:["daily mail","mail online"]},
  {name:"The Sun", country:"United Kingdom", x:5, y:-6, blurb:"Right-leaning tabloid, highly sensationalist.", aliases:["the sun"]},
  {name:"The Mirror", country:"United Kingdom", x:-4, y:-3, blurb:"Left-leaning tabloid, sensationalist tendencies.", aliases:["mirror","the mirror","daily mirror"]},
  {name:"GB News", country:"United Kingdom", x:8, y:-6, blurb:"Right-leaning cable news, opinion-heavy.", aliases:["gb news"]},
  {name:"Metro", country:"United Kingdom", x:-1, y:1, blurb:"Free daily, light political framing.", aliases:["metro","metro uk"]},

  // --- international ---
  {name:"Al Jazeera", country:"Qatar", x:-2, y:2, blurb:"State-funded, strong Middle East coverage.", aliases:["al jazeera","aljazeera"]},
  {name:"Deutsche Welle", country:"Germany", x:-1, y:4, blurb:"German public international broadcaster.", aliases:["dw","deutsche welle"]},
  {name:"France 24", country:"France", x:-1, y:3.5, blurb:"French state international broadcaster.", aliases:["france 24","france24"]},
  {name:"Le Monde", country:"France", x:-3, y:4, blurb:"Center-left French paper of record.", aliases:["le monde"]},
  {name:"Der Spiegel", country:"Germany", x:-3, y:3.5, blurb:"Center-left German newsmagazine.", aliases:["der spiegel","spiegel"]},
  {name:"RT (Russia Today)", country:"Russia", x:-1, y:-8, blurb:"Russian state media, widely assessed as propaganda outlet.", aliases:["rt","russia today"]},
  {name:"Xinhua", country:"China", x:-3, y:-8, blurb:"Chinese state news agency.", aliases:["xinhua"]},
  {name:"Global Times", country:"China", x:-2, y:-7, blurb:"Chinese state-run nationalist tabloid.", aliases:["global times"]},
  {name:"CBC News", country:"Canada", x:-3, y:4, blurb:"Canadian public broadcaster, left-of-center framing.", aliases:["cbc","cbc news"]},
  {name:"ABC (Australia)", country:"Australia", x:-2, y:4, blurb:"Australian public broadcaster.", aliases:["abc australia"]}
];
