// Each entry: name, country, x (-10 far-left … 10 far-right, political lean of reporting/editorial),
// y (-10 sensationalist/opinion-heavy … 10 rigorous fact-based reporting), blurb, aliases
const MEDIA_OUTLETS = [
  // --- US ---
  {name:"Reuters", country:"United States/UK", x:0, y:7, blurb:"Wire service, minimal editorializing, high factual standards.", aliases:["reuters"]},
  {name:"Associated Press", country:"United States", x:-1, y:6.5, blurb:"Wire service, style guide emphasizes neutrality.", aliases:["ap","associated press","ap news"]},
  {name:"The Wall Street Journal", country:"United States", x:2, y:5.5, blurb:"News desk fairly centrist; opinion page leans right.", aliases:["wsj","wall street journal"]},
  {name:"Bloomberg", country:"United States", x:1, y:5, blurb:"Business-focused, data-driven reporting.", aliases:["bloomberg"]},
  {name:"The New York Times", country:"United States", x:-4, y:4.5, blurb:"Left-leaning editorial stance, strong investigative desk.", aliases:["nyt","new york times","the times"]},
  {name:"The Washington Post", country:"United States", x:-4, y:4.5, blurb:"Left-leaning editorial stance, investigative reporting.", aliases:["wapo","washington post"]},
  {name:"NPR", country:"United States", x:-4, y:4, blurb:"Public radio, left-leaning framing, careful sourcing.", aliases:["npr","national public radio"]},
  {name:"PBS NewsHour", country:"United States", x:-2, y:5, blurb:"Public broadcaster, measured tone.", aliases:["pbs","pbs newshour"]},
  {name:"The Atlantic", country:"United States", x:-4, y:3.5, blurb:"Left-leaning long-form journalism and opinion.", aliases:["atlantic","the atlantic"]},
  {name:"Politico", country:"United States", x:-2, y:3.5, blurb:"Insider political coverage, slight left lean.", aliases:["politico"]},
  {name:"The Hill", country:"United States", x:0, y:3.5, blurb:"Congress-focused, relatively centrist.", aliases:["the hill"]},
  {name:"USA Today", country:"United States", x:-1, y:3, blurb:"General-interest, centrist framing.", aliases:["usa today"]},
  {name:"ABC News", country:"United States", x:-2, y:3, blurb:"Broadcast network, mild left lean.", aliases:["abc news","abc"]},
  {name:"CBS News", country:"United States", x:-2, y:3, blurb:"Broadcast network, mild left lean.", aliases:["cbs news","cbs"]},
  {name:"NBC News", country:"United States", x:-3, y:3, blurb:"Broadcast network, mild-moderate left lean.", aliases:["nbc news","nbc"]},
  {name:"National Review", country:"United States", x:6, y:3, blurb:"Conservative opinion/commentary magazine.", aliases:["national review"]},
  {name:"CNN", country:"United States", x:-4, y:2, blurb:"Cable news, left-leaning framing, more opinion content than wire services.", aliases:["cnn"]},
  {name:"Vox", country:"United States", x:-6, y:1.5, blurb:"Explanatory journalism, openly left-leaning.", aliases:["vox"]},
  {name:"HuffPost", country:"United States", x:-6, y:0, blurb:"Left-leaning digital news and opinion.", aliases:["huffpost","huffington post"]},
  {name:"MSNBC", country:"United States", x:-7, y:-3, blurb:"Cable news, strongly left-leaning opinion-heavy programming.", aliases:["msnbc"]},
  {name:"Fox News", country:"United States", x:7, y:-3, blurb:"Cable news, strongly right-leaning opinion-heavy programming.", aliases:["fox news","fox"]},
  {name:"Fox Business", country:"United States", x:6, y:-1, blurb:"Business-focused, right-leaning framing.", aliases:["fox business"]},
  {name:"The Daily Wire", country:"United States", x:8, y:-4, blurb:"Conservative commentary and opinion outlet.", aliases:["daily wire","the daily wire"]},
  {name:"The Federalist", country:"United States", x:8, y:-5, blurb:"Conservative opinion outlet.", aliases:["federalist","the federalist"]},
  {name:"Breitbart News", country:"United States", x:9, y:-7, blurb:"Right-wing populist, opinion-heavy, contested factual record.", aliases:["breitbart"]},
  {name:"Newsmax", country:"United States", x:8, y:-6, blurb:"Right-leaning cable news, opinion-heavy.", aliases:["newsmax"]},
  {name:"One America News", country:"United States", x:9, y:-8, blurb:"Far-right cable news, low fact-checking standards.", aliases:["oan","oann","one america news"]},
  {name:"The Epoch Times", country:"United States", x:7, y:-6, blurb:"Right-leaning, associated with Falun Gong movement.", aliases:["epoch times","the epoch times"]},

  // --- UK ---
  {name:"BBC News", country:"United Kingdom", x:-1, y:4.5, blurb:"Public broadcaster, mandated impartiality standard.", aliases:["bbc","bbc news"]},
  {name:"The Economist", country:"United Kingdom", x:2, y:6, blurb:"Centrist-liberal, rigorous data-driven analysis.", aliases:["economist","the economist"]},
  {name:"Financial Times", country:"United Kingdom", x:2, y:6, blurb:"Business-focused, high factual standards.", aliases:["ft","financial times"]},
  {name:"Sky News", country:"United Kingdom", x:1, y:3.5, blurb:"Broadcast news, relatively centrist.", aliases:["sky news"]},
  {name:"The Times", country:"United Kingdom", x:3, y:4, blurb:"Center-right broadsheet.", aliases:["the times uk","times uk"]},
  {name:"The Guardian", country:"United Kingdom", x:-6, y:2.5, blurb:"Left-leaning broadsheet, strong investigative desk.", aliases:["guardian","the guardian"]},
  {name:"The Independent", country:"United Kingdom", x:-4, y:1.5, blurb:"Left-leaning digital outlet.", aliases:["independent","the independent"]},
  {name:"The Telegraph", country:"United Kingdom", x:6, y:2, blurb:"Center-right broadsheet.", aliases:["telegraph","the telegraph"]},
  {name:"Daily Mail", country:"United Kingdom", x:6, y:-4, blurb:"Right-leaning tabloid, sensationalist headlines.", aliases:["daily mail","mail online"]},
  {name:"The Sun", country:"United Kingdom", x:5, y:-6, blurb:"Right-leaning tabloid, highly sensationalist.", aliases:["the sun"]},
  {name:"The Mirror", country:"United Kingdom", x:-4, y:-3, blurb:"Left-leaning tabloid, sensationalist tendencies.", aliases:["mirror","the mirror","daily mirror"]},
  {name:"GB News", country:"United Kingdom", x:8, y:-6, blurb:"Right-leaning cable news, opinion-heavy.", aliases:["gb news"]},
  {name:"Metro", country:"United Kingdom", x:-1, y:1, blurb:"Free daily, light political framing.", aliases:["metro","metro uk"]},

  // --- international ---
  {name:"Al Jazeera", country:"Qatar", x:-2, y:2, blurb:"State-funded, strong Middle East coverage.", aliases:["al jazeera","aljazeera"]},
  {name:"Deutsche Welle", country:"Germany", x:-1, y:4, blurb:"German public international broadcaster.", aliases:["dw","deutsche welle"]},
  {name:"France 24", country:"France", x:-1, y:3.5, blurb:"French state international broadcaster.", aliases:["france 24","france24"]},
  {name:"Le Monde", country:"France", x:-3, y:4, blurb:"Center-left French paper of record.", aliases:["le monde"]},
  {name:"Der Spiegel", country:"Germany", x:-3, y:3.5, blurb:"Center-left German newsmagazine.", aliases:["der spiegel","spiegel"]},
  {name:"RT (Russia Today)", country:"Russia", x:-1, y:-8, blurb:"Russian state media, widely assessed as propaganda outlet.", aliases:["rt","russia today"]},
  {name:"Xinhua", country:"China", x:-3, y:-8, blurb:"Chinese state news agency.", aliases:["xinhua"]},
  {name:"Global Times", country:"China", x:-2, y:-7, blurb:"Chinese state-run nationalist tabloid.", aliases:["global times"]},
  {name:"CBC News", country:"Canada", x:-3, y:4, blurb:"Canadian public broadcaster, left-of-center framing.", aliases:["cbc","cbc news"]},
  {name:"ABC (Australia)", country:"Australia", x:-2, y:4, blurb:"Australian public broadcaster.", aliases:["abc australia"]},
// --- Norway ---
  {name:"NRK", country:"Norway", x:-1, y:5, blurb:"Public broadcaster, mandated impartiality, high trust.", aliases:["nrk"]},
  {name:"Aftenposten", country:"Norway", x:1, y:5, blurb:"Leading broadsheet, center-right leaning, high standards.", aliases:["aftenposten"]},
  {name:"VG", country:"Norway", x:0, y:1, blurb:"Largest tabloid, centrist, mixes hard news with sensational headlines.", aliases:["vg","verdens gang"]},
  {name:"Dagbladet", country:"Norway", x:-3, y:0, blurb:"Left-leaning tabloid.", aliases:["dagbladet"]},
  {name:"Dagens Næringsliv", country:"Norway", x:2, y:5, blurb:"Business daily, center-right, high factual standards.", aliases:["dn","dagens naeringsliv","dagens næringsliv"]},
  {name:"Klassekampen", country:"Norway", x:-7, y:3, blurb:"Socialist-aligned daily, rigorous but openly left-wing.", aliases:["klassekampen"]},
  {name:"Nettavisen", country:"Norway", x:3, y:-1, blurb:"Populist-leaning digital tabloid.", aliases:["nettavisen"]},
  {name:"TV 2 (Norway)", country:"Norway", x:0, y:3, blurb:"Commercial broadcaster, centrist framing.", aliases:["tv2","tv 2 norway"]},
  {name:"Morgenbladet", country:"Norway", x:-3, y:5, blurb:"Intellectual weekly, left-liberal.", aliases:["morgenbladet"]},
  {name:"Vårt Land", country:"Norway", x:1, y:4, blurb:"Christian daily, values-focused coverage.", aliases:["vart land","vårt land"]},
  {name:"Resett", country:"Norway", x:6, y:-5, blurb:"Right-wing populist outlet, anti-immigration framing.", aliases:["resett"]},
  {name:"Document.no", country:"Norway", x:7, y:-6, blurb:"Right-wing, anti-immigration commentary site.", aliases:["document.no","document no"]},
  {name:"Filter Nyheter", country:"Norway", x:-2, y:4, blurb:"Independent investigative outlet.", aliases:["filter nyheter"]},

  // --- Sweden / Denmark / Finland ---
  {name:"Dagens Nyheter", country:"Sweden", x:-2, y:5, blurb:"Leading liberal broadsheet, high standards.", aliases:["dn sweden","dagens nyheter"]},
  {name:"Svenska Dagbladet", country:"Sweden", x:3, y:5, blurb:"Center-right broadsheet.", aliases:["svd","svenska dagbladet"]},
  {name:"Aftonbladet", country:"Sweden", x:-4, y:0, blurb:"Left-leaning tabloid.", aliases:["aftonbladet"]},
  {name:"Expressen", country:"Sweden", x:2, y:-1, blurb:"Center-right tabloid.", aliases:["expressen"]},
  {name:"Helsingin Sanomat", country:"Finland", x:0, y:5, blurb:"Leading Finnish paper, centrist, high standards.", aliases:["helsingin sanomat","hs"]},
  {name:"Politiken", country:"Denmark", x:-3, y:4, blurb:"Center-left Danish broadsheet.", aliases:["politiken"]},
  {name:"Jyllands-Posten", country:"Denmark", x:3, y:3, blurb:"Center-right, known for 2005 Muhammad cartoons.", aliases:["jyllands-posten","jyllands posten"]},
  {name:"Berlingske", country:"Denmark", x:2, y:4, blurb:"Center-right Danish broadsheet.", aliases:["berlingske"]},

  // --- Rest of Europe ---
  {name:"El País", country:"Spain", x:-3, y:4, blurb:"Leading center-left Spanish paper.", aliases:["el pais","el país"]},
  {name:"El Mundo", country:"Spain", x:3, y:3, blurb:"Center-right Spanish paper.", aliases:["el mundo"]},
  {name:"Corriere della Sera", country:"Italy", x:1, y:4, blurb:"Centrist Italian paper of record.", aliases:["corriere della sera","corriere"]},
  {name:"La Repubblica", country:"Italy", x:-3, y:3, blurb:"Center-left Italian broadsheet.", aliases:["la repubblica","repubblica"]},
  {name:"NOS", country:"Netherlands", x:-1, y:5, blurb:"Dutch public broadcaster, high trust.", aliases:["nos"]},
  {name:"De Telegraaf", country:"Netherlands", x:3, y:0, blurb:"Right-leaning tabloid, largest circulation in NL.", aliases:["de telegraaf","telegraaf"]},
  {name:"NRC Handelsblad", country:"Netherlands", x:-2, y:5, blurb:"Center-left quality broadsheet.", aliases:["nrc","nrc handelsblad"]},
  {name:"Die Zeit", country:"Germany", x:-3, y:5, blurb:"Center-left weekly, high-quality long-form journalism.", aliases:["die zeit","zeit"]},
  {name:"Bild", country:"Germany", x:4, y:-3, blurb:"Right-leaning tabloid, highly sensationalist.", aliases:["bild"]},
  {name:"Frankfurter Allgemeine Zeitung", country:"Germany", x:3, y:5, blurb:"Center-right quality broadsheet.", aliases:["faz","frankfurter allgemeine"]},
  {name:"taz", country:"Germany", x:-7, y:3, blurb:"Left-wing alternative daily.", aliases:["taz","die tageszeitung"]},
  {name:"Gazeta Wyborcza", country:"Poland", x:-2, y:3, blurb:"Center-left, historically critical of PiS government.", aliases:["gazeta wyborcza"]},
  {name:"TVP", country:"Poland", x:4, y:-4, blurb:"State broadcaster, historically aligned with governing party.", aliases:["tvp"]},
  {name:"Kathimerini", country:"Greece", x:2, y:3, blurb:"Center-right Greek paper of record.", aliases:["kathimerini"]},
  {name:"Público", country:"Portugal", x:-3, y:3, blurb:"Center-left Portuguese broadsheet.", aliases:["publico","público"]},
// --- France ---
  {name:"Le Figaro", country:"France", x:3, y:4, blurb:"Center-right paper of record.", aliases:["le figaro","figaro"]},
  {name:"Libération", country:"France", x:-6, y:3, blurb:"Left-wing broadsheet.", aliases:["liberation","libération"]},
  {name:"Le Point", country:"France", x:2, y:4, blurb:"Center-right weekly newsmagazine.", aliases:["le point"]},
  {name:"L'Obs", country:"France", x:-3, y:3, blurb:"Center-left weekly newsmagazine.", aliases:["l'obs","lobs","le nouvel observateur"]},
  {name:"Marianne", country:"France", x:-2, y:2, blurb:"Left-populist, sovereigntist framing.", aliases:["marianne"]},
  {name:"Valeurs Actuelles", country:"France", x:7, y:-3, blurb:"Right-wing nationalist weekly.", aliases:["valeurs actuelles"]},
  {name:"BFM TV", country:"France", x:0, y:1, blurb:"24-hour commercial news channel, some sensationalism.", aliases:["bfm tv","bfmtv"]},
  {name:"TF1", country:"France", x:1, y:2, blurb:"Largest commercial broadcaster, centrist.", aliases:["tf1"]},
  {name:"Mediapart", country:"France", x:-4, y:5, blurb:"Investigative digital outlet, left-leaning, high standards.", aliases:["mediapart"]},
  {name:"CNews", country:"France", x:6, y:-4, blurb:"Right-leaning news channel, opinion-heavy.", aliases:["cnews"]},

  // --- Eastern Europe ---
  {name:"Rzeczpospolita", country:"Poland", x:2, y:4, blurb:"Center-right quality broadsheet.", aliases:["rzeczpospolita"]},
  {name:"TVN24", country:"Poland", x:-1, y:3, blurb:"Private broadcaster, historically critical of PiS government.", aliases:["tvn24","tvn"]},
  {name:"Český rozhlas", country:"Czech Republic", x:-1, y:4, blurb:"Public radio broadcaster.", aliases:["cesky rozhlas","český rozhlas"]},
  {name:"Blesk", country:"Czech Republic", x:1, y:-1, blurb:"Largest tabloid.", aliases:["blesk"]},
  {name:"Hospodářské noviny", country:"Czech Republic", x:2, y:4, blurb:"Business-focused daily.", aliases:["hospodarske noviny","hospodářské noviny","hn"]},
  {name:"Index.hu", country:"Hungary", x:-1, y:3, blurb:"Independent-leaning digital outlet.", aliases:["index.hu","index hu"]},
  {name:"Magyar Nemzet", country:"Hungary", x:6, y:-3, blurb:"Pro-government, aligned with Orbán's Fidesz.", aliases:["magyar nemzet"]},
  {name:"Digi24", country:"Romania", x:0, y:3, blurb:"Commercial news channel, relatively centrist.", aliases:["digi24"]},
  {name:"Adevărul", country:"Romania", x:-2, y:2, blurb:"Center-left daily.", aliases:["adevarul","adevărul"]},
  {name:"Novaya Gazeta", country:"Russia", x:-4, y:4, blurb:"Independent investigative outlet, operates in exile under pressure.", aliases:["novaya gazeta"]},
  {name:"Meduza", country:"Russia", x:-3, y:4, blurb:"Independent Russian outlet, operates from exile.", aliases:["meduza"]},
  {name:"Ukrainska Pravda", country:"Ukraine", x:-1, y:4, blurb:"Leading independent Ukrainian outlet.", aliases:["ukrainska pravda"]},

  // --- South America / Spanish-speaking ---
  {name:"Clarín", country:"Argentina", x:3, y:2, blurb:"Largest-circulation paper, center-right.", aliases:["clarin","clarín"]},
  {name:"La Nación", country:"Argentina", x:4, y:3, blurb:"Center-right paper of record.", aliases:["la nacion","la nación"]},
  {name:"Página/12", country:"Argentina", x:-6, y:2, blurb:"Left-wing, historically Kirchnerist-aligned.", aliases:["pagina 12","página/12","pagina12"]},
  {name:"O Globo", country:"Brazil", x:2, y:3, blurb:"Center-right, major Brazilian outlet.", aliases:["o globo","globo"]},
  {name:"Folha de S.Paulo", country:"Brazil", x:0, y:4, blurb:"Centrist paper of record.", aliases:["folha de s.paulo","folha","folha de sao paulo"]},
  {name:"Veja", country:"Brazil", x:3, y:1, blurb:"Center-right weekly newsmagazine.", aliases:["veja"]},
  {name:"El Universal", country:"Mexico", x:0, y:3, blurb:"Centrist paper of record.", aliases:["el universal mexico"]},
  {name:"Reforma", country:"Mexico", x:2, y:3, blurb:"Center-right, editorially independent.", aliases:["reforma"]},
  {name:"El Comercio", country:"Peru", x:2, y:3, blurb:"Center-right paper of record.", aliases:["el comercio"]},
  {name:"El Tiempo", country:"Colombia", x:1, y:3, blurb:"Centrist paper of record.", aliases:["el tiempo"]},
  {name:"El Mercurio", country:"Chile", x:4, y:1, blurb:"Center-right, historically influential.", aliases:["el mercurio"]},
  {name:"La Tercera", country:"Chile", x:1, y:3, blurb:"Centrist daily.", aliases:["la tercera"]},
  {name:"teleSUR", country:"Venezuela", x:-6, y:-6, blurb:"State-funded pan-Latin American broadcaster, propaganda concerns.", aliases:["telesur"]},
  {name:"Univision", country:"United States", x:-1, y:3, blurb:"Leading US Spanish-language broadcaster.", aliases:["univision"]},

  // --- More US ---
  {name:"Los Angeles Times", country:"United States", x:-3, y:4, blurb:"Major regional paper, center-left leaning.", aliases:["la times","los angeles times"]},
  {name:"Chicago Tribune", country:"United States", x:1, y:3, blurb:"Major regional paper, historically center-right.", aliases:["chicago tribune"]},
  {name:"The Boston Globe", country:"United States", x:-3, y:4, blurb:"Major regional paper, center-left leaning.", aliases:["boston globe"]},
  {name:"Miami Herald", country:"United States", x:-1, y:3, blurb:"Major regional paper, centrist.", aliases:["miami herald"]},
  {name:"San Francisco Chronicle", country:"United States", x:-3, y:3, blurb:"Major regional paper, left-leaning.", aliases:["sf chronicle","san francisco chronicle"]},
  {name:"The Dallas Morning News", country:"United States", x:2, y:3, blurb:"Major regional paper, center-right.", aliases:["dallas morning news"]},
  {name:"Houston Chronicle", country:"United States", x:0, y:3, blurb:"Major regional paper, centrist.", aliases:["houston chronicle"]},
  {name:"Axios", country:"United States", x:-1, y:4, blurb:"Digital news, concise factual format.", aliases:["axios"]},
  {name:"The Intercept", country:"United States", x:-7, y:2, blurb:"Investigative, strongly left-leaning.", aliases:["the intercept","intercept"]},
  {name:"ProPublica", country:"United States", x:-2, y:6, blurb:"Nonprofit investigative journalism, high standards.", aliases:["propublica"]},
  {name:"Mother Jones", country:"United States", x:-7, y:1, blurb:"Left-leaning investigative magazine.", aliases:["mother jones"]},
  {name:"Reason", country:"United States", x:5, y:6, blurb:"Libertarian magazine.", aliases:["reason","reason magazine"]},
  {name:"The American Conservative", country:"United States", x:6, y:1, blurb:"Paleoconservative commentary.", aliases:["american conservative"]},
  {name:"Slate", country:"United States", x:-5, y:1, blurb:"Left-leaning digital commentary.", aliases:["slate"]},
  {name:"Salon", country:"United States", x:-6, y:0, blurb:"Left-leaning digital commentary.", aliases:["salon"]},
  {name:"The New Republic", country:"United States", x:-5, y:2, blurb:"Left-leaning political commentary.", aliases:["new republic","the new republic"]},
  {name:"Time", country:"United States", x:-1, y:3, blurb:"General-interest newsmagazine, mild left lean.", aliases:["time magazine","time"]},
  {name:"Newsweek", country:"United States", x:-1, y:1, blurb:"General-interest newsmagazine.", aliases:["newsweek"]},
  {name:"Forbes", country:"United States", x:2, y:3, blurb:"Business-focused, center-right lean.", aliases:["forbes"]},
  {name:"The Daily Beast", country:"United States", x:-5, y:0, blurb:"Left-leaning digital tabloid.", aliases:["daily beast","the daily beast"]},
  {name:"The Blaze", country:"United States", x:8, y:-4, blurb:"Conservative commentary outlet.", aliases:["the blaze","blaze media"]},
  {name:"RedState", country:"United States", x:7, y:-3, blurb:"Conservative opinion outlet.", aliases:["redstate"]},
  {name:"Daily Kos", country:"United States", x:-7, y:0, blurb:"Left-leaning political blog/community.", aliases:["daily kos","dailykos"]},
  {name:"Talking Points Memo", country:"United States", x:-5, y:2, blurb:"Left-leaning political news site.", aliases:["talking points memo","tpm"]},
  {name:"The Nation", country:"United States", x:-8, y:2, blurb:"Left-wing political commentary magazine.", aliases:["the nation"]},
  {name:"The Drudge Report", country:"United States", x:3, y:-2, blurb:"Aggregator, historically right-leaning framing.", aliases:["drudge report","drudge"]},
  {name:"Semafor", country:"United States", x:0, y:4, blurb:"Newer digital outlet, centrist framing.", aliases:["semafor"]},
  {name:"The Free Press", country:"United States", x:2, y:2, blurb:"Heterodox commentary, anti-cancel-culture framing.", aliases:["the free press","bari weiss"]},

  // --- More UK ---
  {name:"The Scotsman", country:"United Kingdom", x:0, y:3, blurb:"Scottish national paper, centrist.", aliases:["the scotsman","scotsman"]},
  {name:"The Herald (Scotland)", country:"United Kingdom", x:-2, y:3, blurb:"Scottish paper, center-left.", aliases:["the herald scotland","herald scotland"]},
  {name:"Belfast Telegraph", country:"United Kingdom", x:0, y:3, blurb:"Northern Ireland's largest paper.", aliases:["belfast telegraph"]},
  {name:"Evening Standard", country:"United Kingdom", x:1, y:2, blurb:"London evening paper, centrist.", aliases:["evening standard"]},
  {name:"City AM", country:"United Kingdom", x:3, y:3, blurb:"Business-focused free paper, center-right.", aliases:["city am","cityam"]},
  {name:"Private Eye", country:"United Kingdom", x:-1, y:4, blurb:"Satirical/investigative fortnightly.", aliases:["private eye"]},
  {name:"New Statesman", country:"United Kingdom", x:-5, y:4, blurb:"Center-left political weekly.", aliases:["new statesman"]},
  {name:"The Spectator", country:"United Kingdom", x:6, y:2, blurb:"Center-right political weekly.", aliases:["the spectator","spectator"]},
  {name:"Prospect", country:"United Kingdom", x:-2, y:4, blurb:"Centrist ideas/current-affairs magazine.", aliases:["prospect magazine","prospect"]},
  {name:"PinkNews", country:"United Kingdom", x:-4, y:2, blurb:"LGBTQ-focused news outlet.", aliases:["pinknews","pink news"]},

  // --- Asia ---
  {name:"Hindustan Times", country:"India", x:0, y:3, blurb:"Major English-language daily, centrist.", aliases:["hindustan times"]},
  {name:"The Hindu", country:"India", x:-2, y:4, blurb:"Center-left, high editorial standards.", aliases:["the hindu"]},
  {name:"NDTV", country:"India", x:-1, y:2, blurb:"Broadcast news, relatively centrist.", aliases:["ndtv"]},
  {name:"Republic TV", country:"India", x:4, y:-4, blurb:"Nationalist, highly sensationalist broadcaster.", aliases:["republic tv"]},
  {name:"Zee News", country:"India", x:4, y:-3, blurb:"Nationalist-leaning broadcaster.", aliases:["zee news"]},
  {name:"China Daily", country:"China", x:-3, y:-8, blurb:"State-run English-language outlet.", aliases:["china daily"]},
  {name:"People's Daily", country:"China", x:-4, y:-9, blurb:"Official Communist Party newspaper.", aliases:["people's daily","peoples daily"]},
  {name:"CCTV", country:"China", x:-4, y:-9, blurb:"State broadcaster.", aliases:["cctv china"]},
  {name:"Asahi Shimbun", country:"Japan", x:-2, y:5, blurb:"Center-left major daily.", aliases:["asahi shimbun","asahi"]},
  {name:"Yomiuri Shimbun", country:"Japan", x:2, y:5, blurb:"Center-right, world's largest circulation daily.", aliases:["yomiuri shimbun","yomiuri"]},
  {name:"Mainichi Shimbun", country:"Japan", x:-1, y:4, blurb:"Centrist major daily.", aliases:["mainichi shimbun","mainichi"]},
  {name:"NHK", country:"Japan", x:0, y:5, blurb:"Public broadcaster, mandated impartiality.", aliases:["nhk"]},
  {name:"Chosun Ilbo", country:"South Korea", x:3, y:3, blurb:"Center-right major daily.", aliases:["chosun ilbo"]},
  {name:"JoongAng Ilbo", country:"South Korea", x:2, y:3, blurb:"Center-right major daily.", aliases:["joongang ilbo"]},
  {name:"Yonhap", country:"South Korea", x:0, y:5, blurb:"Wire service, minimal editorializing.", aliases:["yonhap"]},
  {name:"The Straits Times", country:"Singapore", x:2, y:3, blurb:"State-linked, generally supportive of government.", aliases:["straits times"]},
  {name:"South China Morning Post", country:"Hong Kong", x:0, y:2, blurb:"English-language paper, increasingly cautious post-2020.", aliases:["scmp","south china morning post"]},

  // --- Middle East ---
  {name:"Haaretz", country:"Israel", x:-4, y:4, blurb:"Left-leaning, critical investigative journalism.", aliases:["haaretz"]},
  {name:"The Jerusalem Post", country:"Israel", x:3, y:3, blurb:"Center-right English-language paper.", aliases:["jerusalem post"]},
  {name:"The Times of Israel", country:"Israel", x:1, y:4, blurb:"Centrist English-language outlet.", aliases:["times of israel"]},
  {name:"Asharq Al-Awsat", country:"Saudi Arabia", x:3, y:2, blurb:"Pan-Arab paper, Saudi-owned.", aliases:["asharq al-awsat"]},
  {name:"Al Arabiya", country:"Saudi Arabia", x:3, y:1, blurb:"Pan-Arab broadcaster, Saudi-aligned.", aliases:["al arabiya"]},
  {name:"Daily Sabah", country:"Turkey", x:4, y:-4, blurb:"Pro-government English-language outlet.", aliases:["daily sabah"]},
  {name:"Hürriyet", country:"Turkey", x:2, y:0, blurb:"Major secular-leaning daily.", aliases:["hurriyet","hürriyet"]},

  // --- Africa ---
  {name:"Daily Nation", country:"Kenya", x:0, y:3, blurb:"Leading Kenyan daily, centrist.", aliases:["daily nation","nation kenya"]},
  {name:"This Day", country:"Nigeria", x:1, y:2, blurb:"Major Nigerian daily.", aliases:["this day nigeria","thisday"]},
  {name:"Punch", country:"Nigeria", x:0, y:2, blurb:"Leading Nigerian daily.", aliases:["punch nigeria"]},
  {name:"Mail & Guardian", country:"South Africa", x:-3, y:4, blurb:"Investigative, center-left.", aliases:["mail and guardian","mail & guardian"]},
  {name:"News24", country:"South Africa", x:-1, y:3, blurb:"Leading digital news outlet.", aliases:["news24"]},

  // --- More Latin America ---
  {name:"Excélsior", country:"Mexico", x:1, y:2, blurb:"Historic major Mexican daily.", aliases:["excelsior"]},
  {name:"El Espectador", country:"Colombia", x:-2, y:4, blurb:"Center-left, investigative daily.", aliases:["el espectador"]},

  // --- More Europe ---
  {name:"La Stampa", country:"Italy", x:-1, y:4, blurb:"Center-left major daily.", aliases:["la stampa"]},
  {name:"Neue Zürcher Zeitung", country:"Switzerland", x:3, y:5, blurb:"Center-right, high-standards Swiss paper.", aliases:["nzz","neue zurcher zeitung"]},
  {name:"Le Soir", country:"Belgium", x:-2, y:3, blurb:"Center-left Belgian paper.", aliases:["le soir"]},
  {name:"De Standaard", country:"Belgium", x:1, y:4, blurb:"Center-right Flemish paper.", aliases:["de standaard"]},
  {name:"The Irish Times", country:"Ireland", x:-1, y:5, blurb:"Center-left paper of record.", aliases:["irish times"]},
  {name:"Irish Independent", country:"Ireland", x:1, y:3, blurb:"Center-right major daily.", aliases:["irish independent"]},

  // --- More Oceania ---
  {name:"Sydney Morning Herald", country:"Australia", x:-2, y:4, blurb:"Center-left major daily.", aliases:["sydney morning herald","smh"]},
  {name:"The Australian", country:"Australia", x:5, y:3, blurb:"Center-right national paper.", aliases:["the australian"]},
  {name:"News.com.au", country:"Australia", x:2, y:0, blurb:"Popular digital tabloid-style outlet.", aliases:["news.com.au"]},
  {name:"New Zealand Herald", country:"New Zealand", x:0, y:3, blurb:"Leading NZ daily, centrist.", aliases:["nz herald","new zealand herald"]},
  {name:"Stuff", country:"New Zealand", x:-1, y:3, blurb:"Major NZ digital/print outlet.", aliases:["stuff nz","stuff.co.nz"]},

  // --- More Canada ---
  {name:"The Globe and Mail", country:"Canada", x:1, y:4, blurb:"Center-right paper of record.", aliases:["globe and mail"]},
  {name:"Toronto Star", country:"Canada", x:-3, y:4, blurb:"Center-left major daily.", aliases:["toronto star"]},
  {name:"National Post", country:"Canada", x:4, y:3, blurb:"Center-right national paper.", aliases:["national post"]},
  {name:"Global News", country:"Canada", x:0, y:3, blurb:"Commercial broadcast news, centrist.", aliases:["global news canada"]},

  // --- More Nordic ---
  {name:"Dagsavisen", country:"Norway", x:-4, y:3, blurb:"Left-leaning Norwegian daily.", aliases:["dagsavisen"]},
  {name:"E24", country:"Norway", x:2, y:4, blurb:"Norwegian business/finance outlet.", aliases:["e24"]},
  {name:"iTromsø", country:"Norway", x:0, y:3, blurb:"Regional Northern Norway paper.", aliases:["itromso","itromsø"]},
  {name:"Bergens Tidende", country:"Norway", x:0, y:4, blurb:"Major regional Bergen paper.", aliases:["bergens tidende","bt"]},
  {name:"Adresseavisen", country:"Norway", x:1, y:4, blurb:"Major Trondheim regional paper.", aliases:["adresseavisen"]},
  {name:"Stavanger Aftenblad", country:"Norway", x:1, y:4, blurb:"Major Stavanger regional paper.", aliases:["stavanger aftenblad"]},
  {name:"Sveriges Television", country:"Sweden", x:-1, y:5, blurb:"Swedish public broadcaster.", aliases:["svt","sveriges television"]},
  {name:"Sveriges Radio", country:"Sweden", x:-1, y:5, blurb:"Swedish public radio.", aliases:["sveriges radio","sr sweden"]},
  {name:"DR (Danmarks Radio)", country:"Denmark", x:-1, y:5, blurb:"Danish public broadcaster.", aliases:["dr denmark","danmarks radio"]},
  {name:"Yle", country:"Finland", x:-1, y:5, blurb:"Finnish public broadcaster.", aliases:["yle"]},
  {name:"Iltalehti", country:"Finland", x:1, y:0, blurb:"Finnish tabloid.", aliases:["iltalehti"]},

  // --- More Eastern Europe / Baltics ---
  {name:"Delfi", country:"Lithuania", x:0, y:2, blurb:"Leading Baltic digital news portal.", aliases:["delfi"]},
  {name:"Postimees", country:"Estonia", x:1, y:3, blurb:"Leading Estonian daily.", aliases:["postimees"]},
  {name:"Onet", country:"Poland", x:-1, y:2, blurb:"Major Polish news portal.", aliases:["onet"]},
  {name:"Interia", country:"Poland", x:0, y:2, blurb:"Major Polish news portal.", aliases:["interia"]},
  {name:"HotNews.ro", country:"Romania", x:-1, y:3, blurb:"Independent Romanian digital outlet.", aliases:["hotnews","hotnews.ro"]},
  {name:"iROZHLAS", country:"Czech Republic", x:-1, y:4, blurb:"Czech public radio's digital news.", aliases:["irozhlas"]},
  {name:"Denník N", country:"Slovakia", x:-2, y:4, blurb:"Independent Slovak daily, critical of Fico government.", aliases:["dennik n","denník n"]},
  {name:"Nova Makedonija", country:"North Macedonia", x:0, y:2, blurb:"State-linked Macedonian daily.", aliases:["nova makedonija"]},
  {name:"B92", country:"Serbia", x:-2, y:2, blurb:"Independent-leaning Serbian outlet.", aliases:["b92"]},
  {name:"RTS (Radio Television of Serbia)", country:"Serbia", x:2, y:-3, blurb:"State broadcaster, government-aligned.", aliases:["rts serbia"]},

  // --- More Latin America ---
  {name:"ABC Color", country:"Paraguay", x:3, y:2, blurb:"Leading center-right Paraguayan daily.", aliases:["abc color"]},
  {name:"El Nacional", country:"Venezuela", x:4, y:1, blurb:"Opposition-aligned Venezuelan paper, faced state pressure.", aliases:["el nacional"]},
  {name:"El País (Uruguay)", country:"Uruguay", x:3, y:3, blurb:"Center-right leading Uruguayan daily.", aliases:["el pais uruguay"]},
  {name:"La Diaria", country:"Uruguay", x:-4, y:3, blurb:"Left-leaning Uruguayan daily.", aliases:["la diaria"]},
  {name:"La Prensa (Nicaragua)", country:"Nicaragua", x:2, y:2, blurb:"Opposition-aligned, faced Ortega-government crackdown.", aliases:["la prensa nicaragua"]},

  // --- More international wire/pan-regional ---
  {name:"Deutsche Presse-Agentur", country:"Germany", x:0, y:6, blurb:"German wire service, minimal editorializing.", aliases:["dpa"]},
  {name:"Agence France-Presse", country:"France", x:0, y:6, blurb:"French wire service, minimal editorializing.", aliases:["afp","agence france-presse"]},
  {name:"EFE", country:"Spain", x:0, y:5, blurb:"Spanish-language wire service.", aliases:["efe"]},
  {name:"ANSA", country:"Italy", x:0, y:5, blurb:"Italian wire service.", aliases:["ansa"]},
  {name:"Anadolu Agency", country:"Turkey", x:3, y:-3, blurb:"Turkish state-run wire service.", aliases:["anadolu agency","anadolu"]},

  // --- More Southeast/South Asia ---
  {name:"The Jakarta Post", country:"Indonesia", x:0, y:3, blurb:"English-language Indonesian daily, centrist.", aliases:["jakarta post"]},
  {name:"Kompas", country:"Indonesia", x:0, y:3, blurb:"Leading Indonesian-language daily.", aliases:["kompas"]},
  {name:"Bangkok Post", country:"Thailand", x:1, y:3, blurb:"English-language Thai daily, centrist.", aliases:["bangkok post"]},
  {name:"Rappler", country:"Philippines", x:-3, y:4, blurb:"Independent digital outlet, faced government pressure.", aliases:["rappler"]},
  {name:"Philippine Daily Inquirer", country:"Philippines", x:-1, y:3, blurb:"Leading Philippine daily.", aliases:["inquirer","philippine daily inquirer"]},
  {name:"Dawn", country:"Pakistan", x:-1, y:4, blurb:"Leading English-language Pakistani daily.", aliases:["dawn newspaper","dawn"]},
  {name:"The Express Tribune", country:"Pakistan", x:1, y:2, blurb:"English-language Pakistani daily.", aliases:["express tribune"]},
  {name:"Prothom Alo", country:"Bangladesh", x:-1, y:3, blurb:"Leading Bengali-language daily.", aliases:["prothom alo"]},
  {name:"The Daily Star (Bangladesh)", country:"Bangladesh", x:0, y:3, blurb:"Leading English-language Bangladeshi daily.", aliases:["daily star bangladesh"]},

  // --- More Africa ---
  {name:"Al-Ahram", country:"Egypt", x:2, y:-4, blurb:"State-linked leading Egyptian daily.", aliases:["al-ahram","al ahram"]},
  {name:"Daily Trust", country:"Nigeria", x:1, y:2, blurb:"Major Nigerian daily.", aliases:["daily trust"]},
  {name:"The East African", country:"Kenya", x:-1, y:3, blurb:"Regional East Africa weekly.", aliases:["east african"]},
  {name:"Ethiopian Herald", country:"Ethiopia", x:-1, y:-3, blurb:"State-linked English-language daily.", aliases:["ethiopian herald"]},
  {name:"Zimbabwe Independent", country:"Zimbabwe", x:1, y:2, blurb:"Independent weekly, critical of government.", aliases:["zimbabwe independent"]},

  // --- More US niche/local ---
  {name:"The Texas Tribune", country:"United States", x:-1, y:5, blurb:"Nonprofit Texas-focused outlet, high standards.", aliases:["texas tribune"]},
  {name:"CalMatters", country:"United States", x:-1, y:5, blurb:"Nonprofit California-focused outlet.", aliases:["calmatters"]},
  {name:"The 19th", country:"United States", x:-4, y:4, blurb:"Nonprofit outlet focused on gender/politics.", aliases:["the 19th","19th news"]},
  {name:"Grist", country:"United States", x:-4, y:4, blurb:"Environmental-focused nonprofit outlet.", aliases:["grist"]},
  {name:"The Marshall Project", country:"United States", x:-3, y:5, blurb:"Nonprofit criminal-justice-focused outlet.", aliases:["marshall project"]},
  {name:"Democracy Now!", country:"United States", x:-8, y:2, blurb:"Independent left-leaning broadcast outlet.", aliases:["democracy now"]},
  {name:"Jacobin", country:"United States", x:-9, y:2, blurb:"Democratic-socialist magazine.", aliases:["jacobin"]},
  {name:"Christian Broadcasting Network", country:"United States", x:6, y:0, blurb:"Evangelical Christian broadcaster.", aliases:["cbn","christian broadcasting network"]},
  {name:"Al Jazeera English", country:"Qatar", x:-2, y:3, blurb:"English-language arm, generally regarded as more independent than Arabic service.", aliases:["al jazeera english","aje"]}
];
