// Each entry: name, country, x (-10 far-left … 10 far-right, political lean of reporting/editorial),
// y (-10 sensationalist/opinion-heavy … 10 rigorous fact-based reporting), blurb, aliases
const MEDIA_OUTLETS = [
  // --- US ---
  {name:"Reuters", country:"United States/UK", x:0, y:7, blurb:"Wire service, minimal editorializing, high factual standards.", aliases:["reuters"]},
  {name:"Associated Press", country:"United States", x:-1, y:6.5, blurb:"Wire service, style guide emphasizes neutrality.", aliases:["ap","associated press","ap news"]},
  {name:"The Wall Street Journal", country:"United States", x:2, y:5.5, blurb:"News desk fairly centrist; opinion page leans right.", aliases:["wsj","wall street journal"]},
  {name:"Bloomberg", country:"United States", x:1, y:5, blurb:"Business-focused, data-driven reporting.", aliases:["bloomberg"]},
  {name:"The New York Times", country:"United States", x:-4, y:4.5, blurb:"Left-leaning editorial stance, strong investigative desk.", aliases:["nyt","new york times","the times"]},
  {name:"The Washington Post", country:"United States", x:-4, y:4.5, blurb:"Left-leaning editorial stance, investigative reporting.", aliases:["wapo","washington post"]},
  {name:"NPR", country:"United States", x:-4, y:4, blurb:"Public radio, left-leaning framing, careful sourcing.", aliases:["npr","national public radio"]},
  {name:"PBS NewsHour", country:"United States", x:-2, y:5, blurb:"Public broadcaster, measured tone.", aliases:["pbs","pbs newshour"]},
  {name:"The Atlantic", country:"United States", x:-4, y:3.5, blurb:"Left-leaning long-form journalism and opinion.", aliases:["atlantic","the atlantic"]},
  {name:"Politico", country:"United States", x:-2, y:3.5, blurb:"Insider political coverage, slight left lean.", aliases:["politico"]},
  {name:"The Hill", country:"United States", x:0, y:3.5, blurb:"Congress-focused, relatively centrist.", aliases:["the hill"]},
  {name:"USA Today", country:"United States", x:-1, y:3, blurb:"General-interest, centrist framing.", aliases:["usa today"]},
  {name:"ABC News", country:"United States", x:-2, y:3, blurb:"Broadcast network, mild left lean.", aliases:["abc news","abc"]},
  {name:"CBS News", country:"United States", x:-2, y:3, blurb:"Broadcast network, mild left lean.", aliases:["cbs news","cbs"]},
  {name:"NBC News", country:"United States", x:-3, y:3, blurb:"Broadcast network, mild-moderate left lean.", aliases:["nbc news","nbc"]},
  {name:"National Review", country:"United States", x:6, y:3, blurb:"Conservative opinion/commentary magazine.", aliases:["national review"]},
  {name:"CNN", country:"United States", x:-4, y:2, blurb:"Cable news, left-leaning framing, more opinion content than wire services.", aliases:["cnn"]},
  {name:"Vox", country:"United States", x:-6, y:1.5, blurb:"Explanatory journalism, openly left-leaning.", aliases:["vox"]},
  {name:"HuffPost", country:"United States", x:-6, y:0, blurb:"Left-leaning digital news and opinion.", aliases:["huffpost","huffington post"]},
  {name:"MSNBC", country:"United States", x:-7, y:-3, blurb:"Cable news, strongly left-leaning opinion-heavy programming.", aliases:["msnbc"]},
  {name:"Fox News", country:"United States", x:7, y:-3, blurb:"Cable news, strongly right-leaning opinion-heavy programming.", aliases:["fox news","fox"]},
  {name:"Fox Business", country:"United States", x:6, y:-1, blurb:"Business-focused, right-leaning framing.", aliases:["fox business"]},
  {name:"The Daily Wire", country:"United States", x:8, y:-4, blurb:"Conservative commentary and opinion outlet.", aliases:["daily wire","the daily wire"]},
  {name:"The Federalist", country:"United States", x:8, y:-5, blurb:"Conservative opinion outlet.", aliases:["federalist","the federalist"]},
  {name:"Breitbart News", country:"United States", x:9, y:-7, blurb:"Right-wing populist, opinion-heavy, contested factual record.", aliases:["breitbart"]},
  {name:"Newsmax", country:"United States", x:8, y:-6, blurb:"Right-leaning cable news, opinion-heavy.", aliases:["newsmax"]},
  {name:"One America News", country:"United States", x:9, y:-8, blurb:"Far-right cable news, low fact-checking standards.", aliases:["oan","oann","one america news"]},
  {name:"The Epoch Times", country:"United States", x:7, y:-6, blurb:"Right-leaning, associated with Falun Gong movement.", aliases:["epoch times","the epoch times"]},

  // --- UK ---
  {name:"BBC News", country:"United Kingdom", x:-1, y:4.5, blurb:"Public broadcaster, mandated impartiality standard.", aliases:["bbc","bbc news"]},
  {name:"The Economist", country:"United Kingdom", x:2, y:6, blurb:"Centrist-liberal, rigorous data-driven analysis.", aliases:["economist","the economist"]},
  {name:"Financial Times", country:"United Kingdom", x:2, y:6, blurb:"Business-focused, high factual standards.", aliases:["ft","financial times"]},
  {name:"Sky News", country:"United Kingdom", x:1, y:3.5, blurb:"Broadcast news, relatively centrist.", aliases:["sky news"]},
  {name:"The Times", country:"United Kingdom", x:3, y:4, blurb:"Center-right broadsheet.", aliases:["the times uk","times uk"]},
  {name:"The Guardian", country:"United Kingdom", x:-6, y:2.5, blurb:"Left-leaning broadsheet, strong investigative desk.", aliases:["guardian","the guardian"]},
  {name:"The Independent", country:"United Kingdom", x:-4, y:1.5, blurb:"Left-leaning digital outlet.", aliases:["independent","the independent"]},
  {name:"The Telegraph", country:"United Kingdom", x:6, y:2, blurb:"Center-right broadsheet.", aliases:["telegraph","the telegraph"]},
  {name:"Daily Mail", country:"United Kingdom", x:6, y:-4, blurb:"Right-leaning tabloid, sensationalist headlines.", aliases:["daily mail","mail online"]},
  {name:"The Sun", country:"United Kingdom", x:5, y:-6, blurb:"Right-leaning tabloid, highly sensationalist.", aliases:["the sun"]},
  {name:"The Mirror", country:"United Kingdom", x:-4, y:-3, blurb:"Left-leaning tabloid, sensationalist tendencies.", aliases:["mirror","the mirror","daily mirror"]},
  {name:"GB News", country:"United Kingdom", x:8, y:-6, blurb:"Right-leaning cable news, opinion-heavy.", aliases:["gb news"]},
  {name:"Metro", country:"United Kingdom", x:-1, y:1, blurb:"Free daily, light political framing.", aliases:["metro","metro uk"]},

  // --- international ---
  {name:"Al Jazeera", country:"Qatar", x:-2, y:2, blurb:"State-funded, strong Middle East coverage.", aliases:["al jazeera","aljazeera"]},
  {name:"Deutsche Welle", country:"Germany", x:-1, y:4, blurb:"German public international broadcaster.", aliases:["dw","deutsche welle"]},
  {name:"France 24", country:"France", x:-1, y:3.5, blurb:"French state international broadcaster.", aliases:["france 24","france24"]},
  {name:"Le Monde", country:"France", x:-3, y:4, blurb:"Center-left French paper of record.", aliases:["le monde"]},
  {name:"Der Spiegel", country:"Germany", x:-3, y:3.5, blurb:"Center-left German newsmagazine.", aliases:["der spiegel","spiegel"]},
  {name:"RT (Russia Today)", country:"Russia", x:-1, y:-8, blurb:"Russian state media, widely assessed as propaganda outlet.", aliases:["rt","russia today"]},
  {name:"Xinhua", country:"China", x:-3, y:-8, blurb:"Chinese state news agency.", aliases:["xinhua"]},
  {name:"Global Times", country:"China", x:-2, y:-7, blurb:"Chinese state-run nationalist tabloid.", aliases:["global times"]},
  {name:"CBC News", country:"Canada", x:-3, y:4, blurb:"Canadian public broadcaster, left-of-center framing.", aliases:["cbc","cbc news"]},
  {name:"ABC (Australia)", country:"Australia", x:-2, y:4, blurb:"Australian public broadcaster.", aliases:["abc australia"]},
// --- Norway ---
  {name:"NRK", country:"Norway", x:-1, y:5, blurb:"Public broadcaster, mandated impartiality, high trust.", aliases:["nrk"]},
  {name:"Aftenposten", country:"Norway", x:1, y:5, blurb:"Leading broadsheet, center-right leaning, high standards.", aliases:["aftenposten"]},
  {name:"VG", country:"Norway", x:0, y:1, blurb:"Largest tabloid, centrist, mixes hard news with sensational headlines.", aliases:["vg","verdens gang"]},
  {name:"Dagbladet", country:"Norway", x:-3, y:0, blurb:"Left-leaning tabloid.", aliases:["dagbladet"]},
  {name:"Dagens Næringsliv", country:"Norway", x:2, y:5, blurb:"Business daily, center-right, high factual standards.", aliases:["dn","dagens naeringsliv","dagens næringsliv"]},
  {name:"Klassekampen", country:"Norway", x:-7, y:3, blurb:"Socialist-aligned daily, rigorous but openly left-wing.", aliases:["klassekampen"]},
  {name:"Nettavisen", country:"Norway", x:3, y:-1, blurb:"Populist-leaning digital tabloid.", aliases:["nettavisen"]},
  {name:"TV 2 (Norway)", country:"Norway", x:0, y:3, blurb:"Commercial broadcaster, centrist framing.", aliases:["tv2","tv 2 norway"]},
  {name:"Morgenbladet", country:"Norway", x:-3, y:5, blurb:"Intellectual weekly, left-liberal.", aliases:["morgenbladet"]},
  {name:"Vårt Land", country:"Norway", x:1, y:4, blurb:"Christian daily, values-focused coverage.", aliases:["vart land","vårt land"]},
  {name:"Resett", country:"Norway", x:6, y:-5, blurb:"Right-wing populist outlet, anti-immigration framing.", aliases:["resett"]},
  {name:"Document.no", country:"Norway", x:7, y:-6, blurb:"Right-wing, anti-immigration commentary site.", aliases:["document.no","document no"]},
  {name:"Filter Nyheter", country:"Norway", x:-2, y:4, blurb:"Independent investigative outlet.", aliases:["filter nyheter"]},

  // --- Sweden / Denmark / Finland ---
  {name:"Dagens Nyheter", country:"Sweden", x:-2, y:5, blurb:"Leading liberal broadsheet, high standards.", aliases:["dn sweden","dagens nyheter"]},
  {name:"Svenska Dagbladet", country:"Sweden", x:3, y:5, blurb:"Center-right broadsheet.", aliases:["svd","svenska dagbladet"]},
  {name:"Aftonbladet", country:"Sweden", x:-4, y:0, blurb:"Left-leaning tabloid.", aliases:["aftonbladet"]},
  {name:"Expressen", country:"Sweden", x:2, y:-1, blurb:"Center-right tabloid.", aliases:["expressen"]},
  {name:"Helsingin Sanomat", country:"Finland", x:0, y:5, blurb:"Leading Finnish paper, centrist, high standards.", aliases:["helsingin sanomat","hs"]},
  {name:"Politiken", country:"Denmark", x:-3, y:4, blurb:"Center-left Danish broadsheet.", aliases:["politiken"]},
  {name:"Jyllands-Posten", country:"Denmark", x:3, y:3, blurb:"Center-right, known for 2005 Muhammad cartoons.", aliases:["jyllands-posten","jyllands posten"]},
  {name:"Berlingske", country:"Denmark", x:2, y:4, blurb:"Center-right Danish broadsheet.", aliases:["berlingske"]},

  // --- Rest of Europe ---
  {name:"El País", country:"Spain", x:-3, y:4, blurb:"Leading center-left Spanish paper.", aliases:["el pais","el país"]},
  {name:"El Mundo", country:"Spain", x:3, y:3, blurb:"Center-right Spanish paper.", aliases:["el mundo"]},
  {name:"Corriere della Sera", country:"Italy", x:1, y:4, blurb:"Centrist Italian paper of record.", aliases:["corriere della sera","corriere"]},
  {name:"La Repubblica", country:"Italy", x:-3, y:3, blurb:"Center-left Italian broadsheet.", aliases:["la repubblica","repubblica"]},
  {name:"NOS", country:"Netherlands", x:-1, y:5, blurb:"Dutch public broadcaster, high trust.", aliases:["nos"]},
  {name:"De Telegraaf", country:"Netherlands", x:3, y:0, blurb:"Right-leaning tabloid, largest circulation in NL.", aliases:["de telegraaf","telegraaf"]},
  {name:"NRC Handelsblad", country:"Netherlands", x:-2, y:5, blurb:"Center-left quality broadsheet.", aliases:["nrc","nrc handelsblad"]},
  {name:"Die Zeit", country:"Germany", x:-3, y:5, blurb:"Center-left weekly, high-quality long-form journalism.", aliases:["die zeit","zeit"]},
  {name:"Bild", country:"Germany", x:4, y:-3, blurb:"Right-leaning tabloid, highly sensationalist.", aliases:["bild"]},
  {name:"Frankfurter Allgemeine Zeitung", country:"Germany", x:3, y:5, blurb:"Center-right quality broadsheet.", aliases:["faz","frankfurter allgemeine"]},
  {name:"taz", country:"Germany", x:-7, y:3, blurb:"Left-wing alternative daily.", aliases:["taz","die tageszeitung"]},
  {name:"Gazeta Wyborcza", country:"Poland", x:-2, y:3, blurb:"Center-left, historically critical of PiS government.", aliases:["gazeta wyborcza"]},
  {name:"TVP", country:"Poland", x:4, y:-4, blurb:"State broadcaster, historically aligned with governing party.", aliases:["tvp"]},
  {name:"Kathimerini", country:"Greece", x:2, y:3, blurb:"Center-right Greek paper of record.", aliases:["kathimerini"]},
  {name:"Público", country:"Portugal", x:-3, y:3, blurb:"Center-left Portuguese broadsheet.", aliases:["publico","público"]},
// --- France ---
  {name:"Le Figaro", country:"France", x:3, y:4, blurb:"Center-right paper of record.", aliases:["le figaro","figaro"]},
  {name:"Libération", country:"France", x:-6, y:3, blurb:"Left-wing broadsheet.", aliases:["liberation","libération"]},
  {name:"Le Point", country:"France", x:2, y:4, blurb:"Center-right weekly newsmagazine.", aliases:["le point"]},
  {name:"L'Obs", country:"France", x:-3, y:3, blurb:"Center-left weekly newsmagazine.", aliases:["l'obs","lobs","le nouvel observateur"]},
  {name:"Marianne", country:"France", x:-2, y:2, blurb:"Left-populist, sovereigntist framing.", aliases:["marianne"]},
  {name:"Valeurs Actuelles", country:"France", x:7, y:-3, blurb:"Right-wing nationalist weekly.", aliases:["valeurs actuelles"]},
  {name:"BFM TV", country:"France", x:0, y:1, blurb:"24-hour commercial news channel, some sensationalism.", aliases:["bfm tv","bfmtv"]},
  {name:"TF1", country:"France", x:1, y:2, blurb:"Largest commercial broadcaster, centrist.", aliases:["tf1"]},
  {name:"Mediapart", country:"France", x:-4, y:5, blurb:"Investigative digital outlet, left-leaning, high standards.", aliases:["mediapart"]},
  {name:"CNews", country:"France", x:6, y:-4, blurb:"Right-leaning news channel, opinion-heavy.", aliases:["cnews"]},

  // --- Eastern Europe ---
  {name:"Rzeczpospolita", country:"Poland", x:2, y:4, blurb:"Center-right quality broadsheet.", aliases:["rzeczpospolita"]},
  {name:"TVN24", country:"Poland", x:-1, y:3, blurb:"Private broadcaster, historically critical of PiS government.", aliases:["tvn24","tvn"]},
  {name:"Český rozhlas", country:"Czech Republic", x:-1, y:4, blurb:"Public radio broadcaster.", aliases:["cesky rozhlas","český rozhlas"]},
  {name:"Blesk", country:"Czech Republic", x:1, y:-1, blurb:"Largest tabloid.", aliases:["blesk"]},
  {name:"Hospodářské noviny", country:"Czech Republic", x:2, y:4, blurb:"Business-focused daily.", aliases:["hospodarske noviny","hospodářské noviny","hn"]},
  {name:"Index.hu", country:"Hungary", x:-1, y:3, blurb:"Independent-leaning digital outlet.", aliases:["index.hu","index hu"]},
  {name:"Magyar Nemzet", country:"Hungary", x:6, y:-3, blurb:"Pro-government, aligned with Orbán's Fidesz.", aliases:["magyar nemzet"]},
  {name:"Digi24", country:"Romania", x:0, y:3, blurb:"Commercial news channel, relatively centrist.", aliases:["digi24"]},
  {name:"Adevărul", country:"Romania", x:-2, y:2, blurb:"Center-left daily.", aliases:["adevarul","adevărul"]},
  {name:"Novaya Gazeta", country:"Russia", x:-4, y:4, blurb:"Independent investigative outlet, operates in exile under pressure.", aliases:["novaya gazeta"]},
  {name:"Meduza", country:"Russia", x:-3, y:4, blurb:"Independent Russian outlet, operates from exile.", aliases:["meduza"]},
  {name:"Ukrainska Pravda", country:"Ukraine", x:-1, y:4, blurb:"Leading independent Ukrainian outlet.", aliases:["ukrainska pravda"]},

  // --- South America / Spanish-speaking ---
  {name:"Clarín", country:"Argentina", x:3, y:2, blurb:"Largest-circulation paper, center-right.", aliases:["clarin","clarín"]},
  {name:"La Nación", country:"Argentina", x:4, y:3, blurb:"Center-right paper of record.", aliases:["la nacion","la nación"]},
  {name:"Página/12", country:"Argentina", x:-6, y:2, blurb:"Left-wing, historically Kirchnerist-aligned.", aliases:["pagina 12","página/12","pagina12"]},
  {name:"O Globo", country:"Brazil", x:2, y:3, blurb:"Center-right, major Brazilian outlet.", aliases:["o globo","globo"]},
  {name:"Folha de S.Paulo", country:"Brazil", x:0, y:4, blurb:"Centrist paper of record.", aliases:["folha de s.paulo","folha","folha de sao paulo"]},
  {name:"Veja", country:"Brazil", x:3, y:1, blurb:"Center-right weekly newsmagazine.", aliases:["veja"]},
  {name:"El Universal", country:"Mexico", x:0, y:3, blurb:"Centrist paper of record.", aliases:["el universal mexico"]},
  {name:"Reforma", country:"Mexico", x:2, y:3, blurb:"Center-right, editorially independent.", aliases:["reforma"]},
  {name:"El Comercio", country:"Peru", x:2, y:3, blurb:"Center-right paper of record.", aliases:["el comercio"]},
  {name:"El Tiempo", country:"Colombia", x:1, y:3, blurb:"Centrist paper of record.", aliases:["el tiempo"]},
  {name:"El Mercurio", country:"Chile", x:4, y:1, blurb:"Center-right, historically influential.", aliases:["el mercurio"]},
  {name:"La Tercera", country:"Chile", x:1, y:3, blurb:"Centrist daily.", aliases:["la tercera"]},
  {name:"teleSUR", country:"Venezuela", x:-6, y:-6, blurb:"State-funded pan-Latin American broadcaster, propaganda concerns.", aliases:["telesur"]},
  {name:"Univision", country:"United States", x:-1, y:3, blurb:"Leading US Spanish-language broadcaster.", aliases:["univision"]}
];
